begin;
create function pg_temp.assert_true(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'FAIL: %',label;end if;end$$;
create function pg_temp.expect_error(statement text,label text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege then return;end;raise exception 'FAIL: %',label;end$$;
create or replace function private.reward_today() returns date language sql stable set search_path='' as $$select date '2028-01-15'$$;
insert into auth.users(id,email) values('11111111-1111-4111-8111-111111111111','motion-owner@example.invalid'),('22222222-2222-4222-8222-222222222222','motion-other@example.invalid');
insert into public.households(id,name,created_by) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Motion tests','11111111-1111-4111-8111-111111111111');
insert into public.household_members(household_id,user_id,role) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','owner');
insert into public.household_people(id,household_id,name,role) values('cccccccc-cccc-4ccc-8ccc-cccccccccccc','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Carl','child');
insert into public.reward_celebrations(household_id,person_id,iso_year,iso_week,threshold,completed_count) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc',2027,52,7,7);
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
create function pg_temp.config() returns jsonb language sql as $$select public.reward_action(gen_random_uuid(),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','config','{"person_id":"cccccccc-cccc-4ccc-8ccc-cccccccccccc","allowance_enabled":true,"monthly_allowance_minor":10000,"reward_enabled":true,"star_rewards_enabled":true,"default_requires_approval":false}')$$;
create function pg_temp.act(action text) returns jsonb language sql as $$select public.reward_action(gen_random_uuid(),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',action,'{"person_id":"cccccccc-cccc-4ccc-8ccc-cccccccccccc","item_id":"dddddddd-dddd-4ddd-8ddd-dddddddddddd","due_date":"2028-01-15","occurrence_date":"2028-01-15"}')$$;
create function pg_temp.claim() returns boolean language sql as $$select public.claim_reward_milestone('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc','2028-01-01')$$;
select pg_temp.config();
update public.reward_person_config set weekly_celebration_enabled=false;
select pg_temp.config();
select pg_temp.assert_true((select not weekly_celebration_enabled from public.reward_person_config),'Deprecated config values remain untouched');
select pg_temp.assert_true(not (public.get_reward_state('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')->'configs'->0 ? 'weekly_celebration_enabled'),'Active state excludes legacy preference');
select pg_temp.assert_true(not pg_temp.claim(),'Zero eligible tasks never claims a milestone');
insert into public.calendar_items(id,household_id,created_by,title,date,type,person,data) values('dddddddd-dddd-4ddd-8ddd-dddddddddddd','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','Approval task','2028-01-15','Opgave','Alle','{"rewardMode":"allowance","requiresApproval":true}');
select pg_temp.act('complete');
select pg_temp.assert_true(not pg_temp.claim(),'Pending completion cannot claim');
select pg_temp.act('approve');
set local role authenticated;
select pg_temp.assert_true(pg_temp.claim(),'First verified 100 percent claims once');
select pg_temp.assert_true(not pg_temp.claim(),'Retry and second device cannot repeat milestone');
select pg_temp.act('undo');select pg_temp.act('complete');select pg_temp.act('approve');
select pg_temp.assert_true(not pg_temp.claim(),'Undo and re-complete cannot repeat monthly milestone');
select pg_temp.assert_true(not public.claim_reward_milestone('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc','2027-12-01'),'Historical month cannot animate');
select pg_temp.expect_error($q$insert into public.reward_monthly_milestones(household_id,person_id,month_start,earned_minor) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc','2028-02-01',10000)$q$,'Clients cannot forge milestone state');
select pg_temp.assert_true(jsonb_array_length(public.export_family_data('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')->'monthly_milestones')=1,'Export contains milestone history');
select pg_temp.assert_true((select count(*)=1 from public.reward_celebrations),'Historical celebrations preserved without new writes');
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
select pg_temp.expect_error($q$select pg_temp.claim()$q$,'Other household cannot claim milestone');
select pg_temp.assert_true((select count(*)=0 from public.reward_monthly_milestones),'RLS hides milestone of other household');
reset role;set local role anon;
select pg_temp.expect_error($q$select pg_temp.claim()$q$,'Anonymous milestone claim denied');
reset role;
delete from public.households where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
select pg_temp.assert_true((select count(*)=0 from public.reward_monthly_milestones),'Household deletion includes milestone state');
rollback;
