-- Isolated civil-date fixtures; clock changes and data are rolled back.
begin;
create function pg_temp.assert_true(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end$$;
create function pg_temp.expect_error(statement text,label text) returns void language plpgsql as $$begin begin execute statement;exception when others then if sqlstate not in ('42501','P0001','23514') then raise;end if;return;end;raise exception 'FAIL: %',label;end$$;
create or replace function private.reward_today() returns date language sql stable set search_path='' as $$select current_setting('test.reward_today')::date$$;
select set_config('test.reward_today','2028-01-15',true);
insert into auth.users(id,email) values('11111111-1111-4111-8111-111111111111','reward-dates@example.invalid');
insert into public.households(id,name,created_by) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Date tests','11111111-1111-4111-8111-111111111111');
insert into public.household_members(household_id,user_id,role) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','owner');
insert into public.household_people(id,household_id,name,role) values('cccccccc-cccc-4ccc-8ccc-cccccccccccc','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Carl','child');
create function pg_temp.act(action text,payload jsonb) returns jsonb language sql as $$select public.reward_action(gen_random_uuid(),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',action,payload)$$;
create function pg_temp.config(amount int default 10000,enabled boolean default true) returns jsonb language sql as $$select pg_temp.act('config',jsonb_build_object('person_id','cccccccc-cccc-4ccc-8ccc-cccccccccccc','reward_enabled',enabled,'allowance_enabled',true,'monthly_allowance_minor',amount,'star_rewards_enabled',true,'weekly_celebration_enabled',true,'default_requires_approval',false))$$;
create function pg_temp.month(day date) returns jsonb language sql as $$select private.allowance_month('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc',day)$$;
create function pg_temp.complete(id uuid,day date) returns jsonb language sql as $$select pg_temp.act('complete',jsonb_build_object('person_id','cccccccc-cccc-4ccc-8ccc-cccccccccccc','item_id',id,'due_date',day,'occurrence_date',day))$$;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
alter table public.reward_person_config alter column created_at set default private.reward_today()::timestamptz;
select pg_temp.config();
update public.reward_person_config set created_at='2028-01-15T10:00:00Z';
insert into public.calendar_items(id,household_id,created_by,title,date,type,person,data) values
 ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','Weekly','2028-01-15','Opgave','Alle','{"rewardMode":"allowance","repeatWeekly":true,"seriesId":"dddddddd-dddd-4ddd-8ddd-dddddddddddd"}');
select pg_temp.assert_true((pg_temp.month('2028-01-15')->>'eligible_total')::int=3,'Weekly starts midmonth; future occurrences included');
select pg_temp.complete('dddddddd-dddd-4ddd-8ddd-dddddddddddd','2028-01-15');
select pg_temp.assert_true((pg_temp.month('2028-01-15')->>'earned_minor')::int=3333,'Integer rounding one third');
select pg_temp.expect_error($q$select pg_temp.complete('dddddddd-dddd-4ddd-8ddd-dddddddddddd','2028-01-22')$q$,'Cannot complete future');
select pg_temp.config(20000);
select pg_temp.assert_true((pg_temp.month('2028-01-15')->>'allowance_minor')::int=10000,'Monthly amount locked');
select set_config('test.reward_today','2028-02-01',true);
select public.get_reward_state('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
select public.get_reward_state('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
select pg_temp.assert_true((select count(*)=1 and min(earned_minor)=3333 from public.allowance_monthly_snapshots),'January February finalization once');
select pg_temp.assert_true((pg_temp.month('2028-02-01')->>'allowance_minor')::int=20000,'Next month uses new amount');
select pg_temp.assert_true((pg_temp.month('2028-02-01')->>'eligible_total')::int=4,'Weekly crosses month boundary');
update public.calendar_items set data=data||'{"repeatUntil":"2028-02-15"}' where id='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
select pg_temp.assert_true((pg_temp.month('2028-02-01')->>'eligible_total')::int=2,'Repeat end midmonth inclusive');
select pg_temp.assert_true((select earned_minor=3333 from public.allowance_monthly_snapshots limit 1),'Closed snapshot immutable after recurrence edit');
select pg_temp.act('payout',jsonb_build_object('id',(select id from public.allowance_monthly_snapshots limit 1)));
select pg_temp.act('payout',jsonb_build_object('id',(select id from public.allowance_monthly_snapshots limit 1)));
select pg_temp.assert_true((select payout_status='paid' and paid_at is not null and paid_by=auth.uid() and earned_minor=3333 from public.allowance_monthly_snapshots limit 1),'Payout idempotent without money mutation');
insert into public.calendar_items(id,household_id,created_by,title,date,type,person,data) values
 ('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','Leap day','2028-02-29','Opgave','Alle','{"rewardMode":"allowance"}');
select pg_temp.assert_true((pg_temp.month('2028-02-01')->>'eligible_total')::int=3,'Leap day included');
select pg_temp.config(20000,false);
select pg_temp.assert_true((pg_temp.month('2028-02-01')->>'eligible_total')::int=0,'Disable applies tomorrow; future denominator removed');
select set_config('test.reward_today','2028-02-02',true);
select pg_temp.config(20000,true);
select pg_temp.assert_true((pg_temp.month('2028-02-01')->>'eligible_total')::int=3,'Re-enable from next day');
update public.calendar_items set data=data||'{"exceptions":["2028-02-05"]}' where id='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
select pg_temp.assert_true((pg_temp.month('2028-02-01')->>'eligible_total')::int=2,'Deleted occurrence excluded');
insert into public.calendar_items(id,household_id,created_by,title,date,type,person,done) values
 ('ffffffff-ffff-4fff-8fff-ffffffffffff','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','Old done','2028-01-01','Opgave','Alle',true);
update public.calendar_items set data='{"rewardMode":"stars","starValue":50}' where id='ffffffff-ffff-4fff-8fff-ffffffffffff';
select pg_temp.assert_true((select count(*)=0 from public.reward_star_ledger),'Reward edit never awards old completions');
select pg_temp.assert_true((select done from public.calendar_items where id='ffffffff-ffff-4fff-8fff-ffffffffffff'),'Legacy completion preserved');
select pg_temp.assert_true((select private.task_reward_rule(data,'2028-01-01')->>'mode'='none' from public.calendar_items where id='ffffffff-ffff-4fff-8fff-ffffffffffff'),'Historical rule remains none');
select set_config('test.reward_today','2029-01-01',true);
select public.get_reward_state('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
select pg_temp.assert_true((select count(*)=12 from public.allowance_monthly_snapshots),'December January and skipped months finalize once');
select pg_temp.assert_true((select count(*)=0 from private.reward_task_instances('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','2029-02-01','2029-02-28')),'Nonleap February excludes prior leap task');
set local role authenticated;
select pg_temp.expect_error($q$update public.allowance_monthly_snapshots set earned_minor=999999$q$,'Member cannot rewrite snapshot');
select pg_temp.expect_error($q$delete from public.reward_star_ledger$q$,'Member cannot erase ledger');
select pg_temp.expect_error($q$select private.finalize_reward_months('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')$q$,'Internal definer not callable');
rollback;
