import {t,userError,dateFormatter,formatNumber,householdCurrency,weekdays} from '../i18n/index.js'
import {escape as e} from './product-ui.js'
import {currentAgreement,periodLabel,dutyLabel,allowancePreview} from './allowance-model.js'
import {currency,parseCurrency,rewardConfig,enabled,rewardToday} from './rewards-model.js'
export function agreementSettings(ui,pid){
 if(!ui.adult)return;
 const c=ui.c,p=c.people.find(p=>p.id===pid),cfg=rewardConfig(c.state,pid),a=currentAgreement(c.state,pid),current=c.state.monthly.find(m=>m.person_id===pid);
 let duties=structuredClone(a?.duties||[]),cadence=a?.cadence||'month';
 ui.modal((t("app.tasks_rewards")),'<section class="allowance-settings"><p class="eyebrow">'+e(p.name)+'</p>'+(a?.needs_review?("<p class=\"allowance-review\" role=\"status\">"+t("allowance.the_allowance_agreement_needs_review_previous_amounts_and_history_are_preserved")+"</p>"):'')+
 ("<form id=\"allowance-form\" class=\"stack-form\"><h3>"+t("allowance.allowance_agreement")+"</h3><div class=\"allowance-amount\"><label>"+t('currency.amount',{currency:householdCurrency()})+"<input name=\"amount\" inputmode=\"decimal\" required value=\"")+formatNumber((a?.amount_minor??cfg.monthly_allowance_minor)/100,{useGrouping:false})+("\"></label><label>"+t("allowance.period")+"<select name=\"cadence\"><option value=\"month\" ")+(cadence==='month'?'selected':'')+(">"+t("app.month")+"</option><option value=\"week\" ")+(cadence==='week'?'selected':'')+(">"+t("app.week")+"</option></select></label></div><label><input name=\"paused\" type=\"checkbox\" ")+(a?.paused?'checked':'')+("> "+t("allowance.pause_from_next_period")+"</label><h4>"+t("allowance.regular_chores")+"</h4><p class=\"hint\">"+t("allowance.chores_earn_allowance_bonus_jobs_earn_only")+"</p><div id=\"allowance-duties\"></div><button type=\"button\" id=\"allowance-add\">"+t("allowance.add_regular_chore")+"</button>")+
 (!current&&(!a||a.needs_review)?("<label>"+t("allowance.first_period")+"<select name=\"start\"><option value=\"next\">"+t("allowance.start_next_period")+"</option><option value=\"today\">"+t("allowance.start_today_full_amount_for_the_rest_of_the_period")+"</option></select></label>"):'')+
 '<p class="allowance-next" role="status"></p><button type="submit" '+(!c.online?'disabled':'')+(">"+t("allowance.save_agreement")+"</button></form>")+
 (current?("<section class=\"allowance-current\"><h4>"+t("allowance.current_period")+" ")+e(periodLabel(current))+'</h4><p><strong>'+(current.earned_minor==null?(t("allowance.awaiting_agreement")):currency(current.earned_minor))+' / '+currency(current.allowance_minor)+'</strong> · '+current.completed_total+' / '+current.eligible_total+(" "+t("allowance.chores_completed"))+(current.excused_total?' · '+current.excused_total+(" "+t("rewards.excused_fritaget")):'')+'</p><p class="hint">'+current.expected_total+(" "+t("allowance.original_chores_amount_and_chores_are_fixed")+"</p><p class=\"hint\">"+t("allowance.need_to_remove_a_chore_now_use_excuse_on_the_task_agreement_changes_apply_from_the_next_period")+"</p></section>"):'')+
 ("<details class=\"allowance-star-settings\"><summary>"+t("allowance.bonus_stars_and_participation")+"</summary><form id=\"reward-config-form\" class=\"stack-form\" data-person=\"")+pid+'"><input type="hidden" name="amount" value="'+cfg.monthly_allowance_minor/100+'">'+(cfg.allowance_enabled?'<input type="hidden" name="allowance_enabled" value="on">':'')+
 [['reward_enabled',(t("allowance.participates_in_tasks_rewards")),enabled(p)],['star_rewards_enabled',(t("app.bonus_stars")),cfg.star_rewards_enabled],['default_requires_approval',(t("allowance.new_bonus_tasks_require_adult_approval")),cfg.default_requires_approval]].map(([k,l,v])=>'<label><input type="checkbox" name="'+k+'" '+(v?'checked':'')+'> '+l+'</label>').join('')+("<button type=\"submit\">"+t("allowance.save_participation")+"</button></form></details></section>"),'allowance');
 const form=ui.root.querySelector('#allowance-form'),list=ui.root.querySelector('#allowance-duties');
 const preview=()=>{
  const f=new FormData(form),today=rewardToday(),day=new Date(today+'T12:00:00'),weekly=f.get('cadence')==='week';
  let start=current?.period_end;
  if(start){day.setTime(new Date(start+'T12:00:00').getTime());day.setDate(day.getDate()+1)}
  else if(a&&!a.needs_review&&a.effective_from>today)day.setTime(new Date(a.effective_from+'T12:00:00').getTime());
  else if(f.get('start')!=='today'){if(weekly)day.setDate(day.getDate()+((8-(day.getDay()||7))));else {day.setMonth(day.getMonth()+1,1)}}
  const label=dateFormatter({day:'numeric',month:'long'}).format(day);
  const estimate=allowancePreview(duties,new Intl.DateTimeFormat('en-CA').format(day),f.get('cadence'));
  form.querySelector('.allowance-next').textContent=(f.has('paused')?(t("allowance.the_agreement_will_be_paused_no_new_chores_will_be_created")+" "):p.name+(" "+t("allowance.will_have")+" ")+estimate.expected+(" "+t("allowance.expected_chores_in_the_next_period")+" "))+(t("allowance.applies_from")+" ")+label+'. '+(f.get('start')==='today'?(t("allowance.only_chores_from_today_count_the_full_amount_applies_to_the_shorter_first_period")):(t("allowance.the_change_does_not_affect")+" ")+p.name+(t("allowance.s_current_allowance_period")));
 };
 const render=()=>{
  list.innerHTML=duties.map((d,i)=>'<article class="allowance-duty" data-duty="'+i+("\"><label>"+t("allowance.chore")+"<input data-field=\"title\" maxlength=\"160\" required value=\"")+e(d.title)+("\" placeholder=\""+t("allowance.for_example_empty_the_dishwasher")+"\"></label><label>"+t("app.when")+"<select data-field=\"schedule\">")+[['daily',(t("allowance.every_day"))],['weekdays',(t("app.all_weekdays"))],['selected',(t("allowance.selected_weekdays"))],['weekly',(t("allowance.once_a_week"))]].map(([v,l])=>'<option value="'+v+'" '+(v===d.schedule?'selected':'')+'>'+l+'</option>').join('')+'</select></label><div class="allowance-weekdays" '+(d.schedule!=='selected'?'hidden':'')+'>'+weekdays().map((n,j)=>'<label><input type="checkbox" data-weekday="'+(j+1)+'" '+(d.weekdays?.includes(j+1)?'checked':'')+'><span>'+n+'</span></label>').join('')+'</div><small>'+e(dutyLabel(d))+(d.schedule==='weekly'?(" "+t("allowance.complete_it_when_it_suits_you_during_the_week")):'')+'</small><label><input type="checkbox" data-field="approval" '+(d.approval?'checked':'')+("> "+t("allowance.adult_approval")+"</label><button type=\"button\" data-remove-duty=\"")+i+("\" class=\"text-button\">"+t("allowance.remove_from_next_period")+"</button></article>")).join('')||("<p class=\"hint\">"+t("allowance.no_regular_chores_set_up_the_period_shows_0")+"</p>");
  list.querySelectorAll('[data-field]').forEach(input=>input.onchange=()=>{const d=duties[Number(input.closest('[data-duty]').dataset.duty)];d[input.dataset.field]=input.type==='checkbox'?input.checked:input.value;if(input.dataset.field==='schedule')render()});
  list.querySelectorAll('[data-weekday]').forEach(input=>input.onchange=()=>{const d=duties[Number(input.closest('[data-duty]').dataset.duty)];d.weekdays=[...input.closest('.allowance-weekdays').querySelectorAll('input:checked')].map(x=>Number(x.dataset.weekday))});
  list.querySelectorAll('[data-remove-duty]').forEach(b=>b.onclick=()=>{duties.splice(Number(b.dataset.removeDuty),1);render();preview()});
 };
 ui.root.querySelector('#allowance-add').onclick=()=>{if(duties.length>=30)return;duties.push({title:'',schedule:'weekdays',weekdays:[1,2,3,4,5],approval:cfg.default_requires_approval});render();list.lastElementChild.querySelector('input').focus();preview()};
 form.onchange=preview;form.onsubmit=ev=>{ev.preventDefault();try{const f=new FormData(form);ui.run('allowance_save',{person_id:pid,amount_minor:parseCurrency(f.get('amount')),cadence:f.get('cadence'),duties,paused:f.has('paused'),start_today:f.get('start')==='today',expected:a?.expected||null},ev.submitter)}catch(error){ui.root.querySelector('#reward-dialog-message').textContent=userError(error)}};
 render();preview();
}
export function allowanceHistory(ui,pid){
 const rows=(ui.c.state.contracts||[]).filter(s=>s.closed_at&&(pid==='Alle'||s.person_id===pid)).slice(0,6);
 return rows.map(s=>'<article class="allowance-history-row"><div><strong>'+e(ui.c.people.find(p=>p.id===s.person_id)?.name)+' · '+e(periodLabel(s))+'</strong><small>'+s.completed_total+' / '+s.eligible_total+(" "+t("allowance.chores")+" ")+(s.earned_minor==null?(t("allowance.all_chores_excused_amount_to_be_agreed")):currency(s.earned_minor))+'</small></div>'+
 (s.payout_status==='paid'?("<span>"+t("allowance.paid")+"</span>"):s.earned_minor==null?ui.adult?'<button data-allowance-resolve="'+s.id+'" data-amount="'+s.allowance_minor+("\">"+t("allowance.agree_amount")+"</button>"):("<span>"+t("allowance.awaiting_an_adult")+"</span>"):ui.adult?ui.button('allowance_payout',{id:s.id},(t("allowance.mark_paid")),!ui.c.online):("<span>"+t("allowance.awaiting_payment")+"</span>"))+'</article>').join('');
}
