import {categoryLabel} from '../i18n/domain-labels.js'
import {t,dateFormatter,labels} from '../i18n/index.js'
import { weekDates,parseDate,dateIso,calendarHeading } from './calendar-dates.js'
import { mealsOn,shoppingItems,SHOPPING_CATEGORIES } from './household-plans.js'
export const escape=val=>String(val??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const paths={today:'M3 10 12 3l9 7v10H3Z M9 20v-7h6v7',calendar:'M4 5h16v16H4Z M4 10h16 M8 3v4 M16 3v4',tasks:'M9 6h12 M9 12h12 M9 18h12 M3 6l1 1 2-3 M3 12l1 1 2-3 M3 18l1 1 2-3',meals:'M4 3v6q0 3 3 3V3 M7 12v9 M15 3v8h5 M20 3v18',shopping:'M3 4h2l3 12h10l3-8H6 M9 20h.01 M18 20h.01',family:'M16 21v-3a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v3 M20 21v-3a4 4 0 0 0-3-4 M9.5 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M17 4a4 4 0 0 1 0 7',plus:'M12 5v14 M5 12h14',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1Z M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6',arrow:'M5 12h14 M14 7l5 5-5 5',sun:'M12 3v2 M12 19v2 M3 12h2 M19 12h2 M5.5 5.5l1.5 1.5 M17 17l1.5 1.5 M5.5 18.5 7 17 M17 7l1.5-1.5 M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8'}
export const icon=name=>'<svg class="ux-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[name]||paths.today)+'"/></svg>'
export const routeLabels=labels({today:'nav.today',calendar:'nav.calendar',tasks:'nav.tasks',meals:'nav.meal_plan',shopping:'nav.shopping',family:'nav.family',recipes:'app.recipes'})
export function renderNavigation(route,kiosk,mobile=false){
 const entries=kiosk?['today','calendar','food','tasks']:['today','calendar','food','tasks','family']
 const active=['meals','shopping','recipes'].includes(route)?'food':route
 return ("<nav class=\"product-nav\" aria-label=\""+t("product.main_navigation")+"\">")+entries.map(id=>'<button type="button" data-product-route="'+id+'" aria-current="'+(id===active?'page':'false')+'">'+icon(id==='food'?'meals':id)+'<span>'+(id==='food'?(t("nav.meals")):routeLabels[id])+'</span></button>').join('')+'</nav>'
}
export function renderMeals(rows,cursor,kiosk=false,compact=false,recipes=[]){
 const today=dateIso(new Date()),days=weekDates(dateIso(cursor))
 return '<div class="meal-view">'+(compact?'':("<div class=\"ux-view-intro\"><div><p class=\"eyebrow\">"+t("product.an_easier_everyday_life")+"</p><h3>"+t("plan_editor.what_shall_we_eat")+"</h3><p>"+t("product.plan_together_take_the_ingredients_shopping")+"</p></div></div>"))+(compact?'<div class="meal-calendar-heading"><p class="meal-week-label">'+escape(calendarHeading(days[0],'week').replace((t("calendar_dates.this_week_week")),(t("app.week"))))+("</p><div class=\"meal-week-nav\"><button data-meal-week=\"-1\" aria-label=\""+t("product.previous_meal_plan_week")+"\">←</button><button data-meal-week=\"0\">"+t("app.this_week")+"</button><button data-meal-week=\"1\" aria-label=\""+t("product.next_meal_plan_week")+"\">→</button></div></div>"):("<div class=\"meal-week-nav\"><button data-meal-week=\"-1\" aria-label=\""+t("product.previous_meal_plan_week")+"\">←</button><div><strong>")+escape(calendarHeading(days[0],'week'))+("</strong><button data-meal-week=\"0\" class=\"text-button\">"+t("app.this_week")+"</button></div><button data-meal-week=\"1\" aria-label=\""+t("product.next_meal_plan_week")+"\">→</button></div>"))+'<div class="meal-week">'+days.map(date=>{
 const meals=mealsOn(rows,date),day=parseDate(date)
 return '<section class="meal-day '+(date===today?'is-today':'')+'" data-meal-date="'+date+'"><header><span>'+escape(dateFormatter({weekday:'long'}).format(day))+'</span><strong>'+escape(dateFormatter({day:'numeric',month:'short'}).format(day))+'</strong>'+(date===today?("<small>"+t("nav.today")+"</small>"):'')+'</header><div class="meal-day-content">'+(meals.length?meals.map(meal=>{const recipe=recipes.find(r=>r.id===(meal.recipe_id||meal.data?.recipe_id));return '<article class="meal-card"><button data-plan-edit="'+meal.id+'">'+(recipe?.image_display_url&&!kiosk?'<img class="meal-recipe-thumbnail" src="'+escape(recipe.image_display_url)+'" alt="" width="48" height="48" loading="lazy" decoding="async">':'<span class="meal-symbol">'+icon('meals')+'</span>')+'<strong>'+escape(recipe?.title||meal.title)+'</strong><small>'+escape(meal.time||(t("app.dinner")))+'</small></button>'+((recipe?.recipe_ingredients?.length||meal.data?.recipe?.ingredients?.length||meal.note)&&!kiosk?'<button class="ingredient-button" data-meal-ingredients="'+meal.id+'">'+icon('shopping')+(" "+t("product.add_ingredients")+"</button>"):'')+'</article>'}).join(''):'<p class="meal-empty">'+(compact?(t("product.not_planned")):(t("product.room_for_something_good")))+'</p>')+(!kiosk?'<button class="meal-add" data-plan-new="meal" data-plan-date="'+date+'" aria-label="'+t('product.plan_meal_date',{date})+'">'+icon('plus')+(meals.length?(t("product.add_meal")):(t("product.plan")))+'</button>':'')+'</div></section>'
 }).join('')+'</div></div>'
}
export function renderShopping(rows,draft={},compact=false,kiosk=false){
 if(kiosk)return renderKioskShopping(rows)
 const all=shoppingItems(rows),open=all.filter(row=>!row.done),done=all.filter(row=>row.done)
 const item=row=>'<li class="shopping-row '+(row.done?'is-bought':'')+'"><label class="shopping-check"><input type="checkbox" data-shopping-toggle="'+row.id+'" '+(row.done?'checked':'')+' aria-label="'+escape((row.done?(t("product.mark_as_needed")+" "):(t("product.bought")+" "))+row.title)+'"><span aria-hidden="true"></span></label><button class="shopping-name" data-plan-edit="'+row.id+'"><strong>'+escape(row.title)+'</strong>'+(row.note?'<small>'+escape(row.note)+'</small>':'')+'</button></li>'
 return '<div class="shopping-view">'+(compact?'<p class="shopping-count">'+t('shopping.count',{count:open.length})+(" "+t("product.on_the_list")+"</p>"):("<div class=\"ux-view-intro\"><div><p class=\"eyebrow\">"+t("product.the_family_s_shared_list")+"</p><h3>"+t("product.remember_everything")+"</h3><p>")+t('shopping.count',{count:open.length})+(" "+t("product.left_the_list_follows_everyone")+"</p></div><span class=\"ux-round-icon\">")+icon('shopping')+'</span></div>')+("<form id=\"shopping-add\" class=\"shopping-add ux-inline-form\"><label for=\"shopping-title\" class=\"sr-only\">"+t("plan_editor.item")+"</label><input id=\"shopping-title\" name=\"title\" placeholder=\""+t("product.add_item")+"\" maxlength=\"160\" value=\"")+escape(draft.title||'')+("\" required autocomplete=\"off\"><label for=\"shopping-note\" class=\"sr-only\">"+t("product.quantity")+"</label><input id=\"shopping-note\" name=\"note\" placeholder=\""+t("product.quantity")+"\" maxlength=\"120\" value=\"")+escape(draft.note||'')+("\"><button type=\"submit\" aria-label=\""+t("product.add_item_tilf_j_vare")+"\">")+icon('plus')+("<span>"+t("product.add")+"</span></button></form><p class=\"hint shopping-tip\">"+t("product.enter_an_item_and_press_enter_you_can_also_add_ingredients_from_the_meal_plan")+"</p><div class=\"shopping-groups\">")+(open.length?SHOPPING_CATEGORIES.map(category=>{const items=open.filter(row=>(SHOPPING_CATEGORIES.includes(row.location)?row.location:'Andet')===category);return items.length?'<section class="shopping-group"><h4>'+escape(categoryLabel(category))+' <span>'+items.length+'</span></h4><ul>'+items.map(item).join('')+'</ul></section>':''}).join(''):'<div class="ux-empty">'+icon('shopping')+("<h4>"+t("product.the_list_is_empty")+"</h4><p>"+t("product.add_the_first_item_or_find_inspiration_in_the_meal_plan")+"</p><button data-go-route=\"meals\">"+t("product.go_to_meal_plan")+" ")+icon('arrow')+'</button></div>')+'</div>'+(done.length?'<details class="shopping-completed"><summary>'+done.length+(" "+t("product.purchased_items")+"</summary><ul>")+done.map(item).join('')+("</ul><button id=\"clear-shopping\" class=\"text-button\">"+t("product.remove_purchased_items_from_the_list")+"</button></details>"):'')+'</div>'
}

function renderKioskShopping(rows){
 const items=shoppingItems(rows).filter(row=>!row.done)
 return '<div class="kiosk-shopping"><p class="shopping-count">'+t('shopping.count',{count:items.length})+(" "+t("product.on_the_family_s_list")+"</p><div class=\"shopping-groups\">")+(items.length?SHOPPING_CATEGORIES.map(category=>{const group=items.filter(row=>(SHOPPING_CATEGORIES.includes(row.location)?row.location:'Andet')===category);return group.length?'<section class="shopping-group"><h4>'+escape(categoryLabel(category))+'</h4><ul>'+group.map(row=>'<li class="shopping-row"><span class="shopping-name"><strong>'+escape(row.title)+'</strong>'+(row.note?'<small>'+escape(row.note)+'</small>':'')+'</span></li>').join('')+'</ul></section>':''}).join(''):("<p class=\"empty-state\">"+t("product.the_list_is_empty_listen_er_tom_")+"</p>"))+'</div></div>'
}
