import { weekDates,parseDate,dateIso,calendarHeading } from './calendar-dates.js'
import { mealsOn,shoppingItems,SHOPPING_CATEGORIES } from './household-plans.js'
export const escape=val=>String(val??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const paths={today:'M3 10 12 3l9 7v10H3Z M9 20v-7h6v7',calendar:'M4 5h16v16H4Z M4 10h16 M8 3v4 M16 3v4',tasks:'M9 6h12 M9 12h12 M9 18h12 M3 6l1 1 2-3 M3 12l1 1 2-3 M3 18l1 1 2-3',meals:'M4 3v6q0 3 3 3V3 M7 12v9 M15 3v8h5 M20 3v18',shopping:'M3 4h2l3 12h10l3-8H6 M9 20h.01 M18 20h.01',family:'M16 21v-3a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v3 M20 21v-3a4 4 0 0 0-3-4 M9.5 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M17 4a4 4 0 0 1 0 7',plus:'M12 5v14 M5 12h14',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1Z M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6',arrow:'M5 12h14 M14 7l5 5-5 5',sun:'M12 3v2 M12 19v2 M3 12h2 M19 12h2 M5.5 5.5l1.5 1.5 M17 17l1.5 1.5 M5.5 18.5 7 17 M17 7l1.5-1.5 M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8'}
export const icon=name=>'<svg class="ux-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[name]||paths.today)+'"/></svg>'
export const routeLabels={today:'I dag',calendar:'Kalender',tasks:'Opgaver',meals:'Madplan',shopping:'Indkøb',family:'Familie',recipes:'Opskrifter'}
export function renderNavigation(route,kiosk,mobile=false){
 const entries=kiosk?['today','calendar','food','tasks']:['today','calendar','food','tasks','family']
 const active=['meals','shopping','recipes'].includes(route)?'food':route
 return '<nav class="product-nav" aria-label="Primær navigation">'+entries.map(id=>'<button type="button" data-product-route="'+id+'" aria-current="'+(id===active?'page':'false')+'">'+icon(id==='food'?'meals':id)+'<span>'+(id==='food'?'Mad & indkøb':routeLabels[id])+'</span></button>').join('')+'</nav>'
}
export function renderMeals(rows,cursor,kiosk=false,compact=false,recipes=[]){
 const today=dateIso(new Date()),days=weekDates(dateIso(cursor))
 return '<div class="meal-view">'+(compact?'':'<div class="ux-view-intro"><div><p class="eyebrow">Lidt lettere hverdag</p><h3>Hvad skal vi spise?</h3><p>Planlæg sammen. Tag ingredienserne med på indkøb.</p></div></div>')+(compact?'<div class="meal-calendar-heading"><p class="meal-week-label">'+escape(calendarHeading(days[0],'week').replace('Denne uge · uge','Uge'))+'</p><div class="meal-week-nav"><button data-meal-week="-1" aria-label="Forrige madplansuge">←</button><button data-meal-week="0">Denne uge</button><button data-meal-week="1" aria-label="Næste madplansuge">→</button></div></div>':'<div class="meal-week-nav"><button data-meal-week="-1" aria-label="Forrige madplansuge">←</button><div><strong>'+escape(calendarHeading(days[0],'week'))+'</strong><button data-meal-week="0" class="text-button">Denne uge</button></div><button data-meal-week="1" aria-label="Næste madplansuge">→</button></div>')+'<div class="meal-week">'+days.map(date=>{
 const meals=mealsOn(rows,date),day=parseDate(date)
 return '<section class="meal-day '+(date===today?'is-today':'')+'" data-meal-date="'+date+'"><header><span>'+escape(new Intl.DateTimeFormat('da-DK',{weekday:'long'}).format(day))+'</span><strong>'+escape(new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'short'}).format(day))+'</strong>'+(date===today?'<small>I dag</small>':'')+'</header><div class="meal-day-content">'+(meals.length?meals.map(meal=>{const recipe=recipes.find(r=>r.id===(meal.recipe_id||meal.data?.recipe_id));return '<article class="meal-card"><button data-plan-edit="'+meal.id+'">'+(recipe?.image_display_url&&!kiosk?'<img class="meal-recipe-thumbnail" src="'+escape(recipe.image_display_url)+'" alt="" width="48" height="48" loading="lazy" decoding="async">':'<span class="meal-symbol">'+icon('meals')+'</span>')+'<strong>'+escape(recipe?.title||meal.title)+'</strong><small>'+escape(meal.time||'Aftensmad')+'</small></button>'+((recipe?.recipe_ingredients?.length||meal.data?.recipe?.ingredients?.length||meal.note)&&!kiosk?'<button class="ingredient-button" data-meal-ingredients="'+meal.id+'">'+icon('shopping')+' Tilføj ingredienser</button>':'')+'</article>'}).join(''):'<p class="meal-empty">'+(compact?'Ikke planlagt':'Plads til noget godt')+'</p>')+(!kiosk?'<button class="meal-add" data-plan-new="meal" data-plan-date="'+date+'" aria-label="Planlæg mad '+date+'">'+icon('plus')+(meals.length?'Tilføj ret':'Planlæg')+'</button>':'')+'</div></section>'
 }).join('')+'</div></div>'
}
export function renderShopping(rows,draft={},compact=false,kiosk=false){
 if(kiosk)return renderKioskShopping(rows)
 const all=shoppingItems(rows),open=all.filter(row=>!row.done),done=all.filter(row=>row.done)
 const item=row=>'<li class="shopping-row '+(row.done?'is-bought':'')+'"><label class="shopping-check"><input type="checkbox" data-shopping-toggle="'+row.id+'" '+(row.done?'checked':'')+' aria-label="'+escape((row.done?'Markér som mangler: ':'Købt: ')+row.title)+'"><span aria-hidden="true"></span></label><button class="shopping-name" data-plan-edit="'+row.id+'"><strong>'+escape(row.title)+'</strong>'+(row.note?'<small>'+escape(row.note)+'</small>':'')+'</button></li>'
 return '<div class="shopping-view">'+(compact?'<p class="shopping-count">'+open.length+' '+(open.length===1?'vare':'varer')+' på listen</p>':'<div class="ux-view-intro"><div><p class="eyebrow">Familiens fælles liste</p><h3>Husk det hele</h3><p>'+open.length+' '+(open.length===1?'vare':'varer')+' tilbage · listen følger jer alle</p></div><span class="ux-round-icon">'+icon('shopping')+'</span></div>')+'<form id="shopping-add" class="shopping-add ux-inline-form"><label for="shopping-title" class="sr-only">Vare</label><input id="shopping-title" name="title" placeholder="Tilføj vare…" maxlength="160" value="'+escape(draft.title||'')+'" required autocomplete="off"><label for="shopping-note" class="sr-only">Mængde</label><input id="shopping-note" name="note" placeholder="Mængde" maxlength="120" value="'+escape(draft.note||'')+'"><button type="submit" aria-label="Tilføj vare">'+icon('plus')+'<span>Tilføj</span></button></form><p class="hint shopping-tip">Skriv en vare og tryk Enter. Du kan også tilføje ingredienser fra madplanen.</p><div class="shopping-groups">'+(open.length?SHOPPING_CATEGORIES.map(category=>{const items=open.filter(row=>(SHOPPING_CATEGORIES.includes(row.location)?row.location:'Andet')===category);return items.length?'<section class="shopping-group"><h4>'+escape(category)+' <span>'+items.length+'</span></h4><ul>'+items.map(item).join('')+'</ul></section>':''}).join(''):'<div class="ux-empty">'+icon('shopping')+'<h4>Listen er tom</h4><p>Tilføj den første vare, eller find inspiration i madplanen.</p><button data-go-route="meals">Gå til madplan '+icon('arrow')+'</button></div>')+'</div>'+(done.length?'<details class="shopping-completed"><summary>'+done.length+' købte varer</summary><ul>'+done.map(item).join('')+'</ul><button id="clear-shopping" class="text-button">Fjern købte varer fra listen</button></details>':'')+'</div>'
}

function renderKioskShopping(rows){
 const items=shoppingItems(rows).filter(row=>!row.done)
 return '<div class="kiosk-shopping"><p class="shopping-count">'+items.length+' '+(items.length===1?'vare':'varer')+' på familiens liste</p><div class="shopping-groups">'+(items.length?SHOPPING_CATEGORIES.map(category=>{const group=items.filter(row=>(SHOPPING_CATEGORIES.includes(row.location)?row.location:'Andet')===category);return group.length?'<section class="shopping-group"><h4>'+escape(category)+'</h4><ul>'+group.map(row=>'<li class="shopping-row"><span class="shopping-name"><strong>'+escape(row.title)+'</strong>'+(row.note?'<small>'+escape(row.note)+'</small>':'')+'</span></li>').join('')+'</ul></section>':''}).join(''):'<p class="empty-state">Listen er tom.</p>')+'</div></div>'
}
