import {t} from '../i18n/index.js'
export const privacySections=()=>[
 [(t("public_pages.family_subscription_and_wall_displays")),(t("public_pages.for_native_subscriptions_revenuecat_processes_the_account_uuid_product_app_store_and_purchase_status_apple_or_google_processes_payment_the_family_shares_access_through_a_server_verified_subscription_the_app_does_not_store_payment_cards_or_raw_receipts_in_family_data_a_paired_wall_display_uses_its_own_anonymous_sign_in_identity_with_limited_access_an_adult_can_remove_access_under_family_devices_pairing_codes_expire_and_are_stored_only_as_hashes_on_the_server"))],
 [(t("public_pages.recipes_and_photos")),(t("public_pages.the_family_shares_recipes_images_personal_ratings_and_links_to_meals_and_shopping_images_are_stored_privately_for_the_family_photo_scanning_sends_your_selected_photos_to_openai_to_read_the_recipe_only_when_you_press_analyse_review_the_result_before_saving_original_photos_are_used_as_covers_only_if_you_choose_library_text_and_ratings_are_cached_on_the_device_for_offline_viewing"))],
 [(t("public_pages.your_information")),(t("public_pages.familiekalender_stores_your_email_account_id_and_family_memberships_supabase_auth_handles_passwords_the_family_shares_events_notes_places_tasks_completion_status_recurrence_reward_history_meal_plans_ingredients_and_shopping_with_member_accounts"))],
 [(t("public_pages.children_and_family_profiles")),(t("public_pages.people_in_the_calendar_are_family_profiles_not_automatically_user_accounts_name_colour_optional_birth_year_avatar_and_task_settings_may_be_stored_the_adult_creating_or_inviting_people_to_the_family_must_have_permission_to_share_their_information_other_members_can_read_and_edit_shared_calendar_and_profile_data"))],
 [(t("public_pages.tasks_and_rewards")),(t("public_pages.rewards_include_monthly_allowance_calculations_and_payment_status_bonus_stars_with_a_history_the_family_reward_catalogue_goals_redemption_requests_adult_approvals_and_reasons_for_excused_chores_the_family_can_read_this_information_adults_manage_approvals_and_settings_the_app_does_not_transfer_money_history_is_preserved_when_a_person_is_archived_and_is_included_in_family_export_and_deletion"))],
 [(t("public_pages.images_and_calendar_feeds")),(t("public_pages.avatars_are_stored_in_a_private_supabase_storage_bucket_and_shown_with_expiring_links_older_avatars_may_use_external_image_links_google_aula_and_other_ics_links_are_stored_on_the_backend_and_fetched_by_a_supabase_edge_function_these_links_may_grant_access_to_private_calendars_only_owners_administrators_can_see_them_and_they_are_excluded_from_json_exports"))],
 [(t("public_pages.device_and_offline_storage")),(t("public_pages.this_device_stores_the_sign_in_session_calendar_people_rewards_meal_plans_shopping_and_pending_changes_locally_so_the_app_can_work_offline_only_share_the_device_with_people_allowed_to_see_the_family_signing_out_clears_local_family_data_and_pending_changes_appearance_and_wall_display_settings_including_a_salted_pin_hash_are_kept_for_the_next_sign_in_system_backups_may_have_a_different_lifetime"))],
 [(t("public_pages.native_devices_and_push")),(t("public_pages.android_ios_registers_a_random_installation_id_account_selected_family_platform_app_version_and_last_active_time_if_push_is_configured_and_you_grant_permission_an_apns_fcm_token_is_also_registered_there_is_no_reminder_engine_yet_the_app_does_not_collect_advertising_ids_precise_location_contacts_microphone_data_or_motion_data"))],
 [(t("public_pages.operations_and_providers")),(t("public_pages.supabase_processes_accounts_databases_files_and_server_functions_the_backend_project_is_in_eu_west_ireland_vercel_hosts_the_web_app_apple_google_handles_any_push_registrations_auth_email_requires_an_smtp_provider_still_to_be_decided_infrastructure_may_process_ip_addresses_and_operational_logs_the_app_has_no_advertising_or_analytics_tracking_sdk"))],
 [(t("public_pages.retention_export_and_deletion")),(t("public_pages.data_is_kept_while_the_family_uses_the_service_until_members_delete_it_or_the_family_is_deleted_inactive_families_are_not_automatically_deleted_under_account_you_can_export_the_selected_family_s_data_as_json_and_delete_your_account_family_data_is_kept_for_other_owners_your_author_references_are_anonymised_if_you_are_the_only_owner_each_family_must_be_explicitly_deleted_in_the_flow_child_profiles_in_a_retained_family_are_not_deleted_with_your_login"))],
 [(t("public_pages.cleanup_and_copies")),(t("public_pages.deleting_a_family_removes_its_calendar_meal_plans_shopping_people_feeds_memberships_rewards_and_avatar_files_account_profile_login_memberships_invitations_and_device_registrations_are_removed_if_network_cleanup_fails_an_internal_deletion_job_is_saved_and_completed_on_the_next_attempt_other_devices_offline_copies_can_only_be_cleared_when_they_reconnect_or_sign_out_provider_backups_and_security_logs_expire_according_to_agreed_retention_periods_the_exact_production_periods_must_be_decided_before_public_launch"))],
 [(t("public_pages.saved_exports")),(t("public_pages.on_native_devices_a_temporary_json_file_is_stored_in_the_app_s_private_cache_while_you_share_it_the_app_clears_it_on_sign_out_or_account_deletion_and_at_the_next_start_export_once_it_is_over_24_hours_old_you_must_delete_any_copies_you_save_or_share_yourself"))],
 [(t("public_pages.contact_and_responsibility")),(t("public_pages.before_public_launch_specify_the_data_controller_support_email_smtp_provider_legal_basis_and_agreed_retention_periods_requests_for_access_correction_or_deletion_must_be_possible_through_the_published_contact"))]
]
const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
export function renderPublicPage(route){
 const content=route==='/terms'?("<h1>"+t("public_pages.subscriptions_in_familiekalender")+"</h1><p>"+t("public_pages.one_subscription_gives_one_family_access_on_its_devices_the_app_store_shows_the_current_price_period_any_trial_and_renewal_before_you_confirm_the_purchase")+"</p><h2>"+t("public_pages.purchases_and_management")+"</h2><p>"+t("public_pages.purchase_restore_and_management_happen_in_the_ios_or_android_app_where_the_subscription_is_available_a_cancelled_subscription_retains_access_until_its_confirmed_expiry_date")+"</p><h2>"+t("public_pages.before_public_launch")+"</h2><p>"+t("public_pages.purchases_are_not_open_yet_final_terms_provider_details_and_support_contact_must_be_established_before_app_store_launch")+"</p>"):route==='/privacy'?("<h1>"+t("public_pages.privacy_in_familiekalender")+"</h1><p>"+t("public_pages.version_1_0_updated_9_october_2026")+"</p>")+privacySections().map(([title,text])=>'<h2>'+escape(title)+'</h2><p>'+escape(text)+'</p>').join(''):
 ("<h1>"+t("public_pages.help_with_familiekalender")+"</h1><h2>"+t("public_pages.sign_in_and_password")+"</h2><p>"+t("public_pages.choose_forgot_password_on_the_sign_in_screen_use_the_email_from_your_family_invitation_check_spam_if_confirmation_is_missing")+"</p><h2>"+t("public_pages.data_and_account")+"</h2><p>"+t("public_pages.export_the_selected_family_through_settings_account_account_deletion_can_be_started_here_on_the_web_or_in_the_app_sign_in_to_confirm_deletion")+"</p><p><a href=\"/delete-account\">"+t("public_pages.delete_my_account_and_associated_data")+"</a></p><h2>"+t("public_pages.offline_and_wall_display")+"</h2><p>"+t("public_pages.connect_the_device_to_send_pending_changes_do_not_sign_out_before_changes_are_synced_if_you_want_to_keep_them")+"</p><h2>"+t("public_pages.contact")+"</h2><p>"+t("public_pages.before_public_launch_the_support_email_has_not_been_finalised_yet")+"</p>")
 return '<main class="app-shell public-page"><article class="panel"><p class="eyebrow">Familiekalender</p>'+content+("<nav aria-label=\""+t("public_pages.help_pages")+"\"><a href=\"/\">"+t("public_pages.go_to_app")+"</a> · <a href=\"/privacy\">"+t("app.privacy")+"</a> · <a href=\"/support\">"+t("app.support")+"</a></nav></article></main>")
}
