import {t,labels,locale} from '../i18n/index.js'
import {dateIso} from './calendar-dates.js'
export const RATINGS=labels({love:'recipe.love_it',like:'recipe.like_it',okay:'recipe.okay',dislike:'recipe.no_thanks'})
export const recipeId=row=>row?.recipe_id||row?.data?.recipe_id||null
export function canonicalRecipeUrl(value){try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return '';u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);u.searchParams.sort();u.pathname=u.pathname.replace(/\/$/,'')||'/';return u.href}catch{return ''}}
export function recipeUsage(id,meals,today=dateIso(new Date())){const dates=meals.filter(m=>m.type==='Madplan'&&recipeId(m)===id&&m.date<=today).map(m=>m.date).sort();return {last:dates.at(-1)||null,count:dates.length}}
export function ratingSummary(ratings=[],people=[]){const eligible=new Set(people.filter(p=>p.active!==false&&p.is_active!==false&&p.archived!==true).map(p=>p.id)),votes=ratings.filter(r=>eligible.has(r.person_id)),positive=votes.filter(r=>['love','like'].includes(r.rating)).length;return {positive,total:eligible.size,rated:votes.length,favorite:eligible.size>0&&positive>eligible.size/2,label:!votes.length?(t("recipe.no_ratings_yet")):positive+'/'+eligible.size+(" "+t("recipe.would_like_it_again"))}}
export function filterRecipes(recipes,{query='',filter='all',people=[],meals=[]}={}){let result=recipes.filter(r=>!r.archived_at&&r.title.toLocaleLowerCase('da').includes(query.toLocaleLowerCase('da')));if(filter==='favorites')result=result.filter(r=>ratingSummary(r.recipe_ratings,people).favorite);if(filter==='quick')result=result.filter(r=>r.total_minutes>0&&r.total_minutes<=30);return result.sort((a,b)=>filter==='unused'?(recipeUsage(a.id,meals).last||'').localeCompare(recipeUsage(b.id,meals).last||'')||a.title.localeCompare(b.title,locale()):filter==='recent'?(recipeUsage(b.id,meals).last||'').localeCompare(recipeUsage(a.id,meals).last||''):a.title.localeCompare(b.title,locale()))}
export function recipeDraft(values){const title=String(values.title||'').trim();if(!title||title.length>160)throw Error((t("recipe.enter_a_title_with_no_more_than_160_characters")));const split=v=>(Array.isArray(v)?v:String(v||'').split(/\r?\n/)).map(x=>typeof x==='string'?x.trim():x.raw_text||x.text||'').filter(Boolean);const ingredients=split(values.ingredients??values.recipe_ingredients),instructions=split(values.instructions??values.recipe_instructions);if(ingredients.length>100||ingredients.some(x=>x.length>1000)||instructions.length>100||instructions.join('\n').length>30000)throw Error((t("recipe.the_recipe_is_too_long_use_no_more_than_100_ingredients_and_100_steps")));const n=v=>v===''||v==null?null:Number(v);const result={title,description:String(values.description||'').trim().slice(0,4000),source_type:values.source_type||'manual',source_url:canonicalRecipeUrl(values.source_url)||null,source_name:String(values.source_name||'').slice(0,200)||null,original_image_url:canonicalRecipeUrl(values.original_image_url)||null,image_path:values.image_path||null,ingredients:ingredients.map((raw_text,i)=>{const source=(values.ingredient_details||values.recipe_ingredients||values.ingredients)?.[i];return source&&typeof source==='object'&&source.raw_text===raw_text?{raw_text,ingredient_name:source.ingredient_name??null,quantity:source.quantity??null,unit:source.unit??null,note:source.note??null}:raw_text}),instructions};for(const k of ['servings','prep_minutes','cook_minutes','total_minutes']){result[k]=n(values[k]);if(result[k]!==null&&(!Number.isFinite(result[k])||result[k]<=0||result[k]>10000))throw Error((t("recipe.servings_and_times_must_be_positive_numbers")))}return result}
export function fromPreview(r,source_type='url'){return {...r,source_type,source_url:r.url||null,source_name:r.site||null,original_image_url:r.image||null,ingredients:r.ingredients||[],instructions:r.instructions||[]}}
