import {escape as e,icon} from './product-ui.js'
import {RATINGS,recipeId,recipeUsage,ratingSummary,filterRecipes,canonicalRecipeUrl,fromPreview} from './recipe-model.js'
import {preparePhoto,blobImage,imageBlob} from './recipe-service.js'
import {dateIso,parseDate} from './calendar-dates.js'
const sorted=(rows=[])=>[...rows].sort((a,b)=>a.position-b.position)
const dateLabel=date=>date?new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'long'}).format(parseDate(date)):'Ikke lavet endnu'
const cover=(r,cls='')=>r.image_display_url?'<img class="recipe-cover '+cls+'" src="'+e(r.image_display_url)+'" alt="'+e(r.title)+'" loading="lazy" decoding="async">':'<div class="recipe-placeholder '+cls+'">'+icon('meals')+'<span>Fra familiens køkken</span></div>'
export class RecipeUI{
 constructor(options){Object.assign(this,options);this.query='';this.filter='all';this.urls=[];this.busy=false;this.detailId=null;this.root.addEventListener('dismiss-dialog',()=>this.close())}
 get opened(){return !!this.root.firstChild}
 context(){return this.getContext()}
 url(blob){const u=URL.createObjectURL(blob);this.urls.push(u);return u}
 close(force=false){if(this.busy&&!force)return;this.root.innerHTML='';this.detailId=null;this.urls.forEach(u=>URL.revokeObjectURL(u));this.urls=[];this.busy=false;this.generation=(this.generation||0)+1}
 show(title,body,{wide=false}={}){
  this.detailId=null;this.generation=(this.generation||0)+1
  this.root.innerHTML='<div class="modal-backdrop recipe-backdrop" role="dialog" aria-modal="true" aria-labelledby="recipe-dialog-title"><section class="calendar-modal recipe-modal '+(wide?'recipe-modal-wide':'')+'"><header class="modal-header"><div><p class="eyebrow">Familiens køkken</p><h2 id="recipe-dialog-title">'+e(title)+'</h2></div><button type="button" data-recipe-close aria-label="Luk">×</button></header>'+body+'<p class="recipe-error message" role="alert"></p></section></div>'
  this.root.querySelector('[data-recipe-close]').onclick=()=>this.close();this.root.querySelector('.modal-backdrop').onclick=ev=>{if(ev.target===ev.currentTarget)this.close()}
 }
 async run(button,fn){if(this.busy)return;const context=this.context().key,generation=this.generation;this.busy=true;if(button)button.disabled=true;const err=this.root.querySelector('.recipe-error');if(err)err.textContent=''
  try{await fn(()=>context===this.context().key&&generation===this.generation)}catch(error){if(context===this.context().key&&generation===this.generation&&err)err.textContent=error.message||'Handlingen kunne ikke gennemføres.'}finally{if(context===this.context().key){this.busy=false;if(button?.isConnected)button.disabled=false}}
 }
 actions(){return '<div class="recipe-actions"><button data-recipe-url>'+icon('arrow')+' Hent fra URL</button><button data-recipe-scan><span aria-hidden="true">📷</span> Scan opskrift</button><button data-recipe-new>'+icon('plus')+' Ny opskrift</button></div>'}
 cards(list){const c=this.context();return list.map(r=>{const summary=ratingSummary(r.recipe_ratings,c.people),usage=recipeUsage(r.id,c.items);return '<article class="library-card"><button class="recipe-card-open" data-recipe-open="'+r.id+'">'+(r.image_display_url?cover(r):'')+'<div class="recipe-card-body"><h3>'+e(r.title)+'</h3><div class="recipe-card-meta">'+(r.total_minutes?'<span>'+e(r.total_minutes)+' min</span>':'')+(r.servings?'<span>'+e(r.servings)+' portioner</span>':'')+'</div>'+(summary.favorite?'<span class="recipe-favorite">♥ Familiefavorit</span>':'<small>'+e(summary.label)+'</small>')+'<small class="recipe-last">'+(usage.last?'Sidst lavet '+dateLabel(usage.last):'Prøv den snart')+'</small></div></button><button class="recipe-card-plan" data-recipe-plan="'+r.id+'">Planlæg '+icon('plus')+'</button></article>'}).join('')}
 renderLibrary({compact=false}={}){const c=this.context();if(c.mode==='kiosk')return '';const list=filterRecipes(c.recipes,{query:compact?'':this.query,filter:compact?'all':this.filter,people:c.people,meals:c.items})
  return '<section class="recipe-library '+(compact?'recipe-library-preview':'')+'"><div class="recipe-section-title"><div><p class="eyebrow">Gode retter, igen og igen</p><h3>Familiens opskrifter</h3></div>'+(compact?'<button data-food-tab="recipes" class="text-button">Se alle →</button>':'')+'</div>'+this.actions()+(!navigator.onLine?'<p class="hint">Offline · senest gemte opskrifter og vurderinger. Ændringer og import kræver forbindelse.</p>':'')+(c.error?'<p class="message" role="status">'+e(c.error)+'</p>':'')+(!compact?'<label class="recipe-search"><span class="sr-only">Søg opskrifter</span><input id="recipe-search" type="search" placeholder="Find en ret…" value="'+e(this.query)+'"></label><div class="recipe-filters" aria-label="Opskriftsfilter">'+[['all','Alle'],['favorites','Familiefavoritter'],['unused','Ikke lavet længe'],['quick','Hurtige retter']].map(([id,label])=>'<button data-recipe-filter="'+id+'" aria-pressed="'+(this.filter===id)+'">'+label+'</button>').join('')+'</div>':'')+'<div class="recipe-grid">'+this.cards(compact?list.slice(0,6):list)+'</div>'+(!list.length?'<div class="recipe-empty"><h4>'+(c.recipes.some(r=>!r.archived_at)?'Ingen retter matcher':'Jeres gode retter hører hjemme her')+'</h4><p>'+(c.recipes.length?'Prøv et andet filter eller søgeord.':'Gem en favorit, hent fra et link eller scan en side fra kogebogen.')+'</p></div>':'')+'</section>'
 }
 bind(container=document){
  // A missing/expired cover falls back to the same compact text card as a recipe without an image.
  container.querySelectorAll('.library-card .recipe-cover,.meal-recipe-thumbnail').forEach(img=>{img.onerror=()=>img.remove();if(img.complete&&!img.naturalWidth)img.remove()})
  container.querySelectorAll('[data-recipe-new]').forEach(b=>b.onclick=()=>this.edit())
  container.querySelectorAll('[data-recipe-url]').forEach(b=>b.onclick=()=>this.urlImport())
  container.querySelectorAll('[data-recipe-scan]').forEach(b=>b.onclick=()=>this.scan())
  container.querySelectorAll('[data-recipe-open]').forEach(b=>b.onclick=()=>this.detail(b.dataset.recipeOpen))
  container.querySelectorAll('[data-recipe-plan]').forEach(b=>b.onclick=()=>this.plan(b.dataset.recipePlan))
  container.querySelectorAll('[data-recipe-filter]').forEach(b=>b.onclick=()=>{this.filter=b.dataset.recipeFilter;this.onChange()})
  const search=container.querySelector('#recipe-search');if(search)search.oninput=()=>{const cursor=search.selectionStart;this.query=search.value;this.onChange();const next=document.querySelector('#recipe-search');next?.focus({preventScroll:true});try{next?.setSelectionRange(cursor,cursor)}catch{}}
 }
 detail(id,{meal=null,readonly=this.context().mode==='kiosk'}={}){
  const c=this.context(),r=c.recipes.find(x=>x.id===id);if(!r)return
  const summary=ratingSummary(r.recipe_ratings,c.people),usage=recipeUsage(r.id,c.items)
  const ingredients=sorted(r.recipe_ingredients),instructions=sorted(r.recipe_instructions)
  this.show(r.title,'<div class="recipe-detail-hero">'+cover(r)+(r.archived_at?'<span class="recipe-favorite">Arkiveret · stadig gemt til madplanen</span>':summary.favorite?'<span class="recipe-favorite">♥ Familiefavorit</span>':'')+'</div><p class="recipe-description">'+e(r.description||'')+'</p><div class="recipe-detail-meta">'+[r.total_minutes?r.total_minutes+' min':'',r.servings?r.servings+' portioner':'',usage.last?'Sidst lavet: '+dateLabel(usage.last):'Ikke lavet endnu',usage.count?'Lavet '+usage.count+' gange':''].filter(Boolean).map(x=>'<span>'+e(x)+'</span>').join('')+'</div>'+(meal?'<section class="recipe-meal-context"><strong>'+dateLabel(meal.date)+'</strong><span>'+(meal.data?.servings_override?e(meal.data.servings_override)+' portioner':'')+'</span><p>'+e(meal.note||'')+'</p>'+(!readonly?'<button data-edit-meal>Rediger dagens måltid</button>':'')+'</section>':'')+(!readonly?'<div class="recipe-detail-actions">'+(!r.archived_at?'<button data-detail-plan>Planlæg denne ret</button>':'')+'<button data-detail-shop>Tilføj ingredienser til indkøb</button></div>':'')+'<section class="recipe-family"><h3>Hvad synes familien?</h3>'+c.people.filter(p=>p.active!==false&&p.is_active!==false&&p.archived!==true).map(p=>{const rating=r.recipe_ratings?.find(x=>x.person_id===p.id)?.rating||'';return '<div class="recipe-person">'+this.avatar(p)+'<strong>'+e(p.name)+'</strong>'+(readonly?'<span>'+e(RATINGS[rating]||'Ikke vurderet')+'</span>':'<label><span class="sr-only">Vurdering for '+e(p.name)+'</span><select data-recipe-rating="'+p.id+'"><option value="">Ikke vurderet</option>'+Object.entries(RATINGS).map(([v,l])=>'<option value="'+v+'" '+(v===rating?'selected':'')+'>'+l+'</option>').join('')+'</select></label>')+'</div>'}).join('')+'</section><div class="recipe-detail-columns"><section><h3>Ingredienser</h3>'+(r.servings?'<p class="hint">Original opskrift til '+e(r.servings)+' portioner. Mængder skaleres ikke automatisk.</p>':'')+'<ul class="recipe-ingredients">'+ingredients.map(i=>'<li><label><input type="checkbox"> <span>'+e(i.raw_text)+'</span></label></li>').join('')+'</ul>'+(!ingredients.length?'<p class="hint">Ingen ingredienser gemt endnu.</p>':'')+'</section><section><h3>Fremgangsmåde</h3><ol class="recipe-steps">'+instructions.map(i=>'<li>'+e(i.text)+'</li>').join('')+'</ol></section></div>'+(canonicalRecipeUrl(r.source_url)?'<a class="recipe-source" href="'+e(canonicalRecipeUrl(r.source_url))+'" target="_blank" rel="noopener noreferrer">Åbn original opskrift · '+e(r.source_name||new URL(r.source_url).hostname)+' ↗</a>':'')+(!readonly?'<div class="recipe-detail-tools"><button data-detail-edit>Rediger opskrift</button>'+(!r.archived_at?'<button data-detail-archive class="text-button">Arkivér</button>':'')+'</div>':''),{wide:true})
  this.detailId=id;this.detailOptions={meal,readonly}
  this.root.querySelector('[data-edit-meal]')?.addEventListener('click',()=>{this.close();this.editMeal(meal)})
  this.root.querySelector('[data-detail-plan]')?.addEventListener('click',()=>this.plan(id))
  this.root.querySelector('[data-detail-shop]')?.addEventListener('click',()=>this.shopping(id,meal))
  this.root.querySelector('[data-detail-edit]')?.addEventListener('click',()=>this.edit(r))
  this.root.querySelector('[data-detail-archive]')?.addEventListener('click',()=>this.archive(r))
  this.root.querySelectorAll('[data-recipe-rating]').forEach(select=>select.onchange=()=>this.run(select,async current=>{await this.service.rate(r,select.dataset.recipeRating,select.value);await this.refresh();if(current()){this.busy=false;this.detail(id,{meal,readonly})}}))
 }
 async changed(){await this.refresh();this.onChange()}
 archive(r){this.show('Arkivér '+r.title,'<p>Retten skjules fra biblioteket. Planlagte og historiske måltider beholder opskriften og billedet.</p><button id="recipe-archive-confirm">Arkivér opskrift</button>');const b=this.root.querySelector('button#recipe-archive-confirm');b.onclick=()=>this.run(b,async current=>{await this.service.archive(r);await this.changed();if(current())this.close(true)})}
 plan(id,date=dateIso(new Date())){
  const r=this.context().recipes.find(x=>x.id===id&&!x.archived_at);if(!r)return
  this.show('Planlæg '+r.title,'<form id="recipe-plan-form" class="stack-form"><label for="recipe-plan-date">Dato</label><input id="recipe-plan-date" type="date" name="date" value="'+e(date)+'" required><label for="recipe-plan-servings">Portioner · valgfrit</label><input id="recipe-plan-servings" name="servings_override" type="number" min="1" max="10000" step="0.5" value="'+e(r.servings||'')+'"><label for="recipe-plan-note">Note til dette måltid</label><textarea id="recipe-plan-note" name="note" rows="3" maxlength="4000" placeholder="Fx lav dobbelt portion"></textarea><p class="hint">Dato, note og portionsvalg gælder kun dette måltid. Opskriften i biblioteket bevares.</p><button type="submit">Gem i madplan</button></form>')
  const form=this.root.querySelector('form');form.onsubmit=ev=>{ev.preventDefault();this.run(form.querySelector('[type=submit]'),async current=>{const v=Object.fromEntries(new FormData(form));await this.planRecipe(r,v);if(current()){this.close(true);this.notice('Planlagt til '+dateLabel(v.date)+'.')}})}
 }
 choose(date=dateIso(new Date())){
  const c=this.context();this.show('Hvad skal vi spise?','<div class="recipe-filters">'+[['recent','Senest brugte'],['favorites','Familiefavoritter'],['all','Alle opskrifter']].map(([id,label])=>'<button data-picker-filter="'+id+'" aria-pressed="'+(id==='recent')+'">'+label+'</button>').join('')+'</div><div class="recipe-picker"></div><button data-manual-meal>Planlæg uden opskrift</button>')
  const render=filter=>{const list=filterRecipes(c.recipes,{filter,people:c.people,meals:c.items});this.root.querySelector('.recipe-picker').innerHTML=list.map(r=>'<button data-pick="'+r.id+'">'+cover(r)+'<span><strong>'+e(r.title)+'</strong><small>'+e(r.total_minutes?r.total_minutes+' min':'Fra biblioteket')+'</small></span>'+icon('plus')+'</button>').join('')||'<p>Ingen opskrifter her endnu. Du kan stadig planlægge en ret.</p>';this.root.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>this.plan(b.dataset.pick,date))}
  this.root.querySelectorAll('[data-picker-filter]').forEach(b=>b.onclick=()=>{this.root.querySelectorAll('[data-picker-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render(b.dataset.pickerFilter)})
  this.root.querySelector('[data-manual-meal]').onclick=()=>{this.close();this.newMeal(date)};render('recent')
 }
 shopping(id,meal=null){
  const r=this.context().recipes.find(x=>x.id===id);if(!r)return;const ingredients=sorted(r.recipe_ingredients),actionId=crypto.randomUUID()
  this.show('Til indkøb fra '+r.title,'<form id="recipe-shopping-form"><p>Fjern det, I allerede har. Mængderne bevares som i opskriften.</p><ul class="recipe-ingredients">'+ingredients.map((i,n)=>'<li><label><input name="ingredient" type="checkbox" value="'+n+'" checked><span>'+e(i.raw_text)+'</span></label></li>').join('')+'</ul><button type="submit" '+(!ingredients.length?'disabled':'')+'>Tilføj valgte ingredienser</button></form>')
  const form=this.root.querySelector('form');form.onsubmit=ev=>{ev.preventDefault();this.run(form.querySelector('[type=submit]'),async current=>{const chosen=new FormData(form).getAll('ingredient').map(i=>ingredients[Number(i)]);if(!chosen.length)throw Error('Vælg mindst én ingrediens.');await this.addShopping(r,chosen,{meal,actionId});if(current()){this.close(true);this.notice('Ingredienserne er tilføjet til indkøb.')}})}
 }
 edit(existing=null,draft=null,{image=null,photo=false}={}){
  const r=draft||existing||{},id=existing?.id||crypto.randomUUID();let selected=image,removed=false
  const initial=r.image_display_url||(image?this.url(image):'')
  const lines=(value,key)=>Array.isArray(value)?value.map(v=>typeof v==='string'?v:v[key]).join('\n'):''
  this.show(existing?'Rediger opskrift':'Gem en god ret','<form id="recipe-editor" class="stack-form">'+(draft?'<p class="recipe-review-note">'+(r.incomplete?'Vi kunne ikke læse hele opskriften sikkert. Ret de manglende felter før du gemmer.':'Læs opskriften igennem og ret den, før du gemmer i biblioteket.')+'</p>':'')+'<div class="recipe-editor-image"><div id="recipe-image-preview">'+(initial?'<img src="'+e(initial)+'" alt="Valgt cover">':'<span>'+icon('meals')+' Tilføj et billede af retten</span>')+'</div><label class="recipe-file-button">Vælg billede<input id="recipe-image-file" type="file" accept="image/jpeg,image/png,image/webp"></label><button type="button" id="recipe-image-remove">Fjern billede</button></div>'+(photo&&image?'<label class="recipe-cover-consent"><input id="recipe-cover-consent" type="checkbox"> Brug det valgte originalfoto som cover</label>':'')+'<label for="recipe-title">Titel</label><input id="recipe-title" name="title" required maxlength="160" value="'+e(r.title||'')+'"><label for="recipe-description">Beskrivelse / note</label><textarea id="recipe-description" name="description" rows="2" maxlength="4000">'+e(r.description||'')+'</textarea><div class="recipe-numbers">'+[['servings','Portioner'],['total_minutes','Tid i alt · min'],['prep_minutes','Forberedelse · min'],['cook_minutes','Tilberedning · min']].map(([k,l])=>'<label>'+l+'<input name="'+k+'" type="number" min="0.5" step="0.5" max="10000" value="'+e(r[k]||'')+'"></label>').join('')+'</div><label for="recipe-ingredients">Ingredienser · én pr. linje</label><textarea id="recipe-ingredients" name="ingredients" rows="6" placeholder="500 g pasta&#10;2 dåser hakkede tomater">'+e(lines(r.ingredients||sorted(r.recipe_ingredients),'raw_text'))+'</textarea><label for="recipe-instructions">Fremgangsmåde · ét trin pr. linje</label><textarea id="recipe-instructions" name="instructions" rows="6">'+e(lines(r.instructions||sorted(r.recipe_instructions),'text'))+'</textarea>'+(r.source_url?'<p class="hint">Kilde: '+e(r.source_name||r.source_url)+'</p>':'')+'<button type="submit">Gem i bibliotek</button></form>',{wide:true})
  const form=this.root.querySelector('form'),preview=this.root.querySelector('#recipe-image-preview')
  this.root.querySelector('#recipe-image-file').onchange=async ev=>{const f=ev.target.files[0];if(!f)return;await this.run(null,async current=>{const blob=await preparePhoto(f);if(current()){selected=blob;removed=false;preview.innerHTML='<img src="'+e(this.url(blob))+'" alt="Valgt cover">';this.root.querySelector('.recipe-cover-consent')?.remove()}})}
  this.root.querySelector('#recipe-image-remove').onclick=()=>{selected=null;removed=true;preview.innerHTML='<span>Uden billede</span>';this.root.querySelector('.recipe-cover-consent')?.remove()}
  form.onsubmit=ev=>{ev.preventDefault();this.run(form.querySelector('[type=submit]'),async current=>{const consent=this.root.querySelector('#recipe-cover-consent');const values={...r,...Object.fromEntries(new FormData(form))};const saved=await this.service.save(values,{existing,id,image:consent&&!consent.checked?null:selected,removeImage:removed});await this.changed();if(current()){this.busy=false;this.detail(saved);this.notice('Opskriften er gemt til familien.')}})}
 }
 urlImport(){
  this.show('Hent opskrift fra URL','<form id="recipe-url-form" class="stack-form"><label for="library-recipe-url">Link til opskriften</label><input id="library-recipe-url" type="url" required placeholder="https://…" maxlength="4096"><p class="hint">Vi henter tekst og billede. Du retter opskriften, før den gemmes.</p><button type="submit">Hent opskrift</button></form>')
  const form=this.root.querySelector('form'),b=form.querySelector('button');form.onsubmit=ev=>{ev.preventDefault();const url=form.querySelector('input').value;let allowDuplicate=false;const fetch=()=>this.run(b,async current=>{b.textContent='Henter opskrift…';try{const {recipe}=await this.service.import({url});if(!current())return;const found=this.duplicate(recipe.url);const next=()=>{this.busy=false;this.edit(null,fromPreview(recipe),{image:recipe.image_copy?imageBlob(recipe.image_copy):null})};if(found&&!allowDuplicate)this.duplicateDialog(found,()=>{allowDuplicate=true;next()});else next()}finally{if(b.isConnected)b.textContent='Hent opskrift'}});const found=this.duplicate(url);if(found)this.duplicateDialog(found,()=>{allowDuplicate=true;fetch()});else fetch()}
 }
 duplicate(url){const canonical=canonicalRecipeUrl(url);return canonical&&this.context().recipes.find(r=>canonicalRecipeUrl(r.source_url)===canonical)}
 duplicateDialog(recipe,next){this.busy=false;this.show('Opskriften findes allerede','<p>Denne opskrift findes allerede i familiens bibliotek'+(recipe.archived_at?' som arkiveret':'')+'.</p><div class="recipe-detail-actions"><button data-duplicate-open>Åbn eksisterende</button><button data-duplicate-anyway>Importér alligevel</button></div>');this.root.querySelector('[data-duplicate-open]').onclick=()=>this.detail(recipe.id);this.root.querySelector('[data-duplicate-anyway]').onclick=next}
 scan(){
  const files=[];this.show('Scan en opskrift','<p>Tag tydelige fotos af alle sider. Op til 4 billeder, i læserækkefølge.</p><div class="scan-entry"><label class="recipe-file-button">📷 Tag foto<input id="scan-camera" type="file" accept="image/*" capture="environment"></label><label class="recipe-file-button">Vælg billeder<input id="scan-files" type="file" accept="image/jpeg,image/png,image/webp" multiple></label></div><p id="scan-upload-status" role="status"></p><div class="scan-pages"></div><p class="hint">Ved analyse sendes billederne til familiens opskriftslæser (OpenAI). Fotos gemmes kun som cover, hvis du selv vælger det. Kontrollér altid resultatet.</p><button id="scan-analyse" disabled>Analyser opskrift</button><button id="scan-manual" class="text-button">Skriv opskriften manuelt</button>')
  const render=()=>{this.root.querySelector('.scan-pages').innerHTML=files.map((f,i)=>'<article class="scan-page"><img src="'+e(f.url)+'" alt="Side '+(i+1)+'"><span>Side '+(i+1)+'</span><div><button data-scan-up="'+i+'" '+(i===0?'disabled':'')+' aria-label="Flyt side '+(i+1)+' op">↑</button><button data-scan-remove="'+i+'" aria-label="Fjern side '+(i+1)+'">×</button></div></article>').join('');this.root.querySelector('#scan-analyse').disabled=!files.length;this.root.querySelectorAll('[data-scan-remove]').forEach(b=>b.onclick=()=>{files.splice(Number(b.dataset.scanRemove),1);render()});this.root.querySelectorAll('[data-scan-up]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.scanUp);[files[n-1],files[n]]=[files[n],files[n-1]];render()})}
  this.root.querySelectorAll('input[type=file]').forEach(input=>input.onchange=()=>this.run(null,async current=>{const selected=[...input.files];this.root.querySelector('#scan-upload-status').textContent='Klargør billeder…';if(selected.length+files.length>4)throw Error('Vælg højst 4 sider.');for(const file of selected){const blob=await preparePhoto(file);if(!current())return;files.push({blob,url:this.url(blob)})}if(current()){input.value='';render();this.root.querySelector('#scan-upload-status').textContent='Billederne er klar til analyse.'}}))
  this.root.querySelector('#scan-manual').onclick=()=>this.edit(null,{source_type:'photo'},{image:files[0]?.blob||null,photo:true})
  const b=this.root.querySelector('#scan-analyse');b.onclick=()=>this.run(b,async current=>{b.textContent='Læser siderne…';try{const images=await Promise.all(files.map(f=>blobImage(f.blob))),{recipe}=await this.service.import({action:'scan',images});if(current()){this.busy=false;this.edit(null,{...recipe,source_type:'photo'},{image:files[0]?.blob||null,photo:true})}}finally{if(b.isConnected)b.textContent='Analyser opskrift'}})
 }
}
