import {emptyRewards,enabled,rewardConfig,rewardRule,managedTask,occurrenceState,isApproved,starBalance,rewardGoal,taskPeople,actionPayload,currency,parseCurrency,monthProgress,rewardToday} from './rewards-model.js'
import {materialize} from './calendar-semantics.js'
import {itemMatchesPerson} from './people.js'
import {weeklyProgress} from './task-rewards.js'
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const attr=o=>e(JSON.stringify(o)), monthName=day=>new Intl.DateTimeFormat('da-DK',{month:'long',year:'numeric'}).format(new Date(day+'T12:00:00'))
const statusText={open:'Klar til at gå i gang',pending:'Afventer godkendelse',approved:'Godkendt',completed:'Udført',rejected:'Prøv igen',excused:'Fritaget',cancelled:'Aflyst'}
const count=(kind,pid,n,format=n=>String(n))=>`<span><span aria-hidden="true" data-reward-count="${kind}:${pid}">${e(format(n))}</span><span class="sr-only">${e(format(n))}</span></span>`
const progress=(value,max,label,key)=>`<progress ${key?`data-reward-progress="${key}"`:""} value="${Math.max(0,value)}" max="${Math.max(1,max)}" aria-label="${e(label)}"></progress>`
export class RewardsUI {
 constructor({getContext,onAction,onSelect,onToggle,onEdit,avatar}){
  Object.assign(this,{getContext,onAction,onSelect,onToggle,onEdit,avatar});this.root=document.createElement('div');document.body.append(this.root);this.busy=false;this.dialog=null;this.historyOpen=new Set()
  this.root.addEventListener('dismiss-dialog',()=>this.close())
 }
 get c(){const c=this.getContext();return {...c,state:c.state||emptyRewards()}}
 get adult(){return ['adult','admin','owner'].includes(this.c.role)&&this.c.mode!=='kiosk'}
 close(force=false){if(this.busy&&!force)return;this.root.innerHTML='';this.dialog=null;this.busy=false}
 get opened(){return !!this.dialog}
 button(action,payload,label,disabled=false){return `<button type="button" data-reward-action="${action}" data-reward-payload="${attr(payload)}" ${disabled?'disabled':''}>${label}</button>`}
 people(){return this.c.people.filter(p=>p.is_active!==false&&enabled(p))}
 summary(kiosk=false){const c=this.c;return `<div class="reward-people ${kiosk?'reward-people-kiosk':''}" aria-label="Familiens opgaver og belønninger">${this.people().map(p=>{const m=monthProgress(c.items,c.people,c.state,p.id),cfg=rewardConfig(c.state,p.id),w=weeklyProgress(c.items,[p],rewardToday(),rewardToday(),c.state)[0];return `<button class="reward-person-summary" data-reward-person-panel="${p.id}" ${kiosk?'data-child-day':'data-reward-select'}="${p.id}">${this.avatar(p,'reward-avatar')}<span><strong>${e(p.name)}</strong>${cfg.allowance_enabled?`<small>${count('allowance',p.id,m.earned_minor,currency)} / ${currency(m.allowance_minor)}</small>`:`<small>${w?.count||0} ${kiosk?'klaret':'klaret denne uge'}</small>`}</span>${cfg.star_rewards_enabled?`<b class="reward-stars">⭐ ${count('stars',p.id,starBalance(c.state,p.id))}</b>`:''}</button>`}).join('')}</div>`}
 dashboard(pid,{child=false}={}){
  const c=this.c,p=c.people.find(p=>p.id===pid);if(!p)return ''
  const cfg=rewardConfig(c.state,pid),m=monthProgress(c.items,c.people,c.state,pid),balance=starBalance(c.state,pid),goal=rewardGoal(c.state,pid),w=weeklyProgress(c.items,c.people,rewardToday(),rewardToday(),c.state).find(w=>w.personId===pid)
  return `<section class="reward-dashboard" data-reward-person-panel="${pid}"><header class="reward-person-heading">${this.avatar(p,'reward-avatar')}<div><p class="eyebrow">${child?'Min dag':'Opgaver & belønninger'}</p><h3>${e(p.name)}</h3></div>${!child?`<button data-child-day="${pid}">Min dag ↗</button>`:''}</header><div class="reward-metrics">${cfg.allowance_enabled?`<article class="reward-month"><p class="eyebrow">${monthName(rewardToday())}</p><strong>${count('allowance',pid,m.earned_minor,currency)} <small>/ ${currency(m.allowance_minor)}</small></strong>${progress(m.completion_percent,100,'Månedens opgaver','month:'+pid)}<p>${count('percent',pid,m.completion_percent,n=>new Intl.NumberFormat('da-DK',{maximumFractionDigits:1}).format(n)+' %')} · ${m.completed_total} / ${m.eligible_total} opgaver${m.excused_total?` · ${m.excused_total} fritaget`:''}</p>${c.state.occurrences.some(o=>o.person_id===pid&&o.local_pending&&o.reward_mode==='allowance')?'<small class="reward-awaiting">Afventer synkronisering · beløbet er bekræftet</small>':''}</article>`:''}${cfg.star_rewards_enabled?`<article class="reward-star-balance"><p class="eyebrow">Bonusstjerner</p><strong>⭐ ${count('stars',pid,balance)}</strong><p>Til familiens belønninger</p></article>`:''}</div>${goal&&cfg.star_rewards_enabled?`<article class="reward-goal"><div><span aria-hidden="true">${e(goal.emoji)}</span><span><small>Mit mål</small><strong>${e(goal.title)}</strong></span><b>${count('goal',pid,balance)} / ${goal.star_cost} ⭐</b></div>${progress(balance,goal.star_cost,'Stjerner til mit mål','goal:'+pid)}<p>${balance>=goal.star_cost?`✓ Du har nok ⭐ til ${e(goal.title)}!`:`Mangler ${goal.star_cost-balance} ⭐`}</p></article>`:''}<p class="reward-week-count">${w?.count||0} opgaver klaret denne uge</p></section>`
 }
 taskCard(item,pid='Alle',{child=false}={}){
  const c=this.c,rule=rewardRule(item),people=taskPeople(item,c.people,c.state).filter(p=>pid==='Alle'||p.id===pid),pool=rule.pool,claimed=c.state.occurrences.some(s=>s.origin_id===(item.data?.rewardOriginId||item.baseId||item.id)&&s.occurrence_date===(item.occurrenceDate||item.data?.originalDate||item.date)&&s.claimed)
  if(!managedTask(item))return `<article class="reward-task" data-reward-task="${e(item.id)}"><div><strong>${e(item.title)}</strong><small>${e(item.time||'Når det passer')}</small></div><button data-reward-legacy="${e(item.id)}" data-done="${!item.done}" aria-label="${item.done?'Genåbn':'Udfør'} ${e(item.title)}">${item.done?'✓ Udført':'Udfør'}</button></article>`
  return `<article class="reward-task ${pool?'reward-bonus-task':''}" data-reward-task="${e(item.id)}"><div class="reward-task-title"><span aria-hidden="true">${rule.mode==='stars'?'✦':'✓'}</span><div>${child?`<strong>${e(item.title)}</strong>`:`<button class="reward-title-button" data-reward-edit="${e(item.id)}">${e(item.title)}</button>`}<small>${rule.mode==='stars'?`+${rule.stars} ⭐`:rule.mode==='allowance'?'Tæller til lommepenge':'Opgave'}${rule.approval?' · Voksen godkender':''}</small></div></div><div class="reward-task-people">${people.map(p=>{const s=occurrenceState(c.state,item,p.id),status=s?.status||'open',payload=actionPayload(item,p.id),done=isApproved(s);return `<div class="reward-task-person"><span>${e(p.name)}<small>${e(statusText[status])}${s?.local_pending?' · Gemt på enheden · Afventer synkronisering':''}</small></span><div class="reward-actions">${pool&&!claimed?this.button('claim',payload,'Tag opgaven',!c.online):['excused','cancelled'].includes(status)?'':this.button(done||status==='pending'?'undo':'complete',payload,done?'✓ Udført':status==='pending'?'Fortryd':'Udfør',item.date>rewardToday())}${this.adult&&!child&&(!pool||claimed)?(status==='pending'?this.button('approve',payload,'Godkend',!c.online)+this.button('reject',payload,'Afvis',!c.online):'')+this.button(status==='excused'?'unexcuse':'excuse',payload,status==='excused'?'Ophæv fritagelse':'Fritag',!c.online):''}</div></div>`}).join('')||'<p>Bonusopgaven er taget af en anden.</p>'}</div></article>`
 }
 bonus(pid){const c=this.c,tasks=materialize(c.items,[rewardToday()],{milestones:false}).filter(t=>t.type==='Opgave'&&rewardRule(t).pool);return tasks.length?`<section class="reward-bonus"><h3>Tjen ekstra <span aria-hidden="true">⭐</span></h3>${tasks.map(t=>this.taskCard(t,pid)).join('')}</section>`:''}
 approvals(){if(!this.adult)return '';const c=this.c,rows=c.state.occurrences.filter(s=>s.status==='pending');return rows.length?`<section class="reward-approval"><h3>Et lille nik fra en voksen <span>${rows.length}</span></h3>${rows.map(s=>`<article><div><strong>${e(s.title)}</strong><small>${e(c.people.find(p=>p.id===s.person_id)?.name)} · ${e(s.due_date)}</small></div><div class="reward-actions">${this.button('approve',{person_id:s.person_id,item_id:s.task_id,occurrence_date:s.occurrence_date,due_date:s.due_date},'Godkend',!c.online)}${this.button('reject',{person_id:s.person_id,item_id:s.task_id,occurrence_date:s.occurrence_date,due_date:s.due_date},'Afvis',!c.online)}</div></article>`).join('')}</section>`:''}
 shop(pid){
  const c=this.c,p=c.people.find(p=>p.id===pid),balance=starBalance(c.state,pid),cfg=rewardConfig(c.state,pid),available=p&&enabled(p)&&cfg.star_rewards_enabled
  return `<section class="reward-shop"><header><div><p class="eyebrow">Små ting at glæde sig til</p><h3>Familiens belønninger</h3></div>${this.adult?'<button data-reward-catalog="new">+ Ny belønning</button>':''}</header>${!p?'<p>Vælg en person øverst for at sætte et mål eller indløse.</p>':`<p class="reward-stars">⭐ ${count("stars",pid,balance)} bonusstjerner${!available?' · Slået fra for denne person':''}</p>`}${!c.online?'<p class="reward-notice">Du skal være online for at indløse en belønning.</p>':''}<div class="reward-catalog">${c.state.catalog.filter(r=>r.active||this.adult).map(r=>`<article data-reward-catalog-card="${r.id}" class="reward-shop-card ${r.active?'':'is-inactive'}"><span class="reward-emoji" aria-hidden="true">${e(r.emoji)}</span><h4>${e(r.title)}</h4>${r.description?`<p>${e(r.description)}</p>`:''}<strong>${r.star_cost} ⭐ ${r.active&&available&&balance>=r.star_cost?'<span class="reward-unlocked" aria-label="Du har stjerner nok">✓ Klar</span>':''} ${!r.active?'· Deaktiveret':''}</strong><div class="reward-actions">${r.active&&available?this.button('goal',{person_id:pid,reward_id:r.id},c.state.goals.some(g=>g.person_id===pid&&g.reward_id===r.id)?'✓ Mit mål':'Mit mål',!c.online)+`<button data-reward-redeem="${r.id}" data-person="${pid}" ${!c.online||balance<r.star_cost?'disabled':''}>${balance<r.star_cost?`Mangler ${r.star_cost-balance} ⭐`:'Indløs'}</button>`:''}${this.adult?`<button data-reward-catalog="${r.id}">Rediger</button>`:''}</div></article>`).join('')||'<div class="reward-empty"><h4>Hvad vil I glæde jer til?</h4><p>Opret familiens egne belønninger. Måske en biograftur, en tur i svømmehallen eller at vælge aftensmad.</p></div>'}</div></section>${this.redemptions(pid)}${this.bonus(pid)}${this.history(pid)}`
 }
 redemptions(pid){const c=this.c,rows=c.state.redemptions.filter(r=>(pid==='Alle'||r.person_id===pid)&&!['cancelled','fulfilled'].includes(r.status));return rows.length?`<section class="reward-redemptions"><h3>På vej til jer</h3>${rows.map(r=>`<article data-reward-redemption="${r.id}"><div><strong>${e(r.emoji)} ${e(r.title)}</strong><small>${e(c.people.find(p=>p.id===r.person_id)?.name)} · ${r.star_cost} ⭐ · ${r.status==='pending'?'Sendt til godkendelse':'Godkendt · Klar 🎟️'}</small></div><div class="reward-actions">${this.adult?(r.status==='pending'?this.button('redemption_approve',{id:r.id},'Godkend',!c.online)+this.button('redemption_cancel',{id:r.id},'Afvis',!c.online):this.button('redemption_fulfill',{id:r.id},'Gennemført',!c.online)):''}</div></article>`).join('')}</section>`:''}
 history(pid){const c=this.c,snaps=c.state.snapshots.filter(s=>pid==='Alle'||s.person_id===pid),ledger=c.state.ledger.filter(s=>pid==='Alle'||s.person_id===pid);return `<details class="reward-history" data-reward-history="${pid}" ${this.historyOpen.has(pid)?'open':''}><summary>Historik · lommepenge & stjerner</summary><p class="hint">Lommepenge er en beregning. Appen flytter ikke penge.</p>${snaps.map(s=>`<article><div><strong>${e(c.people.find(p=>p.id===s.person_id)?.name)} · ${monthName(s.year+'-'+String(s.month).padStart(2,'0')+'-01')}</strong><small>${s.completion_percent} % · ${currency(s.earned_minor)} / ${currency(s.allowance_minor)}</small></div>${s.payout_status==='paid'?'<span>Udbetalt ✓</span>':this.adult?this.button('payout',{id:s.id},'Markér udbetalt',!c.online):'<span>Afventer udbetaling</span>'}</article>`).join('')||'<p>Afsluttede måneder vises her.</p>'}<h4>Stjerneregnskab</h4>${ledger.slice(0,50).map(l=>`<article><div><strong>${e(l.reason)}</strong><small>${e(c.people.find(p=>p.id===l.person_id)?.name)} · ${new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'short'}).format(new Date(l.created_at))}</small></div><b>${l.delta>0?'+':''}${l.delta} ⭐</b></article>`).join('')||'<p>Stjerner fra nye bonusopgaver vises her.</p>'}${ledger.length>50?'<p>Viser de seneste 50 poster. Familiens dataeksport indeholder hele regnskabet.</p>':''}</details>`}
 modal(title,body,kind){this.dialog=kind;this.root.innerHTML=`<div class="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="reward-dialog-title"><section class="reward-modal"><header class="modal-header"><h2 id="reward-dialog-title">${e(title)}</h2><button data-reward-close aria-label="Luk">×</button></header>${body}<p class="message" id="reward-dialog-message" role="status"></p></section></div>`;this.bind(this.root)}
 child(pid){this.childId=pid;this.renderChild()}
 renderChild(){const c=this.c,p=c.people.find(p=>p.id===this.childId);if(!p){this.close(true);return}const daily=materialize(c.items,[rewardToday()]).filter(t=>rewardRule(t).pool?taskPeople(t,c.people,c.state).some(person=>person.id===p.id):itemMatchesPerson(t,p.id,c.people)),tasks=daily.filter(t=>t.type==='Opgave'),activities=daily.filter(t=>!['Opgave','Madplan','Indkøb'].includes(t.type));this.modal('Min dag',this.dashboard(p.id,{child:true})+`<section class="reward-child-tasks"><h3>Dagens opgaver</h3>${tasks.map(t=>this.taskCard(t,p.id,{child:true})).join('')||'<p>Ingen opgaver i dag. Nyd dagen.</p>'}</section><section><h3>Dagens aktiviteter</h3>${activities.map(t=>`<article class="reward-child-activity"><time>${e(t.time||'Heldag')}</time><strong>${e(t.title)}</strong></article>`).join('')||'<p>Der er plads i kalenderen i dag.</p>'}</section>`, 'child')}
 taskDetail(item,pid='Alle'){this.detailItem=item;this.detailPerson=pid;this.modal('Opgave',this.taskCard(item,pid),'task-detail')}
 refresh(){if(this.dialog==='task-detail'&&!this.busy){const item=materialize(this.c.items,[this.detailItem.date]).find(i=>i.id===this.detailItem.id);if(item)this.taskDetail(item,this.detailPerson);else this.close(true)}if(this.dialog==='child'&&!this.busy)this.renderChild()}
 config(pid){if(!this.adult)return;const c=this.c,p=c.people.find(p=>p.id===pid),cfg=rewardConfig(c.state,pid);this.modal('Opgaver & belønning',`<form id="reward-config-form" class="stack-form" data-person="${pid}"><h3>${e(p.name)}</h3>${[['reward_enabled','Deltager i belønningssystem',enabled(p)],['allowance_enabled','Månedlige lommepenge',cfg.allowance_enabled]].map(([key,label,checked])=>`<label><input type="checkbox" name="${key}" ${checked?'checked':''}> ${label}</label>`).join('')}<label for="reward-monthly">Månedligt beløb i kroner</label><input id="reward-monthly" name="amount" inputmode="decimal" required value="${String(cfg.monthly_allowance_minor/100).replace('.',',')}">${[['star_rewards_enabled','Bonusstjerner',cfg.star_rewards_enabled],['default_requires_approval','Nye opgaver kræver voksengodkendelse',cfg.default_requires_approval]].map(([key,label,checked])=>`<label><input type="checkbox" name="${key}" ${checked?'checked':''}> ${label}</label>`).join('')}<p class="hint">Første opsætning gælder fra i dag. Senere deltagelsesændringer gælder fra i morgen. Månedens beløb fastholdes; et nyt beløb gælder fra næste måned.</p><button type="submit" ${!c.online?'disabled':''}>Gem indstillinger</button></form>`,'config')}
 catalog(id){if(!this.adult)return;const r=this.c.state.catalog.find(r=>r.id===id)||{title:'',emoji:'⭐',description:'',star_cost:100,active:true};this.modal(r.id?'Rediger belønning':'Ny belønning',`<form id="reward-catalog-form" class="stack-form" data-id="${r.id||''}"><label for="reward-title">Hvad kan man glæde sig til?</label><input id="reward-title" name="title" required maxlength="120" value="${e(r.title)}"><label for="reward-emoji">Symbol</label><input id="reward-emoji" name="emoji" maxlength="16" value="${e(r.emoji)}"><label for="reward-description">Beskrivelse</label><textarea id="reward-description" name="description" maxlength="1000">${e(r.description)}</textarea><label for="reward-cost">Pris i bonusstjerner</label><input id="reward-cost" name="star_cost" type="number" min="1" max="1000000" step="1" required value="${r.star_cost}"><label><input name="active" type="checkbox" ${r.active?'checked':''}> Tilgængelig i familiens butik</label><button type="submit" ${!this.c.online?'disabled':''}>Gem belønning</button></form>`,'catalog')}
 async run(action,payload,button){if(this.busy)return;const context=this.c.key;this.busy=true;if(button)button.disabled=true;try{const result=await this.onAction(action,payload);if(result?.error)throw result.error;if(this.c.key!==context)return;if(['config','catalog','redeem','excuse','reject'].includes(this.dialog))this.close(true);else if(this.dialog==='child'){this.busy=false;this.renderChild()}else if(this.dialog==='task-detail'){this.busy=false;this.refresh()}}catch(error){if(this.c.key===context){const target=this.root.querySelector('#reward-dialog-message')||document.querySelector('#reward-message');if(target)target.textContent=error.message;else this.modal('Kunne ikke gemme',`<p>${e(error.message)}</p>`,'error')}}finally{this.busy=false;if(button?.isConnected)button.disabled=false}}
 bind(root=document){
  root.querySelectorAll('[data-reward-history]').forEach(d=>d.ontoggle=()=>{if(d.open)this.historyOpen.add(d.dataset.rewardHistory);else this.historyOpen.delete(d.dataset.rewardHistory)})
  root.querySelectorAll('[data-reward-close]').forEach(b=>b.onclick=()=>this.close())
  root.querySelectorAll('[data-reward-select]').forEach(b=>b.onclick=()=>this.onSelect(b.dataset.rewardSelect))
  root.querySelectorAll('[data-child-day]').forEach(b=>b.onclick=()=>this.child(b.dataset.childDay))
  root.querySelectorAll('[data-reward-config]').forEach(b=>b.onclick=()=>this.config(b.dataset.rewardConfig))
  root.querySelectorAll('[data-reward-catalog]').forEach(b=>b.onclick=()=>this.catalog(b.dataset.rewardCatalog))
  root.querySelectorAll('[data-reward-edit]').forEach(b=>b.onclick=()=>this.onEdit(b.dataset.rewardEdit))
  root.querySelectorAll('[data-reward-legacy]').forEach(b=>b.onclick=async()=>{await this.onToggle(b.dataset.rewardLegacy,b.dataset.done==='true');this.refresh()})
  root.querySelectorAll('[data-reward-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.rewardAction,payload=JSON.parse(b.dataset.rewardPayload);if(['excuse','reject'].includes(action)){this.modal(action==='excuse'?'Fritag denne opgave':'Afvis og genåbn',`<form id="reward-reason-form" class="stack-form"><label for="reward-reason">Kort begrundelse</label><input id="reward-reason" name="reason" maxlength="500" required placeholder="Fx syg eller opgaven skal gøres færdig"><button type="submit">${action==='excuse'?'Fritag':'Afvis'}</button></form>`,action);this.root.querySelector('form').onsubmit=ev=>{ev.preventDefault();this.run(action,{...payload,reason:new FormData(ev.target).get('reason')},ev.submitter)}}else this.run(action,payload,b)})
  root.querySelectorAll('[data-reward-redeem]').forEach(b=>b.onclick=()=>{const r=this.c.state.catalog.find(r=>r.id===b.dataset.rewardRedeem);this.modal('Indløs belønning',`<p>Vil du bruge ${r.star_cost} ⭐ på <strong>${e(r.title)}</strong>?</p><p>En voksen godkender. Stjernerne trækkes først ved godkendelse.</p>${this.button('redeem',{person_id:b.dataset.person,reward_id:r.id},'Bed om belønningen')}`,'redeem')})
  const configForm=root.querySelector('#reward-config-form');if(configForm)configForm.onsubmit=ev=>{ev.preventDefault();try{const f=new FormData(ev.target),payload={person_id:ev.target.dataset.person,monthly_allowance_minor:parseCurrency(f.get('amount'))};for(const k of ['reward_enabled','allowance_enabled','star_rewards_enabled','default_requires_approval'])payload[k]=f.has(k);this.run('config',payload,ev.submitter)}catch(error){this.root.querySelector('#reward-dialog-message').textContent=error.message}}
  const catalogForm=root.querySelector('#reward-catalog-form');if(catalogForm)catalogForm.onsubmit=ev=>{ev.preventDefault();const f=new FormData(ev.target);this.run('catalog',{id:ev.target.dataset.id||undefined,title:f.get('title'),emoji:f.get('emoji'),description:f.get('description'),star_cost:Number(f.get('star_cost')),active:f.has('active')},ev.submitter)}
 }
}