import {t,userError,dateFormatter,labels,formatNumber} from '../i18n/index.js'
import {allowanceTasks,periodLabel,currentAgreement} from './allowance-model.js'
import {agreementSettings,allowanceHistory} from './allowance-ui.js'
import {emptyRewards,enabled,rewardConfig,rewardRule,managedTask,occurrenceState,isApproved,starBalance,rewardGoal,taskPeople,actionPayload,currency,parseCurrency,monthProgress,rewardToday} from './rewards-model.js'
import {materialize} from './calendar-semantics.js'
import {itemMatchesPerson} from './people.js'
import {weeklyProgress} from './task-rewards.js'
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const attr=o=>e(JSON.stringify(o)), monthName=day=>dateFormatter({month:'long',year:'numeric'}).format(new Date(day+'T12:00:00'))
const statusText=labels({open:'rewards.ready_to_get_started',pending:'rewards.awaiting_approval',approved:'rewards.approved',completed:'app.completed',rejected:'app.try_again',excused:'rewards.excused',cancelled:'rewards.cancelled'})
const count=(kind,pid,n,format=n=>formatNumber(n))=>`<span><span aria-hidden="true" data-reward-count="${kind}:${pid}">${e(format(n))}</span><span class="sr-only">${e(format(n))}</span></span>`
const allowanceCount=(pid,m)=>m.earned_minor==null?("<span>"+t("allowance.awaiting_agreement")+"</span>"):count('allowance',pid,m.earned_minor,currency)
const progress=(value,max,label,key)=>`<progress ${key?`data-reward-progress="${key}"`:""} value="${Math.max(0,value)}" max="${Math.max(1,max)}" aria-label="${e(label)}"></progress>`
export class RewardsUI {
 constructor({getContext,onAction,onSelect,onToggle,onEdit,avatar}){
  Object.assign(this,{getContext,onAction,onSelect,onToggle,onEdit,avatar});this.root=document.createElement('div');document.body.append(this.root);this.busy=false;this.dialog=null;this.historyOpen=new Set()
  this.root.addEventListener('dismiss-dialog',()=>this.close())
 }
 get c(){const c=this.getContext();return {...c,state:c.state||emptyRewards()}}
 get adult(){return ['adult','admin','owner'].includes(this.c.role)&&this.c.mode!=='kiosk'}
 close(force=false){if(this.busy&&!force)return;this.root.innerHTML='';this.dialog=null;this.busy=false}
 get opened(){return !!this.dialog}
 button(action,payload,label,disabled=false){return `<button type="button" data-reward-action="${action}" data-reward-payload="${attr(payload)}" ${disabled?'disabled':''}>${label}</button>`}
 people(){return this.c.people.filter(p=>p.is_active!==false&&enabled(p))}
 summary(kiosk=false){const c=this.c;return `<div class="reward-people ${kiosk?'reward-people-kiosk':''}" aria-label="${t("rewards.family_tasks_and_rewards")}">${this.people().map(p=>{const m=monthProgress(c.items,c.people,c.state,p.id),cfg=rewardConfig(c.state,p.id),w=weeklyProgress(c.items,[p],rewardToday(),rewardToday(),c.state)[0];return `<button class="reward-person-summary" data-reward-person-panel="${p.id}" ${kiosk?'data-child-day':'data-reward-select'}="${p.id}">${this.avatar(p,'reward-avatar')}<span><strong>${e(p.name)}</strong>${cfg.allowance_enabled?`<small>${allowanceCount(p.id,m)} / ${currency(m.allowance_minor)}</small>`:`<small>${w?.count||0} ${kiosk?'klaret':(t("rewards.completed_this_week"))}</small>`}</span>${cfg.star_rewards_enabled?`<b class="reward-stars">⭐ ${count('stars',p.id,starBalance(c.state,p.id))}</b>`:''}</button>`}).join('')}</div>`}
 dashboard(pid,{child=false}={}){
  const c=this.c,p=c.people.find(p=>p.id===pid);if(!p)return ''
  const cfg=rewardConfig(c.state,pid),m=monthProgress(c.items,c.people,c.state,pid),balance=starBalance(c.state,pid),goal=rewardGoal(c.state,pid),w=weeklyProgress(c.items,c.people,rewardToday(),rewardToday(),c.state).find(w=>w.personId===pid)
  return `<section class="reward-dashboard" data-reward-person-panel="${pid}"><header class="reward-person-heading">${this.avatar(p,'reward-avatar')}<div><p class="eyebrow">${child?(t("app.my_day")):(t("rewards.tasks_rewards"))}</p><h3>${e(p.name)}</h3></div>${!child?`<button data-child-day="${pid}">${t("rewards.my_day")}</button>`:''}</header><div class="reward-metrics">${cfg.allowance_enabled?`<article class="reward-month"><p class="eyebrow">${m.period_start?periodLabel(m):(t("allowance.allowance_agreement"))}</p><strong>${allowanceCount(pid,m)} <small>/ ${currency(m.allowance_minor)}</small></strong>${progress(m.completion_percent,100,(t("rewards.regular_chores_this_period")),'month:'+pid)}<p>${count('percent',pid,m.completion_percent,n=>formatNumber(n,{maximumFractionDigits:1})+' %')} · ${m.completed_total} / ${m.eligible_total} ${t("rewards.tasks")}${m.excused_total?` · ${m.excused_total} ${t("rewards.excused_fritaget")}`:''}</p>${m.neutral?'<p class="allowance-neutral">'+(m.neutral==='empty'?(t("rewards.no_regular_chores_set_up")):m.neutral==='all_excused'?(t("rewards.all_chores_are_excused_agree_the_amount_with_an_adult")):currentAgreement(c.state,pid)?.needs_review?(t("rewards.the_allowance_agreement_needs_review")):(t("rewards.the_agreement_starts_next_period")))+'</p>':''}${c.state.occurrences.some(o=>o.person_id===pid&&o.local_pending&&o.reward_mode==='allowance')?("<small class=\"reward-awaiting\">"+t("rewards.waiting_to_sync_amount_confirmed")+"</small>"):''}</article>`:''}${cfg.star_rewards_enabled?`<article class="reward-star-balance"><p class="eyebrow">${t("app.bonus_stars")}</p><strong>⭐ ${count('stars',pid,balance)}</strong><p>${t("rewards.for_the_family_s_rewards")}</p></article>`:''}</div>${goal&&cfg.star_rewards_enabled?`<article class="reward-goal"><div><span aria-hidden="true">${e(goal.emoji)}</span><span><small>${t("rewards.my_goal")}</small><strong>${e(goal.title)}</strong></span><b>${count('goal',pid,balance)} / ${goal.star_cost} ⭐</b></div>${progress(balance,goal.star_cost,(t("rewards.stars_towards_my_goal")),'goal:'+pid)}<p>${balance>=goal.star_cost?`${t("rewards.you_have_enough_for")} ${e(goal.title)}!`:`${t("rewards.still_needed")} ${goal.star_cost-balance} ⭐`}</p></article>`:''}<p class="reward-week-count">${w?.count||0} ${t("rewards.tasks_completed_this_week")}</p></section>`
 }
 taskCard(item,pid='Alle',{child=false}={}){
  const c=this.c,rule=rewardRule(item),people=taskPeople(item,c.people,c.state).filter(p=>pid==='Alle'||p.id===pid),pool=rule.pool,claimed=c.state.occurrences.some(s=>s.origin_id===(item.data?.rewardOriginId||item.baseId||item.id)&&s.occurrence_date===(item.occurrenceDate||item.data?.originalDate||item.date)&&s.claimed),locked=!!(c.state.contracts||[]).find(p=>p.id===item.data?.allowanceContractId&&p.closed_at)
  if(!managedTask(item))return `<article class="reward-task" data-reward-task="${e(item.id)}"><div><strong>${e(item.title)}</strong><small>${e(item.time||(t("rewards.when_it_suits_you")))}</small></div><button data-reward-legacy="${e(item.id)}" data-done="${!item.done}" aria-label="${item.done?(t("rewards.reopen")):(t("rewards.complete"))} ${e(item.title)}">${item.done?(t("rewards.completed")):(t("rewards.complete"))}</button></article>`
  return `<article class="reward-task ${pool?'reward-bonus-task':''}" data-reward-task="${e(item.id)}"><div class="reward-task-title"><span aria-hidden="true">${rule.mode==='stars'?'✦':'✓'}</span><div>${child?`<strong>${e(item.title)}</strong>`:`<button class="reward-title-button" data-reward-edit="${e(item.id)}">${e(item.title)}</button>`}<small>${rule.mode==='stars'?`+${rule.stars} ⭐`:rule.mode==='allowance'?(t("rewards.regular_allowance_chore"))+(item.data?.windowEnd>item.data?.allowanceDueDate?(" "+t("rewards.this_week_s_chore")):'')+(locked?(" "+t("rewards.finished")):''):'Opgave'}${rule.approval?(" "+t("rewards.adult_approval")):''}</small></div></div><div class="reward-task-people">${people.map(p=>{const s=occurrenceState(c.state,item,p.id),status=s?.status||'open',payload=actionPayload(item,p.id),done=isApproved(s);return `<div class="reward-task-person"><span>${e(p.name)}<small>${e(statusText[status])}${s?.local_pending?(" "+t("rewards.saved_on_device_waiting_to_sync")):''}</small></span><div class="reward-actions">${pool&&!claimed?this.button('claim',payload,(t("rewards.take_this_task")),!c.online):['excused','cancelled'].includes(status)?'':this.button(done||status==='pending'?'undo':'complete',payload,done?(t("rewards.completed")):status==='pending'?(t("rewards.undo")):(t("rewards.complete")),item.date>rewardToday()||locked)}${this.adult&&!child&&!locked&&(!pool||claimed)?(status==='pending'?this.button('approve',payload,(t("rewards.approve")),!c.online)+this.button('reject',payload,(t("rewards.reject")),!c.online):'')+this.button(status==='excused'?'unexcuse':'excuse',payload,status==='excused'?(t("rewards.remove_excuse")):(t("rewards.excuse")),!c.online):''}</div></div>`}).join('')||("<p>"+t("rewards.someone_else_has_taken_this_bonus_task")+"</p>")}</div></article>`
 }
 bonus(pid){const c=this.c,tasks=materialize(c.items,[rewardToday()],{milestones:false}).filter(t=>t.type==='Opgave'&&rewardRule(t).pool);return tasks.length?`<section class="reward-bonus"><h3>${t("rewards.earn_extra")} <span aria-hidden="true">⭐</span></h3>${tasks.map(t=>this.taskCard(t,pid)).join('')}</section>`:''}
 approvals(){if(!this.adult)return '';const c=this.c,rows=c.state.occurrences.filter(s=>s.status==='pending'&&(!s.allowance_contract_id||!(c.state.contracts||[]).find(p=>p.id===s.allowance_contract_id)?.closed_at));return rows.length?`<section class="reward-approval"><h3>${t("rewards.a_little_nod_from_an_adult")} <span>${rows.length}</span></h3>${rows.map(s=>`<article><div><strong>${e(s.title)}</strong><small>${e(c.people.find(p=>p.id===s.person_id)?.name)} · ${e(s.due_date)}</small></div><div class="reward-actions">${this.button('approve',{person_id:s.person_id,item_id:s.task_id,occurrence_date:s.occurrence_date,due_date:s.due_date},(t("rewards.approve")),!c.online)}${this.button('reject',{person_id:s.person_id,item_id:s.task_id,occurrence_date:s.occurrence_date,due_date:s.due_date},(t("rewards.reject")),!c.online)}</div></article>`).join('')}</section>`:''}
 shop(pid){
  const c=this.c,p=c.people.find(p=>p.id===pid),balance=starBalance(c.state,pid),cfg=rewardConfig(c.state,pid),available=p&&enabled(p)&&cfg.star_rewards_enabled
  return `<section class="reward-shop"><header><div><p class="eyebrow">${t("rewards.little_things_to_look_forward_to")}</p><h3>${t("rewards.family_rewards")}</h3></div>${this.adult?("<button data-reward-catalog=\"new\">"+t("rewards.new_reward")+"</button>"):''}</header>${!p?("<p>"+t("rewards.choose_a_person_above_to_set_a_goal_or_redeem_a_reward")+"</p>"):`<p class="reward-stars">⭐ ${count("stars",pid,balance)} ${t("rewards.bonus_stars")}${!available?(" "+t("rewards.disabled_for_this_person")):''}</p>`}${!c.online?("<p class=\"reward-notice\">"+t("app.you_need_to_be_online_to_redeem_a_reward")+"</p>"):''}<div class="reward-catalog">${c.state.catalog.filter(r=>r.active||this.adult).map(r=>`<article data-reward-catalog-card="${r.id}" class="reward-shop-card ${r.active?'':'is-inactive'}"><span class="reward-emoji" aria-hidden="true">${e(r.emoji)}</span><h4>${e(r.title)}</h4>${r.description?`<p>${e(r.description)}</p>`:''}<strong>${r.star_cost} ⭐ ${r.active&&available&&balance>=r.star_cost?("<span class=\"reward-unlocked\" aria-label=\""+t("rewards.you_have_enough_stars")+"\">"+t("rewards.ready")+"</span>"):''} ${!r.active?(t("rewards.disabled")):''}</strong><div class="reward-actions">${r.active&&available?this.button('goal',{person_id:pid,reward_id:r.id},c.state.goals.some(g=>g.person_id===pid&&g.reward_id===r.id)?(t("rewards.my_goal__mit_mal")):(t("rewards.my_goal")),!c.online)+`<button data-reward-redeem="${r.id}" data-person="${pid}" ${!c.online||balance<r.star_cost?'disabled':''}>${balance<r.star_cost?`${t("rewards.still_needed")} ${r.star_cost-balance} ⭐`:(t("rewards.redeem"))}</button>`:''}${this.adult?`<button data-reward-catalog="${r.id}">${t("app.edit")}</button>`:''}</div></article>`).join('')||("<div class=\"reward-empty\"><h4>"+t("rewards.what_will_you_look_forward_to")+"</h4><p>"+t("rewards.create_your_family_s_own_rewards_perhaps_a_cinema_trip_a_swim_or_choosing_dinner")+"</p></div>")}</div></section>${this.redemptions(pid)}${this.bonus(pid)}${this.history(pid)}`
 }
 redemptions(pid){const c=this.c,rows=c.state.redemptions.filter(r=>(pid==='Alle'||r.person_id===pid)&&!['cancelled','fulfilled'].includes(r.status));return rows.length?`<section class="reward-redemptions"><h3>${t("rewards.on_the_way")}</h3>${rows.map(r=>`<article data-reward-redemption="${r.id}"><div><strong>${e(r.emoji)} ${e(r.title)}</strong><small>${e(c.people.find(p=>p.id===r.person_id)?.name)} · ${r.star_cost} ⭐ · ${r.status==='pending'?(t("reward_motion.sent_for_approval")):(t("rewards.approved_ready"))}</small></div><div class="reward-actions">${this.adult?(r.status==='pending'?this.button('redemption_approve',{id:r.id},(t("rewards.approve")),!c.online)+this.button('redemption_cancel',{id:r.id},(t("rewards.reject")),!c.online):this.button('redemption_fulfill',{id:r.id},(t("rewards.completed_gennemf_rt")),!c.online)):''}</div></article>`).join('')}</section>`:''}
 history(pid){const c=this.c,snaps=c.state.snapshots.filter(s=>pid==='Alle'||s.person_id===pid),ledger=c.state.ledger.filter(s=>pid==='Alle'||s.person_id===pid);return `<details class="reward-history" data-reward-history="${pid}" ${this.historyOpen.has(pid)?'open':''}><summary>${t("rewards.history_allowance_stars")}</summary><p class="hint">${t("rewards.allowance_is_a_calculation_the_app_does_not_transfer_money")}</p>${allowanceHistory(this,pid)}${snaps.map(s=>`<article><div><strong>${e(c.people.find(p=>p.id===s.person_id)?.name)} · ${monthName(s.year+'-'+String(s.month).padStart(2,'0')+'-01')}</strong><small>${s.completion_percent} % · ${currency(s.earned_minor)} / ${currency(s.allowance_minor)}</small></div>${s.payout_status==='paid'?("<span>"+t("allowance.paid")+"</span>"):this.adult?this.button('payout',{id:s.id},(t("allowance.mark_paid")),!c.online):("<span>"+t("allowance.awaiting_payment")+"</span>")}</article>`).join('')||("<p>"+t("rewards.completed_months_appear_here")+"</p>")}<h4>${t("rewards.star_ledger")}</h4>${ledger.slice(0,50).map(l=>`<article><div><strong>${e(l.reason)}</strong><small>${e(c.people.find(p=>p.id===l.person_id)?.name)} · ${dateFormatter({day:'numeric',month:'short'}).format(new Date(l.created_at))}</small></div><b>${l.delta>0?'+':''}${l.delta} ⭐</b></article>`).join('')||("<p>"+t("rewards.stars_from_new_bonus_tasks_appear_here")+"</p>")}${ledger.length>50?("<p>"+t("rewards.showing_the_latest_50_entries_the_family_data_export_includes_the_complete_ledger")+"</p>"):''}</details>`}
 modal(title,body,kind){this.dialog=kind;this.root.innerHTML=`<div class="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="reward-dialog-title"><section class="reward-modal"><header class="modal-header"><h2 id="reward-dialog-title">${e(title)}</h2><button data-reward-close aria-label="${t("common.close")}">×</button></header>${body}<p class="message" id="reward-dialog-message" role="status"></p></section></div>`;this.bind(this.root)}
 child(pid){this.childId=pid;this.renderChild()}
 renderChild(){const c=this.c,p=c.people.find(p=>p.id===this.childId);if(!p){this.close(true);return}const daily=allowanceTasks(materialize(c.items,[rewardToday()]),c.state,[rewardToday()]).filter(t=>rewardRule(t).pool?taskPeople(t,c.people,c.state).some(person=>person.id===p.id):itemMatchesPerson(t,p.id,c.people)),tasks=daily.filter(t=>t.type==='Opgave'),activities=daily.filter(t=>!['Opgave','Madplan','Indkøb'].includes(t.type));this.modal((t("app.my_day")),this.dashboard(p.id,{child:true})+`<section class="reward-child-tasks"><h3>${t("app.today_s_tasks")}</h3>${tasks.map(t=>this.taskCard(t,p.id,{child:true})).join('')||("<p>"+t("rewards.no_tasks_today_enjoy_your_day")+"</p>")}</section><section><h3>${t("rewards.today_s_activities")}</h3>${activities.map(item=>`<article class="reward-child-activity"><time>${e(item.time||(t("calendar.all_day")))}</time><strong>${e(item.title)}</strong></article>`).join('')||("<p>"+t("rewards.there_is_room_in_the_calendar_today")+"</p>")}</section>`, 'child')}
 taskDetail(item,pid='Alle'){this.detailItem=item;this.detailPerson=pid;this.modal('Opgave',this.taskCard(item,pid),'task-detail')}
 refresh(){if(this.dialog==='task-detail'&&!this.busy){const item=allowanceTasks(materialize(this.c.items,[this.detailItem.date]),this.c.state,[this.detailItem.date]).find(i=>i.id===this.detailItem.id);if(item)this.taskDetail(item,this.detailPerson);else this.close(true)}if(this.dialog==='child'&&!this.busy)this.renderChild()}
 config(pid){agreementSettings(this,pid)}
 catalog(id){if(!this.adult)return;const r=this.c.state.catalog.find(r=>r.id===id)||{title:'',emoji:'⭐',description:'',star_cost:100,active:true};this.modal(r.id?(t("rewards.edit_reward")):(t("rewards.new_reward_ny_bel_nning")),`<form id="reward-catalog-form" class="stack-form" data-id="${r.id||''}"><label for="reward-title">${t("rewards.what_can_you_look_forward_to")}</label><input id="reward-title" name="title" required maxlength="120" value="${e(r.title)}"><label for="reward-emoji">${t("rewards.symbol")}</label><input id="reward-emoji" name="emoji" maxlength="16" value="${e(r.emoji)}"><label for="reward-description">${t("rewards.description")}</label><textarea id="reward-description" name="description" maxlength="1000">${e(r.description)}</textarea><label for="reward-cost">${t("rewards.cost_in_bonus_stars")}</label><input id="reward-cost" name="star_cost" type="number" min="1" max="1000000" step="1" required value="${r.star_cost}"><label><input name="active" type="checkbox" ${r.active?'checked':''}> ${t("rewards.available_in_the_family_shop")}</label><button type="submit" ${!this.c.online?'disabled':''}>${t("rewards.save_reward")}</button></form>`,'catalog')}
 async run(action,payload,button){if(this.busy)return;const context=this.c.key;this.busy=true;if(button)button.disabled=true;try{const result=await this.onAction(action,payload);if(result?.error)throw result.error;if(this.c.key!==context)return;if(['config','allowance','catalog','redeem','excuse','reject','allowance-resolve'].includes(this.dialog))this.close(true);else if(this.dialog==='child'){this.busy=false;this.renderChild()}else if(this.dialog==='task-detail'){this.busy=false;this.refresh()}}catch(error){if(this.c.key===context){const target=this.root.querySelector('#reward-dialog-message')||document.querySelector('#reward-message');if(target)target.textContent=userError(error);else this.modal((t("rewards.could_not_save")),`<p>${e(userError(error))}</p>`,'error')}}finally{this.busy=false;if(button?.isConnected)button.disabled=false}}
 bind(root=document){
  root.querySelectorAll('[data-reward-history]').forEach(d=>d.ontoggle=()=>{if(d.open)this.historyOpen.add(d.dataset.rewardHistory);else this.historyOpen.delete(d.dataset.rewardHistory)})
  root.querySelectorAll('[data-allowance-resolve]').forEach(b=>b.onclick=()=>{this.modal((t("rewards.agree_this_period_s_amount")),("<form id=\"allowance-resolve-form\" class=\"stack-form\"><p>"+t("rewards.all_chores_were_excused_agree_the_amount_together_the_app_does_not_transfer_money")+"</p><label>"+t("allowance.amount")+"<input name=\"amount\" inputmode=\"decimal\" required value=\"")+Number(b.dataset.amount)/100+("\"></label><button type=\"submit\">"+t("rewards.save_agreed_amount")+"</button></form>"),'allowance-resolve');this.root.querySelector('form').onsubmit=ev=>{ev.preventDefault();try{this.run('allowance_resolve',{id:b.dataset.allowanceResolve,amount_minor:parseCurrency(new FormData(ev.target).get('amount'))},ev.submitter)}catch(error){this.root.querySelector('#reward-dialog-message').textContent=userError(error)}}})
  root.querySelectorAll('[data-reward-close]').forEach(b=>b.onclick=()=>this.close())
  root.querySelectorAll('[data-reward-select]').forEach(b=>b.onclick=()=>this.onSelect(b.dataset.rewardSelect))
  root.querySelectorAll('[data-child-day]').forEach(b=>b.onclick=()=>this.child(b.dataset.childDay))
  root.querySelectorAll('[data-reward-config]').forEach(b=>b.onclick=()=>this.config(b.dataset.rewardConfig))
  root.querySelectorAll('[data-reward-catalog]').forEach(b=>b.onclick=()=>this.catalog(b.dataset.rewardCatalog))
  root.querySelectorAll('[data-reward-edit]').forEach(b=>b.onclick=()=>this.onEdit(b.dataset.rewardEdit))
  root.querySelectorAll('[data-reward-legacy]').forEach(b=>b.onclick=async()=>{await this.onToggle(b.dataset.rewardLegacy,b.dataset.done==='true');this.refresh()})
  root.querySelectorAll('[data-reward-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.rewardAction,payload=JSON.parse(b.dataset.rewardPayload);if(['excuse','reject'].includes(action)){this.modal(action==='excuse'?(t("rewards.excuse_this_task")):(t("rewards.reject_and_reopen")),`<form id="reward-reason-form" class="stack-form"><label for="reward-reason">${t("rewards.brief_reason")}</label><input id="reward-reason" name="reason" maxlength="500" required placeholder="${t("rewards.for_example_ill_or_the_task_needs_finishing")}"><button type="submit">${action==='excuse'?(t("rewards.excuse")):(t("rewards.reject"))}</button></form>`,action);this.root.querySelector('form').onsubmit=ev=>{ev.preventDefault();this.run(action,{...payload,reason:new FormData(ev.target).get('reason')},ev.submitter)}}else this.run(action,payload,b)})
  root.querySelectorAll('[data-reward-redeem]').forEach(b=>b.onclick=()=>{const r=this.c.state.catalog.find(r=>r.id===b.dataset.rewardRedeem);this.modal((t("rewards.redeem_reward")),`<p>${t("rewards.would_you_like_to_spend")} ${r.star_cost} ${t("rewards.on")} <strong>${e(r.title)}</strong>?</p><p>${t("rewards.an_adult_approves_stars_are_deducted_only_on_approval")}</p>${this.button('redeem',{person_id:b.dataset.person,reward_id:r.id},(t("rewards.request_this_reward")))}`,'redeem')})
  const configForm=root.querySelector('#reward-config-form');if(configForm)configForm.onsubmit=ev=>{ev.preventDefault();try{const f=new FormData(ev.target),payload={person_id:ev.target.dataset.person,monthly_allowance_minor:parseCurrency(f.get('amount'))};for(const k of ['reward_enabled','allowance_enabled','star_rewards_enabled','default_requires_approval'])payload[k]=f.has(k);this.run('config',payload,ev.submitter)}catch(error){this.root.querySelector('#reward-dialog-message').textContent=userError(error)}}
  const catalogForm=root.querySelector('#reward-catalog-form');if(catalogForm)catalogForm.onsubmit=ev=>{ev.preventDefault();const f=new FormData(ev.target);this.run('catalog',{id:ev.target.dataset.id||undefined,title:f.get('title'),emoji:f.get('emoji'),description:f.get('description'),star_cost:Number(f.get('star_cost')),active:f.has('active')},ev.submitter)}
 }
}