import {expandTaskAdvanced} from './browser-actions.mjs'
import {openCreate,openSettings,logout,toggleView,routeTo,switchHousehold} from './browser-actions.mjs'

import { chromium, expect } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { localSupabase } from '../../scripts/local-supabase.mjs'
process.chdir(fileURLToPath(new URL('../../', import.meta.url)))
const local=localSupabase(), admin=createClient(local.API_URL,local.SERVICE_ROLE_KEY,{auth:{persistSession:false}})
const browser=await chromium.launch({executablePath:process.env.TEST_BROWSER_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true})
const email='mega2-'+randomUUID()+'@example.test', password=randomUUID()+'!Aa1'
let uid,hid,checks=0
const errors=[]
const pass=label=>{checks++;console.log('PASS '+checks+': '+label)}
const must=async query=>{const result=await query;if(result.error)throw result.error;return result.data}
const today='2026-09-28'
async function newPage(width) {
  const context=await browser.newContext({viewport:{width,height:900},timezoneId:'Europe/Copenhagen'})
  const page=await context.newPage()
  page.on('pageerror',error=>errors.push(error.message))
  // Mega 3 protects unsynced edits on logout. This test deliberately leaves one conflict.
  page.on('dialog',dialog=>dialog.accept())
  await page.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())
  await page.clock.setFixedTime(new Date('2026-09-28T12:00:00+02:00'))
  await page.goto('http://127.0.0.1:5178')
  await page.locator('#email').fill(email);await page.locator('#password').fill(password)
  await page.getByRole('button',{name:'Log ind',exact:true}).click()
  await expect(page.locator('.product-nav')).toBeVisible()
  await page.locator('.product-nav [data-product-route=calendar]').click()
  await expect(page.locator('#calendar-view .day-card').first()).toBeVisible()
  return page
}
const card=(page,title)=>page.locator('[data-calendar-item]').filter({has:page.locator('strong',{hasText:title})}).first()
async function nextWeek(page){const steps=await page.locator('.day-view').count()?7:1;for(let i=0;i<steps;i++)await page.locator('#calendar-next-button').click()}
async function unfold(page){const d=page.locator('[data-completed-date]');if(await d.count()&&await d.first().getAttribute('open')===null)await d.first().locator('summary').click()}
async function save(page) {
  await page.locator('#calendar-modal-form button[type=submit]').click()
  await expect(page.locator('#calendar-modal')).toHaveCount(0)
}
async function create(page,title,{date=today,type='Aktivitet',weekly=false,weekdays=false}={}) {
  await openCreate(page)
  await page.locator('#calendar-title').fill(title);await page.locator('#calendar-date').fill(date)
  await page.locator('#calendar-type').selectOption(type);await expandTaskAdvanced(page)
  if(weekly)await page.locator('[name=repeatWeekly]').check()
  if(weekdays)await page.locator('[name=weekdays]').check()
  await save(page)
}
const close=page=>page.locator('#calendar-modal-close').click()
try {
  const created=await must(admin.auth.admin.createUser({email,password,email_confirm:true}));uid=created.user.id
  const household=await must(admin.from('households').insert({name:'Mega 2 acceptance',created_by:uid}).select('id').single());hid=household.id
  await must(admin.from('household_members').insert({household_id:hid,user_id:uid,role:'owner'}))
  const people=await must(admin.from('household_people').insert([
    {household_id:hid,name:'Ida',role:'child',color:'#f59e0b'},
    {household_id:hid,name:'Carl',role:'child',color:'#22c55e'},
  ]).select('*'))
  const ida=people.find(p=>p.name==='Ida'), carl=people.find(p=>p.name==='Carl')
  const wall=await newPage(1800), phone=await newPage(390)
  await expect(wall.locator('.week-grid')).toBeVisible();pass('Desktop calendar opens in week view')
  await expect(phone.locator('.day-view')).toBeVisible();pass('Mobile calendar opens in day view')
  await expect(wall.locator('#calendar-heading-label')).toContainText('Denne uge · uge 40')
  await wall.locator('#calendar-next-button').click()
  await expect(wall.locator('#calendar-heading-label')).toHaveText('Uge 41 · 5.–11. oktober')
  await wall.locator('#calendar-prev-button').click()
  await expect(wall.locator('#calendar-heading-label')).toContainText('Denne uge')
  await phone.locator('#calendar-next-button').click()
  await expect(phone.locator('#calendar-heading-label')).toContainText('tirsdag')
  await phone.locator('#calendar-prev-button').click()
  await expect(phone.locator('#calendar-heading-label')).toContainText('mandag')
  pass('Day/week navigation and ISO week labels')
  for(const page of [wall,phone]){await page.locator('#calendar-next-button').click();await page.locator('#calendar-today-button').click()}
  await expect(wall.locator('.day-card.is-today')).toHaveAttribute('data-day',today)
  await expect(phone.locator('.day-card')).toHaveAttribute('data-day',today);pass('Today on desktop/mobile and today highlight')
  await openCreate(wall);await wall.locator('#calendar-date').fill('2026-10-01');await expect(wall.locator('#calendar-date')).toHaveValue('2026-10-01');await close(wall)
  await phone.locator('#calendar-next-button').click();await openCreate(phone)
  await expect(phone.locator('#calendar-date')).toHaveValue('2026-09-29');await close(phone);await phone.locator('#calendar-today-button').click()
  pass('Global creation preserves selected mobile date; desktop date can be selected in the editor')
  await toggleView(phone);await phone.reload()
  await expect(phone.locator('.week-grid')).toBeVisible()
  await toggleView(phone);await phone.setViewportSize({width:1800,height:900})
  await expect(phone.locator('.day-view')).toBeVisible();await phone.reload()
  await expect(phone.locator('.day-view')).toBeVisible();await phone.setViewportSize({width:390,height:900})
  pass('Explicit view survives reload and viewport changes')
  await create(phone,'Shared live event')
  await expect(card(wall,'Shared live event')).toBeVisible({timeout:12000})
  pass('Realtime create from phone to wall without refresh')
  await wall.locator('[data-person-filter="'+ida.id+'"]').click()
  await expect(card(wall,'Shared live event')).toBeVisible()
  pass('Individual person filter retains Alle events')
  await openCreate(wall)
  await wall.locator('#calendar-title').fill('Multi-person full editor')
  await wall.locator('[name=people][value="'+ida.id+'"]').check()
  await wall.locator('[name=people][value="'+carl.id+'"]').check()
  await wall.locator('#calendar-time').fill('10:15')
  await wall.locator('#calendar-duration').fill('45')
  await wall.locator('#calendar-location').fill('Sports hall')
  await wall.locator('#calendar-note').fill('Remember bag')
  await save(wall)
  await expect(card(wall,'Multi-person full editor')).toContainText(/Ida, Carl|Carl, Ida/)
  await expect(card(wall,'Multi-person full editor')).toHaveCSS('border-left-color','rgb(100, 116, 139)')
  await wall.locator('[data-person-filter="'+carl.id+'"]').click()
  await expect(card(wall,'Multi-person full editor')).toBeVisible()
  await card(wall,'Multi-person full editor').click()
  await expect(wall.locator('#calendar-duration')).toHaveValue('45')
  await expect(wall.locator('#calendar-location')).toHaveValue('Sports hall')
  await expect(wall.locator('#calendar-note')).toHaveValue('Remember bag')
  await wall.locator('#calendar-title').fill('Multi edited');await save(wall)
  await card(wall,'Multi edited').click();await wall.locator('#calendar-modal-delete').click()
  await expect(card(wall,'Multi edited')).toHaveCount(0)
  pass('Manual create/edit/delete and complete multi-person editor')
  await must(admin.from('household_people').update({name:'Ida renamed'}).eq('id',ida.id))
  await expect(wall.locator('[data-person-filter="'+ida.id+'"]')).toContainText('Ida renamed',{timeout:12000})
  await expect(phone.locator('[data-person-filter="'+ida.id+'"]')).toContainText('Ida renamed')
  pass('Realtime people rename retains stable chip IDs')
  await wall.locator('[data-person-filter=Alle]').click()
  await wall.setViewportSize({width:390,height:900});await toggleView(wall) // Inline task completion uses the mobile day flow after Polish24.
  await create(wall,'Recurring task',{type:'Opgave',weekly:true})
  await card(wall,'Recurring task').locator('[data-calendar-toggle]').check();await unfold(wall)
  await expect(card(phone,'Recurring task').locator('[data-calendar-toggle]')).toBeChecked({timeout:12000})
  await nextWeek(wall)
  await expect(card(wall,'Recurring task').locator('[data-calendar-toggle]')).not.toBeChecked()
  await wall.locator('#calendar-today-button').click();await unfold(wall)
  await card(wall,'Recurring task').click()
  await expect(wall.locator('#calendar-title')).toHaveAttribute('list','task-suggestions')
  await expect(wall.locator('#task-suggestions option')).toHaveCount(8)
  await expect(wall.locator('[name=repeatScope][value=one]')).toBeChecked()
  await wall.locator('#calendar-title').fill('First override edited');await save(wall)
  await expect(card(wall,'First override edited').locator('[data-calendar-toggle]')).toBeChecked()
  await wall.reload();await expect(card(wall,'First override edited').locator('[data-calendar-toggle]')).toBeChecked()
  await nextWeek(wall)
  await expect(card(wall,'Recurring task').locator('[data-calendar-toggle]')).not.toBeChecked()
  pass('First-occurrence done persists, next week incomplete, existing override edits correctly, task suggestions')
  await card(wall,'Recurring task').click();await wall.locator('[name=repeatScope][value=series]').check()
  await expect(wall.locator('#calendar-date')).toHaveValue(today);await expect(wall.locator('#calendar-date')).toBeDisabled()
  await wall.locator('#calendar-title').fill('Whole renamed');await save(wall)
  await wall.locator('#calendar-today-button').click();await unfold(wall)
  await expect(card(wall,'First override edited')).toBeVisible()
  await nextWeek(wall);await expect(card(wall,'Whole renamed')).toBeVisible()
  pass('Whole series preserves start and completed override history')
  await card(wall,'Whole renamed').click();await wall.locator('[name=repeatScope][value=future]').check()
  await wall.locator('#calendar-title').fill('Future renamed');await save(wall)
  await expect(card(wall,'Future renamed')).toBeVisible()
  await nextWeek(wall);await expect(card(wall,'Future renamed')).toBeVisible()
  await card(wall,'Future renamed').click();await wall.locator('[name=repeatScope][value=one]').check()
  await wall.locator('#calendar-modal-delete').click()
  await expect(card(wall,'Future renamed')).toHaveCount(0)
  await nextWeek(wall);await expect(card(wall,'Future renamed')).toBeVisible()
  await card(wall,'Future renamed').click();await wall.locator('[name=repeatScope][value=future]').check()
  await wall.locator('#calendar-modal-delete').click();await expect(card(wall,'Future renamed')).toHaveCount(0)
  await nextWeek(wall);await expect(card(wall,'Future renamed')).toHaveCount(0)
  await wall.locator('#calendar-today-button').click();await unfold(wall)
  await expect(card(wall,'First override edited')).toBeVisible()
  pass('Future split and only-this/future delete preserve previous occurrences')
  await unfold(wall);await card(wall,'First override edited').click();await wall.locator('[name=repeatScope][value=series]').check()
  await wall.locator('#calendar-modal-delete').click()
  await expect(card(wall,'First override edited')).toHaveCount(0)
  pass('Whole-series delete removes original base and overrides')
  await wall.setViewportSize({width:1800,height:900});await toggleView(wall)
  await create(wall,'Every weekday',{weekdays:true})
  await expect(wall.locator('[data-calendar-item]').filter({hasText:'Every weekday'})).toHaveCount(5)
  await create(wall,'Weekly weekdays',{weekdays:true,weekly:true})
  await expect(wall.locator('[data-calendar-item]').filter({hasText:'Weekly weekdays'})).toHaveCount(5)
  await nextWeek(wall)
  await expect(wall.locator('[data-calendar-item]').filter({hasText:'Every weekday'})).toHaveCount(0)
  await expect(wall.locator('[data-calendar-item]').filter({hasText:'Weekly weekdays'})).toHaveCount(5)
  pass('Five weekdays and five weekly weekday series')
  await wall.locator('#calendar-today-button').click()
  await toggleView(wall)
  const birthday=await must(admin.from('calendar_items').insert({household_id:hid,created_by:uid,title:'Birthday child',date:'2020-09-28',type:'Fødselsdag',data:{birthYear:2010,repeatYearly:true}}).select().single())
  await expect(card(wall,'Birthday child bliver 16 år')).toBeVisible({timeout:12000})
  await expect(card(wall,'Birthday child').locator('.calendar-birthday-flag')).toBeVisible()
  await wall.clock.setFixedTime(new Date('2027-09-28T12:00:00+02:00'));await wall.locator('#calendar-today-button').click()
  await expect(card(wall,'Birthday child bliver 17 år')).toBeVisible()
  await card(wall,'Birthday child').click();await expect(wall.locator('#calendar-date')).toHaveValue('2020-09-28')
  await close(wall)
  expect((await must(admin.from('calendar_items').select('id').eq('id',birthday.id))).length).toBe(1)
  pass('Yearly birthday age, flag and safe base editor without physical yearly rows')
  await wall.clock.setFixedTime(new Date('2026-12-25T12:00:00+01:00'));await wall.locator('#calendar-today-button').click()
  await expect(card(wall,'1. juledag').locator('.calendar-milestone-star')).toBeVisible()
  await card(wall,'1. juledag').click();await expect(wall.locator('#calendar-modal-form button[type=submit]')).toHaveCount(0);await close(wall)
  pass('Virtual milestones use gold star and source-controlled viewer')
  await wall.clock.setFixedTime(new Date('2026-09-28T12:00:00+02:00'));await wall.locator('#calendar-today-button').click()
  for(const source of ['aula','google','ics']) {
    const row=await must(admin.from('calendar_items').insert({household_id:hid,created_by:uid,title:'Imported '+source,date:today,type:'Aktivitet',
      person_ids:[ida.id],person:'Ida',source,external_id:randomUUID(),data:{repeatWeekly:true,people:['Ida']}}).select().single())
    await expect(card(wall,'Imported '+source)).toBeVisible({timeout:12000})
    await expect(card(wall,'Imported '+source)).toContainText('Ida renamed')
    await expect(card(wall,'Imported '+source).locator('.calendar-source-badge')).toHaveText({aula:'Aula',google:'Google',ics:'ICS'}[source])
    await expect(card(wall,'Imported '+source).locator('.calendar-repeat-label')).toHaveCount(0)
    await card(wall,'Imported '+source).click()
    await expect(wall.locator('#calendar-title')).toBeDisabled()
    await expect(wall.locator('[name=repeatScope]')).toHaveCount(0)
    await expect(wall.locator('#calendar-modal-delete')).toHaveCount(0);await close(wall)
    expect(row.id).toBeTruthy()
  }
  await nextWeek(wall)
  await expect(wall.locator('[data-calendar-item]').filter({hasText:'Imported'})).toHaveCount(0)
  await wall.locator('#calendar-today-button').click()
  pass('Aula/Google/ICS source, stable person color, concrete occurrences and read-only editor')
  const feed=await must(admin.from('calendar_feeds').insert({household_id:hid,name:'Fixture ICS',source:'ics',feed_url:'https://example.invalid/calendar.ics',is_active:true}).select().single())
  await must(admin.from('calendar_feeds').update({is_active:false}).eq('id',feed.id))
  await must(admin.from('calendar_feeds').delete().eq('id',feed.id))
  await expect(card(wall,'Imported ics')).toBeVisible()
  pass('Inactive/deleted feeds do not break imported UI')
  await card(wall,'Shared live event').click()
  await wall.locator('#calendar-title').fill('Unsaved wall draft')
  await wall.locator('#calendar-title').evaluate(input=>input.dataset.retained='yes')
  await create(phone,'Live while editing')
  await expect(card(wall,'Live while editing')).toBeVisible({timeout:12000})
  await expect(wall.locator('#calendar-title')).toHaveValue('Unsaved wall draft')
  await expect(wall.locator('#calendar-title')).toHaveAttribute('data-retained','yes')
  await expect(wall.locator('#calendar-title')).toBeFocused()
  await card(phone,'Shared live event').click();await phone.locator('#calendar-title').fill('Edited on phone');await save(phone)
  await expect(card(wall,'Edited on phone')).toBeVisible({timeout:12000})
  await wall.locator('#calendar-modal-form button[type=submit]').click()
  await expect(wall.locator('#calendar-editor-message')).toContainText('ændret på en anden enhed')
  await expect(wall.locator('#calendar-title')).toHaveValue('Unsaved wall draft')
  await close(wall)
  await card(phone,'Edited on phone').click();await phone.locator('#calendar-modal-delete').click()
  await expect(card(wall,'Edited on phone')).toHaveCount(0,{timeout:12000})
  pass('Realtime preserves unsaved modal DOM, rejects stale edits and propagates delete')
  await create(phone,'Long '+('aftale '.repeat(30)))
  await openCreate(phone)
  await phone.locator('#calendar-type').selectOption('Opgave');await expandTaskAdvanced(phone)
  await expect(phone.locator('#calendar-title')).toHaveAttribute('list','task-suggestions')
  await expect(phone.locator('#calendar-duration')).toBeVisible()
  expect(await phone.locator('.calendar-modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)
  mkdirSync('supabase/.temp/mega2',{recursive:true})
  await phone.screenshot({path:'supabase/.temp/mega2/mobile-editor.png'})
  await close(phone);await wall.screenshot({path:'supabase/.temp/mega2/desktop-calendar.png',fullPage:true})
  expect(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  pass('Mobile editor touch layout, overflow and long title; desktop/mobile screenshots')
  for(const page of [phone,wall]){await logout(page);await expect(page.locator('#login-form')).toBeVisible()}
  await must(admin.from('calendar_items').insert({household_id:hid,created_by:uid,title:'After logout',date:today}))
  await expect(wall.locator('[data-calendar-item]')).toHaveCount(0)
  expect(errors).toEqual([])
  pass('Logout clears household data; no browser exceptions throughout')
  console.log('MEGA2 BROWSER: '+checks+' acceptance checks passed')
} finally {
  await browser.close()
  if(hid)await must(admin.from('households').delete().eq('id',hid))
  if(uid)await must(admin.auth.admin.deleteUser(uid))
}
