import {chromium,expect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {mkdirSync,writeFileSync} from 'node:fs'
import {localSupabase} from '../../scripts/local-supabase.mjs'
import {routeTo,openCreate,openSettings} from './browser-actions.mjs'
const local=localSupabase(),admin=createClient(local.API_URL,local.SERVICE_ROLE_KEY,{auth:{persistSession:false}})
const root='http://127.0.0.1:5178',out='supabase/.temp/polish24',today='2026-10-05'
mkdirSync(out,{recursive:true})
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1440,height:900},timezoneId:'Europe/Copenhagen'})
page.setDefaultTimeout(12000)
const errors=[],results=[],shots=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept())
await page.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort())
const must=async q=>{const r=await q;if(r.error)throw Error(r.error.message);return r.data},pass=label=>{results.push(label);console.log('PASS '+results.length+': '+label)}
const shot=async name=>{await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:out+'/'+name+'.png',fullPage:false});shots.push(name)}
const fits=async()=>{await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(page.locator('.product-nav')).toBeInViewport()}
let uid,hid,mealId
try{
 const email='polish-'+randomUUID()+'@example.test',password=randomUUID()+'!Aa1'
 uid=(await must(admin.auth.admin.createUser({email,password,email_confirm:true}))).user.id
 hid=(await must(admin.from('households').insert({name:'Familien Tandrup Jakobsen',created_by:uid}).select('id').single())).id
 await must(admin.from('household_members').insert({household_id:hid,user_id:uid,role:'owner'}))
 const people=await must(admin.from('household_people').insert(['Carl','Ida','Jakob','Far','Mor'].map((name,i)=>({household_id:hid,name,role:i<3?'child':'adult',color:['#7b9365','#b97758','#648794'][i%3]}))).select('*'))
 const carl=people[0],ida=people[1],jakob=people[2]
 const feed=await must(admin.from('calendar_feeds').insert({household_id:hid,name:'Familiens Google',source:'google',feed_url:'https://calendar.google.com/fixture.ics'}).select('*').single())
 const seed=(title,type='Aktivitet',extra={})=>({id:randomUUID(),household_id:hid,created_by:uid,title,type,date:today,time:'',person:'Alle',person_ids:[],done:false,data:{},...extra})
 const imported=seed('Carl spejder','Aktivitet',{time:'16:00',person:'Carl',person_ids:[carl.id],source:'google',calendar_id:feed.id,external_id:'polish-google-fixture',location:'Spejderhytten',note:'Husk drikkedunk og en varm trøje.',data:{uid:'polish-series',recurrenceId:'2026-10-05T14:00:00.000Z'}})
 const task=seed('Tøm tasken','Opgave',{person:'Ida',person_ids:[ida.id],data:{rewardMode:'stars',starValue:10}})
 await must(admin.from('calendar_items').insert([imported,task,seed('Fodboldtræning','Fritidsinteresse',{time:'17:30',person:'Jakob',person_ids:[jakob.id],location:'Stadion'}),seed('Pasta med tomater','Madplan',{note:'Pasta\nTomater'}),seed('Forældremøde','Aktivitet',{date:'2026-10-06',time:'19:00'}),seed('Kylling i karry','Madplan',{date:'2026-10-06'}),seed('Lasagne','Madplan',{date:'2026-10-08'}),seed('Svømning','Fritidsinteresse',{date:'2026-10-07',time:'16:00',person:'Ida',person_ids:[ida.id]}),seed('Mors fødselsdag','Fødselsdag',{date:'2026-10-11'}),seed('Familiebrunch','Aktivitet',{date:'2026-10-10',time:'10:00'}),seed('Mælk','Indkøb',{note:'2 liter',location:'Mejeri & æg'}),seed('Æbler','Indkøb',{note:'6 stk.',location:'Frugt & grønt'}),seed('Brød','Indkøb',{location:'Brød & kolonial'})]))
 // Verify the actual authenticated local Edge runtime in addition to deterministic browser recipe fixtures.
 const client=createClient(local.API_URL,local.ANON_KEY,{auth:{persistSession:false}});await must(client.auth.signInWithPassword({email,password}));const edge=await client.functions.invoke('recipe-preview',{body:{url:'https://example.com'}});if(edge.error)throw Error('Local recipe Edge smoke failed: '+(await edge.error.context?.text()||edge.error.message));expect(edge.data.recipe.title).toContain('Example');pass('Actual local recipe Edge authenticates, fetches a public HTTPS page with pinned DNS and returns metadata')
 const forbidden=await client.functions.invoke('recipe-preview',{body:{url:'http://127.0.0.1'}});expect(forbidden.error).toBeTruthy();pass('Actual local Edge rejects private URL')
 await page.route('**/functions/v1/recipe-preview',async r=>{const url=r.request().postDataJSON()?.url;if(url?.includes('failure'))return r.fulfill({status:422,contentType:'application/json',body:JSON.stringify({error:'RECIPE_UNAVAILABLE'})});await r.fulfill({contentType:'application/json',body:JSON.stringify({recipe:{title:'Pasta med grønt',url:'https://example.com/recipe',site:'Mad til familien',image:'',ingredients:['500 g pasta','Tomater','Basilikum'],instructions:['Kog pastaen i saltet vand.','Vend tomater og basilikum i.','Servér med familien.'],format:'jsonld'}})})})
 await page.clock.setFixedTime(new Date('2026-10-05T08:00:00+02:00'));await page.goto(root);await page.locator('#email').fill(email);await page.locator('#password').fill(password);await page.locator('#login-form button[type=submit]').click();await expect(page.locator('.product-nav')).toBeVisible()
 await routeTo(page,'today');await fits();await shot('desktop-today');await expect(page.locator('#person-chipbar')).toBeVisible();await expect(page.locator('#logout-button,#household-switch')).toHaveCount(0)
 const nav=await page.locator('.product-nav').boundingBox();expect(nav.x).toBeGreaterThan(200);expect(nav.width).toBeLessThan(750);expect(nav.y).toBeGreaterThan(750);pass('Compact desktop header, centered floating dock, no sidebar or redundant account/household controls')
 await routeTo(page,'calendar');await expect(page.locator('.week-grid>.day-card')).toHaveCount(7);expect(await page.locator('.week-grid>.day-card').evaluateAll(els=>new Set(els.map(e=>Math.round(e.getBoundingClientRect().top))).size)).toBe(1);await expect(page.locator('.week-grid .calendar-birthday-flag')).toBeVisible();await shot('desktop-calendar-normal')
 const day=page.locator('.week-grid>[data-day="'+today+'"]');await expect(day.locator('.compact-task')).toHaveCount(1);await expect(day.locator('[data-reward-action]')).toHaveCount(0);expect(await day.locator('.day-sections').evaluate(e=>e.lastElementChild.classList.contains('day-meals'))).toBe(true);await expect(day.locator('.calendar-item-footer')).toHaveCount(0);pass('Seven simultaneous days, compact tasks, details hidden from week cards, meal last')
 await day.locator('[data-task-detail]').click();await expect(page.locator('.reward-modal')).toContainText('Tøm tasken');await expect(page.locator('.reward-modal').getByRole('button',{name:'Udfør Tøm tasken',exact:true})).toBeVisible();await page.keyboard.press('Escape');pass('Compact task opens existing reward actions')
 await page.locator('[data-person-filter="'+carl.id+'"]').click();await expect(day.locator('.compact-task')).toHaveCount(0);await expect(day.locator('[data-calendar-item="'+imported.id+'"]')).toBeVisible();await page.locator('[data-person-filter=Alle]').click()
 for(const route of ['meals','shopping','family','tasks','today']){await routeTo(page,route);await expect(page.locator('#person-chipbar')).toHaveCount(['tasks','today'].includes(route)?1:0)}pass('Person chips filter content and only appear on Today, Calendar and Tasks')
 await routeTo(page,'calendar');await day.locator('[data-calendar-item="'+imported.id+'"]').click();await expect(page.locator('.imported-editor')).toContainText('Ændringer her gælder kun i Familiekalenderen');await shot('desktop-imported-google-editor');await page.locator('#import-name').fill('Carl spejder · husk drikkedunk');await page.locator('.import-people input[value="'+ida.id+'"]').check();await page.locator('.imported-editor .stack-form button[type=submit]').click();await page.locator('[data-scope-confirm]').click();await expect(page.locator('.imported-editor')).toHaveCount(0);await expect.poll(async()=>(await must(admin.from('calendar_items').select('person_ids').eq('id',imported.id).single())).person_ids.length).toBe(2);pass('Imported editor saves local title and multi-person assignment')
 await day.locator('[data-calendar-item="'+imported.id+'"]').click();await page.locator('[data-import-hide]').click();await expect(page.locator('[data-hide-scope=occurrence]')).toBeVisible();await expect(page.locator('[data-hide-scope=series]')).toBeVisible();await shot('desktop-imported-scope-dialog');await page.keyboard.press('Escape')
 const dense=await must(admin.from('calendar_items').insert([...Array.from({length:8},(_,i)=>seed('Ekstra aftale '+(i+1),'Aktivitet',{time:'1'+i+':00'})),...Array.from({length:5},(_,i)=>seed('Lille opgave '+(i+1),'Opgave',{person:'Carl',person_ids:[carl.id]}))]).select('id'));await page.reload();await routeTo(page,'calendar');await expect(day.locator('[data-day-detail]')).toBeVisible();await shot('desktop-calendar-dense');expect(await day.locator('.compact-activity,.compact-task').count()).toBeLessThanOrEqual(6);await day.locator('[data-day-detail]').click();await expect(page.locator('.full-day-detail .compact-task')).toHaveCount(6);await expect(page.locator('.full-day-detail')).toContainText('Ekstra aftale 8');await expect(page.locator('.full-day-detail .day-meals')).toHaveCount(1);await page.keyboard.press('Escape');pass('Dense week caps visible rows and opens complete day without growing columns')
 await routeTo(page,'meals');await fits();await shot('desktop-food');await openCreate(page,'meal');await page.locator('#recipe-url').fill('https://example.com/recipe');await page.locator('#recipe-fetch').click();await expect(page.locator('#plan-title')).toHaveValue('Pasta med grønt');await expect(page.locator('#plan-note')).toContainText('');expect(await page.locator('#plan-note').inputValue()).toContain('500 g pasta');await shot('desktop-recipe-import');await page.locator('#plan-form button[type=submit]').click();await expect(page.locator('#plan-modal')).toHaveCount(0)
 mealId=(await must(admin.from('calendar_items').select('id,data,recipe_id').eq('household_id',hid).eq('title','Pasta med grønt').single())).id;await page.locator('[data-meal-ingredients="'+mealId+'"]').click();await page.locator('#recipe-shopping-form button[type=submit]').click();await expect.poll(async()=>(await must(admin.from('calendar_items').select('id').eq('household_id',hid).eq('type','Indkøb'))).length).toBe(6);await routeTo(page,'shopping');await fits();await shot('desktop-shopping');expect(await page.locator('.shopping-row').first().evaluate(e=>e.getBoundingClientRect().height)).toBeLessThanOrEqual(44);pass('Recipe import persists structured ingredients/instructions; ingredients reach compact shopping rows')
 await routeTo(page,'meals');await openCreate(page,'meal');await page.locator('#recipe-url').fill('https://example.com/failure');await page.locator('#recipe-fetch').click();await expect(page.locator('#recipe-status')).toContainText('skriv den manuelt');await expect(page.locator('#plan-title')).toBeEditable();await page.keyboard.press('Escape');pass('Recipe fetch failure keeps manual editor usable')
 for(const [width,height] of [[375,667],[390,844],[430,932]]){
  await page.setViewportSize({width,height});await routeTo(page,'calendar');await page.locator('[data-calendar-view=week]').click();await fits();await expect(page.locator('.compact-task').first()).toBeVisible();await shot('mobile-calendar-'+width)
  for(const route of ['today','meals','shopping']){await routeTo(page,route);await fits();await expect(page.locator('#person-chipbar')).toHaveCount(route==='today'?1:0);await expect(page.locator('#new-calendar-button')).toBeInViewport();if(route!=='today')await shot('mobile-'+route+'-'+width);if(route==='shopping')expect(await page.locator('.shopping-row').first().evaluate(e=>e.getBoundingClientRect().height)).toBeLessThanOrEqual(50)}
  await routeTo(page,'meals');await openCreate(page,'meal');await page.locator('#recipe-url').fill('https://example.com/recipe');await page.locator('#recipe-fetch').click();await expect(page.locator('#plan-title')).toHaveValue('Pasta med grønt');await shot('mobile-recipe-import-'+width);await page.keyboard.press('Escape')
 }
 pass('375×667, 390×844, 430×932: mobile nav/FAB retained, compact shopping, scoped chips, recipe editor and no page overflow')
 await page.setViewportSize({width:1280,height:800});await openSettings(page,'device');await page.locator('#device-kiosk').check();await page.locator('#device-pin').fill('1948');await page.locator('#device-settings-form button[type=submit]').click();await expect(page.locator('body')).toHaveAttribute('data-mode','kiosk');await routeTo(page,'calendar')
 for(const [width,height] of [[1280,800],[1024,600],[1920,1080]]){await page.setViewportSize({width,height});await routeTo(page,'today');await routeTo(page,'calendar');await fits();await expect(page.locator('.week-grid>.day-card')).toHaveCount(7);expect(await page.locator('.week-grid .day-sections').evaluateAll(els=>els.filter(e=>e.scrollHeight>e.clientHeight+1).map(e=>({width:innerWidth,height:innerHeight,scroll:e.scrollHeight,client:e.clientHeight,content:e.textContent})))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1)).toBe(true);await expect(page.locator('#new-calendar-button')).toBeHidden();await shot('kiosk-week-'+width)}
 await page.locator('[data-plan-edit="'+mealId+'"]').first().click();await expect(page.locator('.recipe-modal')).toContainText('Ingredienser');await expect(page.locator('.recipe-modal')).toContainText('Fremgangsmåde');await expect(page.locator('.recipe-source')).toHaveAttribute('href','https://example.com/recipe');await expect(page.locator('#plan-form')).toHaveCount(0);await page.keyboard.press('Escape');pass('Kiosk fits without day scrollbars, tiny navigation, compact tasks, meals last; recipe view read-only')
 expect(errors).toEqual([]);pass('No uncaught browser startup/interaction errors')
 writeFileSync(out+'/results.json',JSON.stringify({results,shots,recipePreview:'Deterministic public recipe fixture in browser; actual local Edge fetch/auth/private URL smoke also passed.'},null,2))
 writeFileSync(out+'/review.html','<!doctype html><html lang="da"><meta charset="utf-8"><title>Product Polish 2.4</title><style>body{font:16px system-ui;background:#f4f5ef;margin:28px;color:#274b36}nav{display:flex;gap:12px;flex-wrap:wrap}section{margin:32px 0}img{max-width:100%;border:1px solid #bccab6;border-radius:12px}a{color:inherit}h2{font-size:18px}</style><h1>Product Polish 2.4 · lokal visuel review</h1><p>Isolerede testdata. Opskriftseditor viser en kontrolleret fixture; importfunktionens parsing og netværk er testet separat. Ingen production-ændringer.</p><nav>'+shots.map(n=>'<a href="#'+n+'">'+n+'</a>').join('')+'</nav>'+shots.map(n=>'<section id="'+n+'"><h2>'+n+'</h2><a href="'+n+'.png"><img loading="lazy" src="'+n+'.png" alt="'+n+'"></a></section>').join('')+'</html>')
 console.log('POLISH BROWSER PASS '+results.length+' checks, '+shots.length+' screenshots')
}catch(error){await page.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});throw error}
finally{await browser.close();if(hid)await admin.from('households').delete().eq('id',hid);if(uid)await admin.auth.admin.deleteUser(uid)}
