import test from 'node:test'
import assert from 'node:assert/strict'
import {compactDay,compactTask,compactMeals,filterRoutes} from '../src/lib/calendar-layout.js'
import {ingredientDrafts,planValues} from '../src/lib/household-plans.js'
import {visibleImports} from '../src/lib/imported-editor.js'
import {recipeDetails} from '../src/lib/recipe.js'
test('Dense weeks reserve space for hobbies/tasks, cap items and count overflow exactly',()=>{const items=[...Array.from({length:10},(_,i)=>({id:i,type:'Aktivitet'})),{id:'h',type:'Fritidsinteresse'},{id:'t',type:'Opgave'}];const result=compactDay(items,6);assert.equal(result.items.length,6);assert.equal(result.hidden,6);assert.ok(result.items.some(i=>i.id==='t'));assert.ok(result.items.some(i=>i.id==='h'))})
test('Week tasks expose compact details, with no inline administration',()=>{const html=compactTask({id:'one',title:'Tøm tasken'},{people:'Ida',reward:{mode:'stars',stars:10}});assert.match(html,/data-task-detail/);assert.match(html,/10 ⭐/);assert.doesNotMatch(html,/Fritag|Udf?r|data-reward-action/);assert.equal(compactMeals([]),'')})
test('Structured recipe stays editable, survives calendar values, feeds shopping dedupe',()=>{const values=planValues('meal',{title:'Pasta',date:'2026-10-05',recipeUrl:'https://example.com/recipe',ingredients:'Pasta\nTomater\nPasta',instructions:'Kog pasta\nTilsæt tomater'});assert.deepEqual(values.recipe.ingredients,['Pasta','Tomater','Pasta']);assert.deepEqual(ingredientDrafts(values.recipe.ingredients,[{title:'Tomater',type:'Indkøb',done:false}]).map(i=>i.title),['Pasta']);const edited=planValues('meal',{title:'Ny ret',date:'2026-10-05'},{id:'a',...values,data:{recipe:values.recipe}});assert.deepEqual(edited.recipe,values.recipe);assert.match(recipeDetails(values.recipe),/<ol>/);assert.throws(()=>planValues('meal',{title:'Ret',date:'2026-10-05',recipeUrl:'javascript:alert(1)'}))})
test('Only functional routes show people; imported tombstones do not remove manual lookalikes',()=>{assert.deepEqual(filterRoutes,['today','calendar','tasks']);assert.deepEqual(visibleImports([{id:'manual',title:'Carl spejder'},{id:'hidden',title:'Carl spejder',data:{importHidden:true}}]).map(i=>i.id),['manual'])})
