import {chromium,expect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {mkdirSync,writeFileSync} from 'node:fs'
import {fileURLToPath} from 'node:url'
import {localSupabase} from '../../scripts/local-supabase.mjs'
process.chdir(fileURLToPath(new URL('../../',import.meta.url)))
const local=localSupabase(),admin=createClient(local.API_URL,local.SERVICE_ROLE_KEY,{auth:{persistSession:false}})
const browser=await chromium.launch({executablePath:process.env.TEST_BROWSER_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true})
const email='mega4-'+randomUUID()+'@example.test',inviteEmail='invite-'+randomUUID()+'@example.test'
let password=randomUUID()+'!Aa1'
const invitePassword=randomUUID()+'!Aa1',users=[],households=[],errors=[],results=[]
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Copenhagen',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const dateAfter=offset=>{const d=new Date(today+'T12:00:00');d.setDate(d.getDate()+offset);return new Intl.DateTimeFormat('en-CA').format(d)}
const must=async q=>{const r=await q;if(r.error)throw Error(r.error.message);return r.data}
const pass=label=>{results.push(label);console.log('PASS '+results.length+': '+label)}
const card=(page,title)=>page.locator('.calendar-item').filter({has:page.locator('strong',{hasText:title})}).first()
const root='http://127.0.0.1:5178'
mkdirSync('supabase/.temp/mega4',{recursive:true})
async function pageAt(width,height=844) {
 const context=await browser.newContext({viewport:{width,height},timezoneId:'Europe/Copenhagen',permissions:['clipboard-read','clipboard-write']})
 const page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message))
 await page.route('**/*',route=>['localhost','127.0.0.1'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())
 return page
}
async function login(page,who=email,pw=password) {
 await page.locator('#email').fill(who);await page.locator('#password').fill(pw);await page.getByRole('button',{name:'Log ind',exact:true}).click()
}
async function settings(page,tab) {
 await page.locator('#settings-button').click();await page.locator('[data-settings-tab='+tab+']').click()
}
async function unlock(page,tab='device') {
 await page.locator('#settings-button').click();await expect(page.locator('#pin-modal')).toBeVisible()
 await page.locator('#kiosk-pin').fill('1948');await page.locator('#pin-form button[type=submit]').click()
 await page.locator('[data-settings-tab='+tab+']').click()
}
async function checkLayout(page,label) {
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),label+' page overflow').toBe(true)
 await expect(page.locator('.product-nav')).toBeVisible();await expect(page.locator('#new-calendar-button')).toBeInViewport()
 // Read layout atomically and retry if realtime replaces the navigation between checks.
 await expect.poll(()=>page.evaluate(()=>{const nav=document.querySelector('.product-nav')?.getBoundingClientRect();return Boolean(nav&&nav.width>0&&nav.x>=0&&nav.right<=innerWidth+1)}),{message:label+' navigation fits viewport'}).toBe(true)
 await page.screenshot({path:'supabase/.temp/mega4/'+label+'.png',fullPage:true})
}
let phone,wall,hid,uid,person
try {
 uid=(await must(admin.auth.admin.createUser({email,password,email_confirm:true}))).user.id;users.push(uid)
 const inviteUid=(await must(admin.auth.admin.createUser({email:inviteEmail,password:invitePassword,email_confirm:true}))).user.id;users.push(inviteUid)
 hid=(await must(admin.from('households').insert({name:'Familien Sommer',created_by:uid}).select('id').single())).id;households.push(hid)
 const hid2=(await must(admin.from('households').insert({name:'Sommerhuset',created_by:uid}).select('id').single())).id;households.push(hid2)
 await must(admin.from('household_members').insert([hid,hid2].map(household_id=>({household_id,user_id:uid,role:'owner'}))))
 person=(await must(admin.from('household_people').insert([{household_id:hid,name:'Ida',role:'child',color:'#f59e0b'},{household_id:hid,name:'Rasmus',role:'adult',color:'#2563eb'}]).select('*'))).find(p=>p.name==='Ida')
 const seed=(title,extra={})=>({id:randomUUID(),household_id:hid,created_by:uid,title,date:today,type:'Aktivitet',person:'Alle',person_ids:[],done:false,data:{},...extra})
 await must(admin.from('calendar_items').insert([
  seed('Svømning med hele familien og en ekstra lang titel',{time:'23:00',type:'Fritidsinteresse'}),
  seed('Tøm tasker',{type:'Opgave',person:'Ida',person_ids:[person.id]}),
  seed('Weekendtur',{date:dateAfter(2),time:'09:30'}),seed('Tandlæge',{date:dateAfter(1),time:'10:15'}),
  ...Array.from({length:6},(_,i)=>seed('Udført '+i,{type:'Opgave',done:true,person:'Ida',person_ids:[person.id]}))
 ]))
 await must(admin.from('calendar_feeds').insert({household_id:hid,source:'ics',name:'Skole',feed_url:'https://example.invalid/private-TEST_ONLY.ics',is_active:true}))
 phone=await pageAt(390);await phone.goto(root)
 await phone.locator('[data-auth-screen=reset]').click();await phone.locator('#email').fill(email)
 await phone.locator('#reset-form button').click();await expect(phone.locator('#message')).toContainText('har vi sendt et link')
 pass('Forgot-password request uses local callback and generic response')
 let mail
 await expect.poll(async()=>{
  const response=await fetch('http://127.0.0.1:59324/api/v1/messages'),body=await response.json()
  mail=body.messages?.find(row=>row.To?.some(to=>to.Address===email));return Boolean(mail)
 },{timeout:15000}).toBe(true)
 const contents=await (await fetch('http://127.0.0.1:59324/api/v1/message/'+mail.ID)).json()
 const link=contents.HTML.match(/href="([^"]+)"/)?.[1]?.replaceAll('&amp;','&')
 expect(link).toBeTruthy();await phone.goto(link)
 await expect(phone.locator('#recovery-form')).toBeVisible()
 password=randomUUID()+'!Bb2'
 await phone.locator('#new-password').fill(password);await phone.locator('#repeat-password').fill(password)
 await phone.locator('#recovery-form button').click();await expect(phone.locator('#settings-button')).toBeVisible()
 pass('Actual local recovery email opens callback and updates password')
 await expect(phone.locator('body')).toHaveAttribute('data-mode','mobile')
 await expect(phone.locator('.product-nav button')).toHaveCount(4)
 await expect(phone.locator('.day-view')).toBeVisible()
 pass('Mobile four destinations and day default')
 await phone.locator('[data-quick-type=Opgave]').first().click()
 await expect(phone.locator('#calendar-type')).toHaveValue('Opgave')
 await phone.locator('#calendar-title').fill('Ny mobilopgave')
 const adult=(await must(admin.from('household_people').select('id').eq('household_id',hid).eq('name','Rasmus').single())).id
 await phone.locator('[name=people][value="'+adult+'"]').check()
 const box=await phone.locator('.calendar-modal').boundingBox();expect(box.width).toBe(390)
 await phone.locator('#calendar-note').fill('En note til familien')
 await phone.locator('#calendar-modal-form button[type=submit]').click();await expect(phone.locator('#calendar-modal')).toHaveCount(0)
 await expect(card(phone,'Ny mobilopgave')).toBeVisible()
 pass('Mobile quick-create opens full-screen editor and saves')
 await phone.locator('[data-product-route=tasks]').click()
 await card(phone,'Ny mobilopgave').locator('[data-calendar-toggle]').check()
 await expect(phone.locator('#calendar-modal')).toHaveCount(0)
 await expect(phone.locator('.task-view details')).toBeVisible()
 await phone.locator('[data-task-range=week]').click();await expect(phone.locator('[data-task-range=week]')).toHaveAttribute('aria-pressed','true')
 pass('Task destination quick-completes, groups week and folds completed')
 await settings(phone,'people')
 await phone.locator('[data-archive-person="'+person.id+'"]').click()
 await expect(phone.locator('[data-archive-person="'+person.id+'"]')).toHaveText('Gendan')
 expect((await must(admin.from('calendar_items').select('id').eq('household_id',hid))).length).toBe(11)
 await phone.locator('[data-archive-person="'+person.id+'"]').click()
 await expect(phone.locator('[data-archive-person="'+person.id+'"]')).toHaveText('Arkivér')
 await phone.locator('#person-'+person.id+'-reward-enabled').check()
 await phone.locator('[data-save-person="'+person.id+'"]').click()
 await expect.poll(async()=>(await must(admin.from('household_people').select('reward_enabled').eq('id',person.id).single())).reward_enabled).toBe(true)
 await expect(phone.locator('.message').filter({hasText:'Person gemt.'})).toBeVisible()
 pass('Person archive retains history; restore and reward setting persist')
 await phone.locator('[data-settings-tab=feeds]').click()
 await expect(phone.locator('.calendar-feed-url')).toHaveText('example.invalid/…')
 expect(await phone.locator('[data-settings-panel=feeds]').innerHTML()).not.toContain('private-TEST_ONLY')
 await phone.locator('[data-copy-calendar-feed]').click()
 expect(await phone.evaluate(()=>navigator.clipboard.readText())).toContain('private-TEST_ONLY')
 await phone.locator('[data-edit-calendar-feed]').click();await expect(phone.locator('#calendar-feed-url')).toHaveValue(/private-TEST_ONLY/)
 pass('Private feed masked by default; explicit copy and edit work')
 await phone.locator('#calendar-feed-cancel').click();await phone.locator('[data-settings-tab=family]').click()
 await expect(phone.locator('#family-admin-content')).toContainText(email)
 await phone.locator('#invite-email').fill(inviteEmail);await phone.locator('#invite-form button[type=submit]').click()
 await expect(phone.locator('#new-invite-link')).toBeVisible();const invitation=await phone.locator('#new-invite-link').inputValue()
 await phone.locator('#copy-invite').click();expect(await phone.evaluate(()=>navigator.clipboard.readText())).toBe(invitation)
 const invited=await pageAt(430);await invited.goto(invitation);expect(invited.url()).not.toContain('#invite')
 await login(invited,inviteEmail,invitePassword);await invited.locator('#accept-invite').click()
 await expect(invited.locator('#settings-button')).toBeVisible();await invited.locator('[data-product-route=family]').click()
 await expect(invited.locator('#family-admin-content')).toContainText(inviteEmail);await expect(invited.locator('#invite-form')).toHaveCount(0)
 await expect(invited.locator('[data-settings-panel=family]')).toContainText('Kun ejer')
 pass('Email-bound invitation joins correct household; adult cannot administer invitations')
 await phone.locator('#invite-email').fill('revoke-'+randomUUID()+'@example.test');await phone.locator('#invite-form button[type=submit]').click()
 await expect(phone.locator('#invite-form button[type=submit]')).toBeEnabled()
 await expect(phone.locator('#family-admin-content')).toContainText('revoke-')
 await expect(phone.locator('[data-revoke-invite]')).toHaveCount(1)
 await phone.locator('[data-revoke-invite]').click();await expect(phone.locator('#family-admin-content')).toContainText('Tilbagekaldt')
 pass('Owner can revoke pending invitation')
 await phone.locator('[data-settings-tab=appearance]').click();await phone.locator('#appearance-accent').selectOption('#2563eb')
 await phone.locator('#appearance-tone').selectOption('warm');await phone.locator('#appearance-form button').click()
 await phone.locator('#settings-modal-close').click();await phone.reload()
 await expect(phone.locator('body')).toHaveAttribute('data-mode','mobile')
 expect(await phone.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent'))).toBe('#2563eb')
 pass('Curated appearance persists per device and household')
 wall=await pageAt(1920,1080);await wall.addInitScript(()=>Object.defineProperty(navigator,'wakeLock',{value:undefined,configurable:true}));await wall.goto(root);await login(wall);await expect(wall.locator('#settings-button')).toBeVisible()
 await settings(wall,'device');await wall.locator('#device-kiosk').check();await wall.locator('#device-pin').fill('1948')
 await wall.locator('#device-wake').check()
 await wall.locator('#shortcut-homey').fill('https://homey.app/');await wall.locator('#device-settings-form button[type=submit]').click()
 await expect(wall.locator('body')).toHaveAttribute('data-mode','kiosk');await expect(wall.locator('#device-clock')).toContainText(/\d/)
 await expect(wall.locator('.kiosk-shortcuts a')).toHaveCount(1);await expect(wall.locator('.upcoming-panel .upcoming-event')).toHaveCount(2)
 await wall.reload();await expect(wall.locator('body')).toHaveAttribute('data-mode','kiosk')
 await expect(wall.locator('.kiosk-heading')).toContainText('Familien Sommer')
 pass('Explicit kiosk and selected household survive reload with configured shortcuts and upcoming events')
 await wall.locator('#settings-button').click();await wall.locator('#kiosk-pin').fill('0000');await wall.locator('#pin-form button[type=submit]').click()
 await expect(wall.locator('#pin-message')).toContainText('Forkert');await expect(wall.locator('#settings-modal')).toHaveCount(0)
 await wall.keyboard.press('Escape');await expect(wall.locator('#pin-modal')).toHaveCount(0)
 pass('Kiosk settings reject wrong PIN; Escape closes lock without exiting kiosk')
 await unlock(wall);await expect(wall.locator('#wake-status')).toContainText('Ikke understøttet');await wall.locator('#settings-modal-close').click()
 pass('Wake-lock consent survives reload; unsupported browser uses quiet fallback')
 await card(wall,'Tøm tasker').locator('[data-calendar-toggle]').check()
 await expect(wall.locator('#celebration-title')).toHaveText('Superstjerne')
 await wall.screenshot({path:'supabase/.temp/mega4/kiosk-celebration.png'})
 await wall.keyboard.press('Escape');await expect(wall.locator('#celebration-title')).toHaveCount(0)
 pass('Kiosk task completion displays and dismisses exactly-once celebration')
 for(const [width,height] of [[1024,600],[1024,768],[1280,800],[1920,1080]]){
  await wall.setViewportSize({width,height});await wall.locator('[data-product-route=calendar]').click()
  await expect(wall.locator('.week-grid .day-card')).toHaveCount(7)
  const boxes=await wall.locator('.week-grid .day-card').evaluateAll(els=>els.map(el=>({x:el.getBoundingClientRect().x,right:el.getBoundingClientRect().right,top:el.getBoundingClientRect().top})))
  expect(boxes.every(b=>b.x>=0&&b.right<=width+1&&Math.abs(b.top-boxes[0].top)<2)).toBe(true)
  await checkLayout(wall,'kiosk-'+width+'x'+height)
 }
 pass('Kiosk seven-day week fits all four required wall sizes without horizontal scroll')
 for(const [width,height] of [[375,667],[390,844],[430,932],[768,1024],[820,1180],[1366,768],[1440,900]]){
  await phone.setViewportSize({width,height});await phone.locator('[data-product-route=calendar]').click()
  await checkLayout(phone,'calendar-'+width+'x'+height)
  await phone.locator('#new-calendar-button').click();await phone.locator('#calendar-note').fill('Lang kladde')
  expect(await phone.locator('.calendar-modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)
  await phone.locator('#calendar-modal-form button[type=submit]').scrollIntoViewIfNeeded()
  await expect(phone.locator('#calendar-modal-form button[type=submit]')).toBeInViewport()
  await phone.screenshot({path:'supabase/.temp/mega4/editor-'+width+'x'+height+'.png'})
  await phone.keyboard.press('Escape');await expect(phone.locator('#calendar-modal')).toHaveCount(0)
  await expect(phone.locator('#new-calendar-button')).toBeFocused()
  await settings(phone,'people')
  expect(await phone.locator('.settings-modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)
  await phone.screenshot({path:'supabase/.temp/mega4/settings-'+width+'x'+height+'.png'})
  await phone.keyboard.press('Escape')
 }
 pass('Seven mobile/tablet/desktop sizes: navigation, editor save, settings, no horizontal overflow and focus return')
 await phone.setViewportSize({width:390,height:844});await phone.locator('[data-product-route=calendar]').click()
 await phone.locator('#calendar-toggle-view-button').click();await expect(phone.locator('.week-grid .day-card')).toHaveCount(7)
 const positions=await phone.locator('.week-grid .day-card').evaluateAll(els=>els.map(el=>el.getBoundingClientRect().top))
 expect(positions.every((y,i)=>i===0||y>positions[i-1])).toBe(true)
 await phone.screenshot({path:'supabase/.temp/mega4/mobile-week.png',fullPage:true})
 pass('Mobile week is a readable vertical seven-day list')
 await phone.locator('#new-calendar-button').click();await phone.locator('#calendar-note').fill('Kladde med tastatur')
 await phone.setViewportSize({width:390,height:420});await phone.locator('#calendar-modal-form button[type=submit]').scrollIntoViewIfNeeded()
 await expect(phone.locator('#calendar-modal-form button[type=submit]')).toBeInViewport();await expect(phone.locator('#calendar-note')).toHaveValue('Kladde med tastatur')
 await phone.locator('#calendar-modal-close').focus();await phone.keyboard.press('Shift+Tab');await expect(phone.locator('#calendar-modal-form button[type=submit]')).toBeFocused()
 await phone.keyboard.press('Tab');await expect(phone.locator('#calendar-modal-close')).toBeFocused();await phone.keyboard.press('Escape');await phone.setViewportSize({width:390,height:844})
 pass('Reduced visual viewport keeps save reachable and draft intact; modal traps keyboard focus')
 await wall.clock.install({time:new Date()});await wall.locator('[data-product-route=tasks]').click()
 await wall.clock.setSystemTime(new Date(Date.now()+16*60000));await wall.clock.runFor(1100)
 await expect(wall.locator('[data-product-route=today]')).toHaveAttribute('aria-current','page')
 await wall.locator('#new-calendar-button').click();await wall.locator('#calendar-title').fill('Bevar denne kladde')
 await wall.clock.setSystemTime(new Date(Date.now()+33*60000));await wall.clock.runFor(1100)
 await expect(wall.locator('#calendar-title')).toHaveValue('Bevar denne kladde');await wall.keyboard.press('Escape')
 pass('Kiosk inactivity returns to Today and never discards an active editor draft')
 const midnight=new Date();midnight.setDate(midnight.getDate()+1);midnight.setHours(0,0,1,0)
 await wall.clock.setSystemTime(midnight);await wall.clock.runFor(1100)
 await expect(wall.locator('.day-card.is-today')).toHaveAttribute('data-day',dateAfter(1))
 await wall.clock.setSystemTime(new Date());await wall.clock.runFor(1100)
 pass('Kiosk midnight rollover refreshes visible day without reload')
 await unlock(wall,'account');await wall.locator('#account-logout').click();await expect(wall.locator('#login-form')).toBeVisible()
 expect(await wall.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes('auth-token')))).toHaveLength(0)
 await login(wall);await expect(wall.locator('body')).toHaveAttribute('data-mode','kiosk')
 await expect(wall.locator('.kiosk-heading')).toContainText('Familien Sommer')
 pass('Logout clears Auth and cached session; explicit kiosk binding restores after re-login')
 await unlock(wall);await wall.locator('#exit-kiosk').click();await expect(wall.locator('body')).toHaveAttribute('data-mode','desktop')
 await wall.reload();await expect(wall.locator('body')).toHaveAttribute('data-mode','desktop')
 pass('Authenticated PIN-protected exit persists across reload')
 expect(errors).toEqual([])
 pass('No uncaught browser exceptions through all product flows')
 writeFileSync('supabase/.temp/mega4/browser-results.json',JSON.stringify({checks:results.length,results,viewports:11},null,2))
 console.log('MEGA 4 BROWSER PASS '+results.length+'/'+results.length)
} catch(error){
 for(const [name,page]of [['phone',phone],['wall',wall]])if(page&&!page.isClosed())await page.screenshot({path:'supabase/.temp/mega4/failure-'+name+'.png'}).catch(()=>{})
 throw error
} finally {
 await browser.close()
 for(const id of households)await must(admin.from('households').delete().eq('id',id))
 for(const id of users)await must(admin.auth.admin.deleteUser(id))
}
