import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import assert from 'node:assert/strict'
import {localSupabase} from '../../scripts/local-supabase.mjs'
import {calendarPayload} from '../src/lib/calendar.js'
import {planValues} from '../src/lib/household-plans.js'
const local=localSupabase(),admin=createClient(local.API_URL,local.SERVICE_ROLE_KEY,{auth:{persistSession:false}}),client=()=>createClient(local.API_URL,local.ANON_KEY,{auth:{persistSession:false}})
const must=async q=>{const r=await q;if(r.error)throw Error(r.error.message);return r.data},users=[],households=[],paths=[];let count=0;const pass=s=>console.log('PASS '+(++count)+': '+s)
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')
try{
 const setup=async()=>{const email='recipes-'+randomUUID()+'@example.test',password=randomUUID()+'!Aa1',uid=(await must(admin.auth.admin.createUser({email,password,email_confirm:true}))).user.id;users.push(uid);const c=client();await must(c.auth.signInWithPassword({email,password}));const hid=(await must(c.rpc('create_household',{p_name:'Recipes local test'})));const household=typeof hid==='string'?hid:hid.id||hid[0]?.id;households.push(household);return {c,uid,hid:household}}
 const a=await setup(),b=await setup();assert.ok(a.hid&&b.hid)
 const people=await must(a.c.from('household_people').insert([{household_id:a.hid,name:'Barn',role:'child'},{household_id:a.hid,name:'Voksen',role:'adult'}]).select('*'))
 const other=(await must(b.c.from('household_people').insert({household_id:b.hid,name:'Anden'}).select('*').single()))
 const id=randomUUID(),draft={title:'Lasagne',source_type:'manual',servings:5,total_minutes:55,ingredients:['2 dåser hakkede tomater','Salt efter smag'],instructions:['Rør saucen.','Bag retten.']}
 await must(a.c.rpc('save_recipe',{p_household_id:a.hid,p_id:id,p_recipe:draft}))
 const current=()=>must(a.c.from('recipes').select('*,recipe_ingredients(*),recipe_instructions(*),recipe_ratings(*)').eq('id',id).single())
 let r=await current();assert.equal(r.recipe_ingredients.length,2);assert.equal(r.recipe_instructions.length,2);pass('Manual recipe saved atomically with ordered lines')
 assert.equal((await must(b.c.from('recipes').select('*').eq('id',id))).length,0)
 for(const table of ['recipe_ingredients','recipe_instructions','recipe_ratings'])assert.equal((await must(b.c.from(table).select('*').eq('recipe_id',id))).length,0)
 assert.ok((await b.c.rpc('save_recipe',{p_household_id:a.hid,p_id:id,p_recipe:draft,p_expected:r.updated_at})).error);pass('Other households cannot read recipes/lines/ratings or edit through RPC')
 await must(a.c.rpc('save_recipe',{p_household_id:a.hid,p_id:id,p_recipe:{...draft,title:'Familiens lasagne'},p_expected:r.updated_at}))
 assert.ok((await a.c.rpc('save_recipe',{p_household_id:a.hid,p_id:id,p_recipe:draft,p_expected:r.updated_at})).error);r=await current();assert.equal(r.title,'Familiens lasagne');pass('Editing replaces lines atomically and rejects stale version')
 await must(a.c.from('recipe_ratings').upsert({recipe_id:id,person_id:people[0].id,rating:'love'}));await must(a.c.from('recipe_ratings').upsert({recipe_id:id,person_id:people[0].id,rating:'like'}));r=await current();assert.equal(r.recipe_ratings.length,1);assert.equal(r.recipe_ratings[0].rating,'like')
 assert.ok((await a.c.from('recipe_ratings').insert({recipe_id:id,person_id:other.id,rating:'love'})).error);assert.ok((await a.c.from('recipe_ratings').insert({recipe_id:id,person_id:people[1].id,rating:'five-stars'})).error);pass('One current rating per family person, valid scale, cross-household person rejected')
 const mealId=randomUUID(),meal={id:mealId,...calendarPayload({...planValues('meal',{title:r.title,date:'2026-10-05',note:'Lav dobbelt'}),recipe_id:id,servings_override:6},[])}
 await must(a.c.rpc('sync_calendar_mutation',{p_mutation_id:randomUUID(),p_household_id:a.hid,p_upserts:[meal],p_delete_ids:[],p_expected:[]}))
 const record=await must(a.c.from('calendar_items').select('*').eq('id',mealId).single());assert.equal(record.recipe_id,id);assert.equal(record.note,'Lav dobbelt');assert.equal(record.data.servings_override,6);pass('Existing calendar mutation/offline API preserves recipe FK, meal-specific note and servings')
 assert.ok((await b.c.from('calendar_items').insert({household_id:b.hid,created_by:b.uid,title:'Foreign',type:'Madplan',date:'2026-10-05',data:{recipe_id:id}})).error);pass('Cross-household meal recipe reference rejected by database FK')
 const path=a.hid+'/'+id+'/'+randomUUID()+'.png';paths.push(path);await must(a.c.storage.from('recipe-images').upload(path,png,{contentType:'image/png'}));assert.ok((await a.c.storage.from('recipe-images').createSignedUrl(path,60)).data?.signedUrl);assert.ok((await b.c.storage.from('recipe-images').download(path)).error);assert.ok((await b.c.storage.from('recipe-images').upload(a.hid+'/'+id+'/foreign.png',png,{contentType:'image/png'})).error);const publicResult=await fetch(local.API_URL+'/storage/v1/object/public/recipe-images/'+path);assert.notEqual(publicResult.status,200);pass('Private image bucket: own upload/read succeeds, other households and public access denied')
 await must(a.c.from('recipes').update({image_path:path,archived_at:new Date().toISOString()}).eq('id',id));r=await current();assert.ok(r.archived_at);assert.equal((await must(a.c.from('calendar_items').select('recipe_id').eq('id',mealId).single())).recipe_id,id);assert.ok((await a.c.from('recipes').delete().eq('id',id)).error);pass('Archive preserves planned meal and image; browser cannot hard-delete master')
 const ingredient=r.recipe_ingredients[0],action=randomUUID(),shopping={household_id:a.hid,created_by:a.uid,title:ingredient.raw_text,type:'Indkøb',date:'2026-10-05',data:{recipe_id:id,meal_id:mealId,ingredient_id:ingredient.id,ingredient_raw_text:ingredient.raw_text,recipe_action_id:action}}
 await must(a.c.from('calendar_items').insert(shopping));assert.ok((await a.c.from('calendar_items').insert(shopping)).error);assert.equal((await must(a.c.from('calendar_items').select('data').eq('household_id',a.hid).eq('type','Indkøb')))[0].data.ingredient_raw_text,'2 dåser hakkede tomater');pass('Shopping preserves exact raw text and relations; repeated action rejected without duplicates')
 const exported=await must(a.c.rpc('export_family_data',{p_household_id:a.hid}));assert.equal(exported.recipes[0].ingredients.length,2);assert.equal(exported.recipes[0].ratings.length,1);assert.equal(exported.calendar_and_tasks.find(x=>x.id===mealId).data.servings_override,6);pass('Existing household export includes recipe master, lines, ratings and meal overrides')
 const before=await must(a.c.from('calendar_revisions').select('items_version').eq('household_id',a.hid).single());await must(a.c.from('recipe_ratings').upsert({recipe_id:id,person_id:people[0].id,rating:'love'}));const after=await must(a.c.from('calendar_revisions').select('items_version').eq('household_id',a.hid).single());assert.ok(after.items_version>before.items_version);pass('Rating changes bump existing household realtime revision')
 const scan=await a.c.functions.invoke('recipe-preview',{body:{action:'scan',household_id:a.hid,images:[{mime:'image/png',base64:png.toString('base64')}]}});assert.ok(scan.error);const missing=await scan.error.context.json();assert.equal(missing.error,'VISION_NOT_CONFIGURED');assert.ok(!JSON.stringify(missing).includes('sk-'));pass('Actual local Edge authenticates scan and returns controlled missing-provider configuration')
 assert.ok((await a.c.rpc('recipe_deletion_objects',{p_user_id:a.uid})).error);await must(admin.rpc('begin_account_deletion',{p_user_id:a.uid,p_delete_households:[a.hid]}));const deletionObjects=await must(admin.rpc('recipe_deletion_objects',{p_user_id:a.uid}));assert.ok(deletionObjects.some(o=>o.name===path));assert.equal((await must(admin.from('households').select('id').eq('id',b.hid))).length,1);pass('Account deletion accepts recipe storage and schedules only deleted household image cleanup')
 console.log('RECIPES API PASS '+count)
}finally{if(paths.length)await admin.storage.from('recipe-images').remove(paths);for(const hid of households)await admin.from('households').delete().eq('id',hid);for(const uid of users)await admin.auth.admin.deleteUser(uid)}
