import {chromium,expect as baseExpect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {mkdirSync,writeFileSync} from 'node:fs'
import sharp from 'sharp'
import {localSupabase} from '../../scripts/local-supabase.mjs'
import {routeTo,openSettings} from './browser-actions.mjs'
const expect=baseExpect.configure({timeout:15000})
const local=localSupabase(),admin=createClient(local.API_URL,local.SERVICE_ROLE_KEY,{auth:{persistSession:false}}),out='supabase/.temp/recipes30',root='http://127.0.0.1:5179'
mkdirSync(out,{recursive:true})
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),context=await browser.newContext({locale:'da-DK',viewport:{width:1440,height:1000},timezoneId:'Europe/Copenhagen'}),page=await context.newPage()
page.setDefaultTimeout(14000)
const errors=[],results=[],shots=[],paths=[];let uid,hid,signedBatches=0
page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/storage/v1/object/sign/recipe-images')signedBatches++})
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept())
await context.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort())
const must=async q=>{const r=await q;if(r.error)throw Error(r.error.message);return r.data},pass=s=>{results.push(s);console.log('PASS '+results.length+': '+s)}
const shot=async name=>{await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:out+'/'+name+'.png',fullPage:name==='02-desktop-library-six-recipes'});shots.push(name)}
const fits=async()=>expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
const imageLayout=async()=>{
 const images=page.locator('.meal-recipe-thumbnail,.library-card .recipe-cover')
 await expect.poll(()=>images.evaluateAll(imgs=>imgs.length>1&&imgs.every(img=>img.complete&&img.naturalWidth>0))).toBe(true)
 const layout=await images.evaluateAll(imgs=>imgs.map(img=>{const box=img.getBoundingClientRect(),style=getComputedStyle(img),parent=img.parentElement.getBoundingClientRect(),title=img.parentElement.querySelector('strong')?.getBoundingClientRect();return {meal:img.classList.contains('meal-recipe-thumbnail'),width:box.width,height:box.height,fit:style.objectFit,atTop:Math.abs(box.top-parent.top)<2,textFits:!title||(title.left>=box.right+7&&title.right<=parent.right+1&&title.width>=95)}}))
 for(const img of layout){expect(img.fit).toBe('cover');if(img.meal){expect(img.width).toBe(48);expect(img.height).toBe(48);expect(img.textFits).toBe(true)}else{expect(img.width/img.height).toBeCloseTo(1.5,1);expect(img.atTop).toBe(true)}}
 await fits()
}
const close=async()=>{await page.keyboard.press('Escape');await expect(page.locator('.recipe-modal')).toHaveCount(0)}
const cover=async(title,i=0)=>sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="480"><rect width="800" height="480" fill="'+['#d7ddbb','#ead7b4','#d5ddce','#e6d4c7','#d9dfbb','#d7ded7'][i%6]+'"/><rect x="85" y="55" width="630" height="370" rx="32" fill="#fffcf2"/><circle cx="400" cy="202" r="92" fill="#e5e8d1"/><path d="M325 210h150M340 230h120M360 250h80" stroke="#a6b182" stroke-width="12" stroke-linecap="round"/><text x="400" y="343" font-family="Arial" font-size="30" text-anchor="middle" fill="#4b5a38">'+title+'</text><text x="400" y="387" font-family="Arial" font-size="17" text-anchor="middle" fill="#8b8c78">LOKALT TESTBILLEDE</text></svg>')).jpeg().toBuffer()
const scanPage=async n=>sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="700" height="980"><rect width="700" height="980" fill="#fffdf5"/><text x="60" y="95" font-family="Arial" font-size="37" fill="#314934">Tomatsuppe · Side '+n+'</text><text x="60" y="155" font-family="Arial" font-size="24">TESTFIXTURE · ikke en rigtig scanning</text><text x="60" y="240" font-family="Arial" font-size="28">4 portioner · 30 minutter</text><text x="60" y="330" font-family="Arial" font-size="26">'+(n===1?'2 dåser hakkede tomater':'1. Hak løget og varm olien.')+'</text><text x="60" y="390" font-family="Arial" font-size="26">'+(n===1?'1 løg':'2. Tilsæt tomater og kog op.')+'</text></svg>')).jpeg().toBuffer()
try{
 const email='recipes-browser-'+randomUUID()+'@example.test',password=randomUUID()+'!Aa1'
 uid=(await must(admin.auth.admin.createUser({email,password,email_confirm:true}))).user.id
 hid=(await must(admin.from('households').insert({name:'Familien Tandrup Jakobsen',created_by:uid}).select('id').single())).id
 await must(admin.from('household_members').insert({household_id:hid,user_id:uid,role:'owner'}))
 const people=await must(admin.from('household_people').insert(['Carl','Jakob','Ida','Far','Mor'].map((name,i)=>({household_id:hid,name,role:i<3?'child':'adult',color:['#7c935e','#be8468','#6b939a'][i%3]}))).select('*'))
 const names=['Lasagne','Boller i karry','Tacos','Frikadeller','Kylling i karry','Pasta med kødsovs'],recipes=[]
 for(const [i,title] of names.entries()){const id=randomUUID(),path=hid+'/'+id+'/'+randomUUID()+'.jpg';paths.push(path);await must(admin.storage.from('recipe-images').upload(path,await cover(title,i),{contentType:'image/jpeg'}))
  const r=await must(admin.from('recipes').insert({id,household_id:hid,title,description:['Lag på lag af familiens favoritter. God til en travl uge.','En mild og varm familieret.'][i%2],servings:5,total_minutes:[55,40,25,45,30,30][i],image_path:path,source_type:'manual',created_by:uid,...(i===0?{source_url:'https://example.com/lasagne',source_name:'Familiens opskrifter'}:{})}).select('*').single());recipes.push(r)
  await must(admin.from('recipe_ingredients').insert(['500 g hakket oksekød','2 dåser hakkede tomater','1 løg','Salt efter smag'].map((raw_text,position)=>({recipe_id:id,position,raw_text}))))
  await must(admin.from('recipe_instructions').insert(['Hak løget og svits det i en gryde.','Tilsæt de øvrige ingredienser og lad retten simre.','Servér retten varm, og gem resten til i morgen.'].map((text,position)=>({recipe_id:id,position,text}))))
  await must(admin.from('recipe_ratings').insert(people.map((p,n)=>({recipe_id:id,person_id:p.id,rating:i===0?['love','like','love','love','like'][n]:i===2?'like':n<2?'okay':'like'}))))
 }
 const meal=(r,date,note='')=>({household_id:hid,created_by:uid,title:r.title,date,type:'Madplan',note,data:{recipe_id:r.id,servings_override:6}})
 await must(admin.from('calendar_items').insert([meal(recipes[0],'2026-09-18'),meal(recipes[1],'2026-09-20'),meal(recipes[0],'2026-10-05','Lav dobbelt portion'),meal(recipes[2],'2026-10-06'),meal(recipes[4],'2026-10-08'),{household_id:hid,created_by:uid,title:'Familietur',date:'2026-10-05',time:'16:00',type:'Aktivitet',data:{}},{household_id:hid,created_by:uid,title:'Rester fra i går',date:'2026-10-07',type:'Madplan',data:{}}]))
 const fixtureImage=await cover('Tomatsuppe'),scan1=await scanPage(1),scan2=await scanPage(2)
 let scanCalls=0
 await page.route('**/functions/v1/recipe-preview',async route=>{const b=route.request().postDataJSON();if(b.action==='scan'){scanCalls++;if(scanCalls===1)return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'VISION_NOT_CONFIGURED',message:'Fotoscan er ikke konfigureret endnu. Du kan stadig skrive opskriften manuelt.'})});return route.fulfill({contentType:'application/json',body:JSON.stringify({review_required:true,recipe:{title:'Tomatsuppe fra foto',description:'DEMO: struktureret vision-testfixture, ikke live AI.',ingredients:['2 dåser hakkede tomater','1 løg'],instructions:['Hak løget.','Kog tomater og løg i 20 minutter.'],servings:4,total_minutes:30,incomplete:true,image_candidate:null}})})}
  return route.fulfill({contentType:'application/json',body:JSON.stringify({recipe:{title:'Tomatsuppe',description:'En varm ret til hele familien. DEMO: kontrolleret importfixture.',url:'https://example.com/tomatsuppe',site:'Familiens testkøkken',image:'https://example.com/test-cover.jpg',image_copy:{mime:'image/jpeg',base64:fixtureImage.toString('base64')},ingredients:['2 dåser hakkede tomater','1 løg'],instructions:['Hak løget.','Kog suppen i 20 minutter.'],servings:4,prep_minutes:10,cook_minutes:20,total_minutes:30,format:'jsonld'}})})
 })
 await page.clock.setFixedTime(new Date('2026-10-05T10:00:00+02:00'));await page.goto(root);await page.locator('#email').fill(email);await page.locator('#password').fill(password);await page.locator('#login-form button[type=submit]').click();await expect(page.locator('.product-nav')).toBeVisible()
 await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await routeTo(page,'meals');await expect(page.locator('.recipe-grid .library-card')).toHaveCount(6);await expect(page.locator('.recipe-cover').first()).toBeVisible();await imageLayout();await expect(page.locator('.meal-recipe-thumbnail')).toHaveCount(3);await shot('01-desktop-food-landing');pass('Meal plan shows three decoded, compact 48px private covers with readable text')
 await page.locator('.food-tabs [data-food-tab=recipes]').click();await imageLayout();await shot('02-desktop-library-six-recipes');pass('Recipe covers are aligned at the top, cropped to 3:2 and fully decoded')
 await page.locator('[data-recipe-filter=favorites]').click();await expect(page.locator('.library-card')).toHaveCount(6);await shot('03-desktop-family-favorites');await page.locator('[data-recipe-filter=all]').click()
 const signedBeforeSearch=signedBatches;await page.locator('#recipe-search').fill('Lasagne');await expect(page.locator('.library-card')).toHaveCount(1);await page.locator('#recipe-search').fill('');expect(signedBatches).toBe(signedBeforeSearch);pass('Desktop library, real private storage images, search and family-favorite filter')
 await page.locator('[data-recipe-open="'+recipes[0].id+'"]').click();await expect(page.locator('.recipe-family select')).toHaveCount(5);await expect(page.locator('.recipe-detail-meta')).toContainText('Lavet 2 gange');await shot('04-desktop-detail-ratings')
 const signedBeforeRating=signedBatches;await page.locator('[data-recipe-rating="'+people[0].id+'"]').selectOption('dislike');await expect.poll(async()=>(await must(admin.from('recipe_ratings').select('rating').eq('recipe_id',recipes[0].id).eq('person_id',people[0].id).single())).rating).toBe('dislike');expect(signedBatches).toBe(signedBeforeRating);pass('Personal rating changes persist without re-signing unchanged covers; usage derives from actual meals')
 await page.locator('[data-detail-plan]').click();await page.locator('#recipe-plan-date').fill('2026-10-09');await page.locator('#recipe-plan-note').fill('Lav dobbelt portion');await shot('05-desktop-plan-dialog');await page.locator('#recipe-plan-form button[type=submit]').click();await expect(page.locator('.recipe-modal')).toHaveCount(0)
 const planned=await must(admin.from('calendar_items').select('*').eq('household_id',hid).eq('date','2026-10-09').eq('type','Madplan').single());expect(planned.recipe_id).toBe(recipes[0].id);expect(planned.note).toBe('Lav dobbelt portion');pass('Recipe reuse creates independent dated meal with note and servings')
 await page.locator('[data-recipe-url]').click();await shot('06-desktop-url-input');await page.locator('#library-recipe-url').fill('https://example.com/tomatsuppe');await page.locator('#recipe-url-form button').click();await expect(page.locator('#recipe-title')).toHaveValue('Tomatsuppe');await expect(page.locator('#recipe-image-preview img')).toBeVisible();await shot('07-desktop-url-preview-image');await page.locator('#recipe-editor button[type=submit]').click();await expect(page.locator('#recipe-dialog-title')).toHaveText('Tomatsuppe');await close();pass('URL import stays editable, then stores library recipe and private copied cover')
 await page.locator('[data-recipe-url]').click();await page.locator('#library-recipe-url').fill('https://example.com/lasagne?utm_source=x');await page.locator('#recipe-url-form button').click();await expect(page.locator('.recipe-modal')).toContainText('findes allerede');await page.locator('[data-duplicate-open]').click();await expect(page.locator('#recipe-dialog-title')).toHaveText('Lasagne');await close();pass('Canonical source URL warns and opens existing recipe without title merging')
 await page.locator('[data-recipe-scan]').click();await shot('08-desktop-scan-entry');await page.locator('#scan-files').setInputFiles([{name:'page1.jpg',mimeType:'image/jpeg',buffer:scan1},{name:'page2.jpg',mimeType:'image/jpeg',buffer:scan2}]);await expect(page.locator('.scan-page')).toHaveCount(2);await shot('09-desktop-scan-multipage');await page.locator('[data-scan-up="1"]').click();await page.locator('#scan-analyse').click();await expect(page.locator('.recipe-error')).toContainText('ikke konfigureret');expect(await must(admin.from('recipes').select('id').eq('household_id',hid))).toHaveLength(7);pass('Multipage upload/reorder reaches server; missing provider shows real error and never saves')
 await page.locator('#scan-analyse').click();await expect(page.locator('#recipe-title')).toHaveValue('Tomatsuppe fra foto');await expect(page.locator('.recipe-review-note')).toContainText('ikke læse hele');await expect(page.locator('[data-scan-cover]')).toHaveCount(2);await expect(page.locator('#recipe-image-preview img')).toHaveCount(0);await shot('10-desktop-scan-analysed-DEMO');await close()
 await page.locator('[data-recipe-new]').click();await page.locator('#recipe-title').fill('Grøntsagssuppe');await page.locator('#recipe-ingredients').fill('2 gulerødder\n1 løg');await page.locator('#recipe-instructions').fill('Hak grøntsagerne.\nKog dem møre.');await shot('11-desktop-manual-editor');await page.locator('#recipe-editor button[type=submit]').click();await expect(page.locator('#recipe-dialog-title')).toHaveText('Grøntsagssuppe');await close();const plainCard=page.locator('.library-card').filter({hasText:'Grøntsagssuppe'});await expect(plainCard.locator('img,.recipe-placeholder')).toHaveCount(0);expect((await plainCard.boundingBox()).height).toBeLessThan(200);pass('Manual recipe without image has a compact text card, no reserved image frame')
 await page.locator('[data-recipe-open="'+recipes[0].id+'"]').click();await page.locator('[data-detail-shop]').click();await page.locator('#recipe-shopping-form input').last().uncheck();await shot('12-desktop-ingredient-selection');const add=page.locator('#recipe-shopping-form button');await add.dblclick();await expect(page.locator('.recipe-modal')).toHaveCount(0);const shopping=await must(admin.from('calendar_items').select('*').eq('household_id',hid).eq('type','Indkøb'));expect(shopping).toHaveLength(3);expect(shopping.map(x=>x.data.ingredient_raw_text)).toContain('2 dåser hakkede tomater');pass('Selected ingredients preserve text/recipe relation; double click creates only one action')
 await page.locator('[data-food-tab=meals]').first().click();await imageLayout();await shot('13-desktop-meal-plan')
 await page.locator('[data-plan-edit="'+planned.id+'"]').click();await page.locator('[data-edit-meal]').click();await page.locator('#plan-note').fill('Kun til fredag');await page.locator('#plan-form button[type=submit]').click();await expect(page.locator('#plan-modal')).toHaveCount(0);expect((await must(admin.from('calendar_items').select('note').eq('id',planned.id).single())).note).toBe('Kun til fredag');expect((await must(admin.from('recipes').select('description').eq('id',recipes[0].id).single())).description).not.toBe('Kun til fredag');pass('Meal editing leaves master recipe untouched')
 const peer=await context.newPage();await peer.goto(root);await routeTo(peer,'meals');await peer.locator('[data-food-tab=recipes]').first().click();await peer.locator('[data-recipe-open="'+recipes[0].id+'"]').click()
 await must(admin.from('recipe_ratings').upsert({recipe_id:recipes[0].id,person_id:people[1].id,rating:'dislike'}));await expect(peer.locator('[data-recipe-rating="'+people[1].id+'"]')).toHaveValue('dislike');await peer.close();pass('Second active browser receives rating changes through existing realtime channel')
 for(const [width,height] of [[375,667],[390,844],[430,932]]){
  await page.setViewportSize({width,height});await routeTo(page,'meals');await imageLayout();await shot('14-mobile-food-landing-'+width)
  await page.locator('[data-food-tab=recipes]').first().click();await imageLayout();await expect(page.locator('.library-card .recipe-placeholder')).toHaveCount(0);await shot('15-mobile-library-'+width)
  await page.locator('[data-recipe-open="'+recipes[0].id+'"]').click();await fits();await shot('16-mobile-detail-'+width);if(width===390){await page.locator('.recipe-family').scrollIntoViewIfNeeded();await shot('17-mobile-rating-ui')}
  await page.locator('[data-detail-plan]').click();await fits();if(width===390)await shot('21-mobile-plan-date');await close()
  await page.locator('[data-recipe-scan]').click();await fits();if(width===390)await shot('18-mobile-camera-entry');await expect(page.locator('#scan-camera')).toHaveAttribute('capture','environment')
  await page.locator('#scan-files').setInputFiles([{name:'page1.jpg',mimeType:'image/jpeg',buffer:scan1},{name:'page2.jpg',mimeType:'image/jpeg',buffer:scan2}]);await expect(page.locator('.scan-page')).toHaveCount(2);if(width===390)await shot('19-mobile-multipage');await page.locator('#scan-analyse').click();await expect(page.locator('#recipe-title')).toHaveValue('Tomatsuppe fra foto');await fits();if(width===390)await shot('20-mobile-analysed-DEMO');await close()
  await page.locator('[data-food-tab=shopping]').first().click();await fits();if(width===390)await shot('22-mobile-shopping')
 }
 pass('375×667, 390×844, 430×932: library/detail/camera/multipage/planning/shopping without horizontal overflow')
 // Real image response failure: keep text/actions and collapse the thumbnail/cover space.
 await page.setViewportSize({width:1440,height:1000})
 const missingCover=recipes[0].image_path,brokenRoute='**/storage/v1/object/sign/recipe-images/'+missingCover+'?*'
 await page.route(brokenRoute,r=>r.fulfill({status:404,body:''}))
 await page.reload();await routeTo(page,'meals');await expect(page.locator('.meal-card [data-plan-edit] strong').filter({hasText:'Lasagne'}).first()).toBeVisible()
 await expect(page.locator('.meal-card [data-plan-edit]').filter({hasText:'Lasagne'}).locator('img')).toHaveCount(0)
 await page.locator('[data-food-tab=recipes]').first().click();const brokenCard=page.locator('[data-recipe-open="'+recipes[0].id+'"]')
 await expect(brokenCard).toBeVisible();await expect(brokenCard.locator('img,.recipe-placeholder')).toHaveCount(0);await fits();await shot('25-desktop-image-fallback')
 await page.unroute(brokenRoute);await page.reload();await routeTo(page,'meals');await imageLayout();pass('404 cover fallback leaves recipe titles/actions readable, removes empty frames, and recovers after reload')

 await page.locator('[data-food-tab=recipes]').first().click();await expect(page.locator('.library-card')).toHaveCount(8);await context.setOffline(true);await page.reload();await expect(page.locator('.library-card')).toHaveCount(8);await expect(page.locator('.recipe-library')).toContainText('Offline');await context.setOffline(false);pass('Existing offline foundation restores library text and ratings from household cache')
 await page.setViewportSize({width:1280,height:800});await openSettings(page,'device');await page.locator('#device-kiosk').check();await page.locator('#device-pin').fill('1948');await page.locator('#device-settings-form button[type=submit]').click();await expect(page.locator('body')).toHaveAttribute('data-mode','kiosk')
 await routeTo(page,'today');await fits();await shot('23-kiosk-today-meal')
 await routeTo(page,'calendar');await fits();await shot('24-kiosk-week-meals');await expect(page.locator('.week-grid>.day-card')).toHaveCount(7);await expect(page.locator('[data-recipe-new],[data-recipe-scan],[data-recipe-url]')).toHaveCount(0)
 await page.locator('[data-plan-edit]').first().click();await expect(page.locator('.recipe-steps')).toBeVisible();await expect(page.locator('[data-recipe-rating],[data-detail-edit],[data-detail-plan]')).toHaveCount(0);await close();pass('Kiosk retains compact calendar/meal integration and read-only recipe view')
 expect(errors).toEqual([]);pass('No uncaught browser interaction errors')
 writeFileSync(out+'/results.json',JSON.stringify({results,shots,fixtures:'Local disposable family; labelled synthetic cover/page images. URL and successful scan browser responses are deterministic TEST fixtures, not live vision. Actual Edge missing-provider, parsing and security tested separately.'},null,2))
 writeFileSync(out+'/review.html','<!doctype html><html lang="da"><meta charset="utf-8"><title>Mad & opskrifter 3.0</title><style>body{font:16px system-ui;background:#f6f2e8;color:#334b34;margin:28px}nav{display:flex;gap:12px;flex-wrap:wrap}section{margin:36px 0}img{max-width:100%;border:1px solid #c4cbb5;border-radius:12px}a{color:inherit}.demo{background:#ede3c6;border-radius:10px;padding:16px}</style><h1>Mad & opskrifter 3.0 · lokal visuel review</h1><p class="demo">DEMO / TESTDATA: Alle familier, retter og billeder er lokale testfixtures. Billederne er tydeligt mærkede testpladsholdere. URL-preview og analyserede fotos viser kontrollerede fixtures, IKKE en succesfuld live vision-analyse. Live scan kræver server-secret OPENAI_API_KEY. Intet er deployet.</p><nav>'+shots.map(n=>'<a href="#'+n+'">'+n+'</a>').join('')+'</nav>'+shots.map(n=>'<section id="'+n+'"><h2>'+n+'</h2><a href="'+n+'.png"><img loading="lazy" src="'+n+'.png" alt="'+n+'"></a></section>').join('')+'</html>')
 console.log('RECIPES BROWSER PASS '+results.length+' checks, '+shots.length+' screenshots')
}catch(error){await page.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});throw error}
finally{await browser.close();if(paths.length)await admin.storage.from('recipe-images').remove(paths);if(hid)await admin.from('households').delete().eq('id',hid);if(uid)await admin.auth.admin.deleteUser(uid)}
