import {materialize,planEdit,itemValues} from '../src/lib/calendar-semantics.js'
import {calendarPayload} from '../src/lib/calendar.js'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {localSupabase} from '../../scripts/local-supabase.mjs'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
const live=process.argv.includes('--allow-live-tests'),project='oyyqniwppytipdktzwsy'
function liveConfig(){try{const keys=JSON.parse(execFileSync('cmd.exe',['/d','/s','/c','npx.cmd --yes supabase@2.118.0 projects api-keys --project-ref '+project+' --reveal --output json'],{encoding:'utf8',windowsHide:true,stdio:['ignore','pipe','pipe']}));return {API_URL:'https://'+project+'.supabase.co',ANON_KEY:keys.find(k=>k.name==='anon').api_key,SERVICE_ROLE_KEY:keys.find(k=>k.name==='service_role').api_key}}catch{throw Error('Live credentials could not be loaded safely.')}}
const local=live?liveConfig():localSupabase(),opts={auth:{persistSession:false,autoRefreshToken:false}},admin=createClient(local.API_URL,local.SERVICE_ROLE_KEY,opts),users=[],households=[],checks=[]
const reportPath='supabase/.temp/rewards2-'+(live?'live':'local')+'-api.json';mkdirSync('supabase/.temp',{recursive:true});const report=(cleanup=false)=>writeFileSync(reportPath,JSON.stringify({project:live?project:'local',checks,fixture_users:users,fixture_households:households,cleanup,updated_at:new Date().toISOString()},null,2))
const must=async q=>{const r=await q;if(r.error)throw Error(r.error.message);return r.data}
const check=(label,value)=>{if(!value)throw Error('FAIL '+label);checks.push(label);console.log('PASS '+checks.length+': '+label)}
const client=async(role,hid)=>{const email='rewards-v2-'+randomUUID()+'@example.test',password=randomUUID()+'Aa!1';const u=(await must(admin.auth.admin.createUser({email,password,email_confirm:true}))).user;users.push(u.id);report();const c=createClient(local.API_URL,local.PUBLISHABLE_KEY||local.ANON_KEY,opts);await must(c.auth.signInWithPassword({email,password}));if(hid)await must(admin.from('household_members').insert({household_id:hid,user_id:u.id,role}));return c}
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Copenhagen',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const call=(c,hid,action,payload,id=randomUUID())=>c.rpc('reward_action',{p_request_id:id,p_household_id:hid,p_action:action,p_payload:payload})
let owner,child,other,hid,p1,p2
try{
 owner=await client();hid=await must(owner.rpc('create_household',{p_name:'Rewards V2 isolated'}));households.push(hid);report();child=await client('child',hid);other=await client();const foreign=await must(other.rpc('create_household',{p_name:'Foreign rewards'}));households.push(foreign);report()
 const people=await must(owner.from('household_people').insert(['Carl','Ida'].map(name=>({household_id:hid,name,role:'child'}))).select());[p1,p2]=people
 const config=p=>({person_id:p.id,reward_enabled:true,allowance_enabled:true,monthly_allowance_minor:10000,star_rewards_enabled:true,default_requires_approval:false})
 await must(call(owner,hid,'config',config(p1)));await must(call(owner,hid,'config',config(p2)))
 check('Child cannot configure rewards',Boolean((await call(child,hid,'config',config(p1))).error))
 check('Outsider cannot read state',Boolean((await other.rpc('get_reward_state',{p_household_id:hid})).error))
 check('RLS hides foreign config',(await must(other.from('reward_person_config').select('*').eq('household_id',hid))).length===0)
 const make=async(mode='allowance',extra={})=>must(owner.from('calendar_items').insert({id:randomUUID(),household_id:hid,created_by:(await owner.auth.getUser()).data.user.id,title:'Testopgave',date:today,type:'Opgave',person_ids:[p1.id],person:'Carl',done:false,data:{rewardMode:mode,starValue:mode==='stars'?10:0,requiresApproval:false,...extra}}).select().single())
 const payload=(t,p=p1)=>({item_id:t.id,person_id:p.id,occurrence_date:today,due_date:today})
 await must(call(owner,hid,'allowance_save',{person_id:p1.id,cadence:'week',amount_minor:10000,start_today:true,duties:Array.from({length:20},(_,n)=>({title:'Fast pligt '+n,schedule:'weekly',approval:false}))}))
 await must(call(owner,hid,'allowance_save',{person_id:p2.id,cadence:'week',amount_minor:10000,start_today:true,duties:[]}))
 const tasks=(await must(owner.rpc('get_reward_state',{p_household_id:hid}))).occurrences.filter(o=>o.person_id===p1.id).map(o=>({id:o.task_id,date:o.due_date}))
 for(const t of tasks.slice(0,10))await must(call(child,hid,'complete',payload(t)))
 let state=await must(owner.rpc('get_reward_state',{p_household_id:hid})),month=state.monthly.find(m=>m.person_id===p1.id)
 check('10 / 20 = 50 percent',month.eligible_total===20&&month.completed_total===10&&month.completion_percent===50)
 check('10000 ore yields 5000 ore',month.earned_minor===5000)
 for(const t of tasks.slice(10))await must(call(child,hid,'complete',payload(t)))
 month=(await must(owner.rpc('get_reward_state',{p_household_id:hid}))).monthly.find(m=>m.person_id===p1.id)
 check('20 / 20 = full allowance',month.earned_minor===10000)
 await must(call(owner,hid,'excuse',{...payload(tasks[19]),reason:'Syg'}));month=(await must(owner.rpc('get_reward_state',{p_household_id:hid}))).monthly.find(m=>m.person_id===p1.id)
 check('Excused removed from numerator and denominator',month.eligible_total===19&&month.completed_total===19&&month.excused_total===1)
 check('Child cannot undo an adult excuse',Boolean((await call(child,hid,'undo',payload(tasks[19]))).error))
 check('Child cannot excuse',Boolean((await call(child,hid,'excuse',payload(tasks[0]))).error))
 await must(call(owner,hid,'unexcuse',payload(tasks[19])))
 const shared=await make('allowance');await must(owner.from('calendar_items').update({person_ids:[p1.id,p2.id],person:'Alle'}).eq('id',shared.id));await must(call(child,hid,'complete',payload(shared)))
 state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Multi-person completion is independent',state.monthly.find(m=>m.person_id===p2.id).completed_total===0)
 const all=await make('allowance');await must(owner.from('calendar_items').update({person_ids:[],person:'Alle',data:{rewardMode:'allowance',people:['Alle']}}).eq('id',all.id));await must(call(child,hid,'complete',payload(all,p2)));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Unlinked legacy tasks cannot change frozen contracts',state.monthly.find(m=>m.person_id===p2.id).eligible_total===0&&state.monthly.find(m=>m.person_id===p2.id).completed_total===0)
 const pending=await make('stars',{requiresApproval:true});const req=randomUUID();await must(call(child,hid,'complete',payload(pending),req));await must(call(child,hid,'complete',payload(pending),req));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Pending completion grants no stars',!state.balances.length&&state.occurrences.find(s=>s.task_id===pending.id).status==='pending')
 check('Child cannot approve',Boolean((await call(child,hid,'approve',payload(pending))).error));await must(call(owner,hid,'approve',payload(pending)));await must(call(owner,hid,'approve',payload(pending)));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Approve twice awards once',state.balances.find(b=>b.person_id===p1.id).balance===10&&state.ledger.filter(l=>l.source_type==='task_award').length===1)
 await must(call(owner,hid,'reject',payload(pending)));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Reject after approve reverses ledger',state.balances.find(b=>b.person_id===p1.id).balance===0&&state.ledger.length===2)
 await must(call(child,hid,'complete',payload(pending)));await must(call(owner,hid,'approve',payload(pending)));await must(call(child,hid,'undo',payload(pending)));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Undo preserves history and reverses award',state.balances.find(b=>b.person_id===p1.id).balance===0&&state.ledger.length===4)
 const bonus=await make('stars',{starValue:100});await must(call(child,hid,'complete',payload(bonus)));await must(call(child,hid,'complete',payload(bonus)));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Unapproved bonus awards exactly once',state.balances.find(b=>b.person_id===p1.id).balance===100)
 check('Direct ledger write denied',Boolean((await child.from('reward_star_ledger').insert({household_id:hid,person_id:p1.id,delta:999,reason:'forged',source_type:'task_award',source_id:bonus.id,idempotency_key:randomUUID()})).error))
 check('Child cannot elevate task reward',Boolean((await child.from('calendar_items').update({data:{rewardMode:'stars',starValue:9999}}).eq('id',bonus.id)).error))
 check('Child cannot delete configured reward task',Boolean((await child.from('calendar_items').delete().eq('id',bonus.id)).error))
 check('Child cannot forge inherited reward rule',Boolean((await child.from('calendar_items').insert({id:randomUUID(),household_id:hid,created_by:(await child.auth.getUser()).data.user.id,title:'Forged override',date:today,type:'Opgave',data:{overrideBaseId:bonus.id,overrideOf:bonus.id,originalDate:today}})).error))
 const reward=(await must(call(owner,hid,'catalog',{title:'Biograftur',emoji:'🎬',star_cost:75}))).id
 check('Catalog created by adult',Boolean(reward));check('Child cannot edit catalog',Boolean((await call(child,hid,'catalog',{id:reward,title:'Gratis',star_cost:1})).error))
 await must(call(child,hid,'goal',{person_id:p1.id,reward_id:reward}));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Goal does not reserve balance',state.goals[0].reward_id===reward&&state.balances.find(b=>b.person_id===p1.id).balance===100)
 check('Insufficient stars rejected',Boolean((await call(child,hid,'redeem',{person_id:p2.id,reward_id:reward})).error))
 const red=(await must(call(child,hid,'redeem',{person_id:p1.id,reward_id:reward}))).id
 state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Pending redemption has no debit',state.balances.find(b=>b.person_id===p1.id).balance===100)
 await must(call(owner,hid,'redemption_approve',{id:red}));await must(call(owner,hid,'redemption_approve',{id:red}));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Redemption debited once',state.balances.find(b=>b.person_id===p1.id).balance===25&&state.ledger.filter(l=>l.source_type==='redemption').length===1)
 await must(call(owner,hid,'redemption_fulfill',{id:red}));check('Reward can be fulfilled',(await must(owner.from('reward_redemptions').select('status').eq('id',red).single())).status==='fulfilled')
 const cheap=(await must(call(owner,hid,'catalog',{title:'Vælg aftensmad',star_cost:20}))).id,cheap2=(await must(call(owner,hid,'catalog',{title:'Ekstra læsetid',star_cost:20}))).id
 const reds=await Promise.all([cheap,cheap2].map(async reward_id=>(await must(call(child,hid,'redeem',{person_id:p1.id,reward_id}))).id));const approvals=await Promise.all(reds.map(id=>call(owner,hid,'redemption_approve',{id})));check('Simultaneous approval cannot overdraw',approvals.filter(r=>!r.error).length===1);state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Balance remains nonnegative after race',state.balances.find(b=>b.person_id===p1.id).balance===5)
 const unapproved=reds[approvals.findIndex(r=>r.error)];await must(call(owner,hid,'redemption_cancel',{id:unapproved}));check('Pending request cancelled without debit',(await must(owner.from('reward_redemptions').select('status').eq('id',unapproved).single())).status==='cancelled')
 await must(call(owner,hid,'catalog',{id:reward,title:'Biograftur',star_cost:75,active:false}));check('Disabled reward clears goal',(await must(owner.from('reward_goals').select('*').eq('person_id',p1.id))).length===0)
 const pool=await make('stars',{starValue:25,bonusPool:true,requiresApproval:true});const claims=await Promise.all([p1,p2].map(p=>call(child,hid,'claim',payload(pool,p))));check('Simultaneous bonus claim has one winner',claims.filter(r=>!r.error).length===1);const winner=[p1,p2][claims.findIndex(r=>!r.error)];await must(call(child,hid,'complete',payload(pool,winner)));await must(call(owner,hid,'approve',payload(pool,winner)));check('Claimed bonus can complete and approve',(await must(owner.from('task_reward_occurrences').select('*').eq('task_id',pool.id).single())).awarded_delta===25)
 const recurring=await make('stars',{starValue:12,repeatWeekly:true});await must(call(child,hid,'complete',payload(recurring)))
 const edit=async(item,scope,title)=>{const rows=await must(owner.from('calendar_items').select('*').eq('household_id',hid));const plan=planEdit(rows,item,{...itemValues(item),title},scope);return must(owner.rpc('sync_calendar_mutation',{p_mutation_id:randomUUID(),p_household_id:hid,p_expected:plan.expected,p_delete_ids:plan.deleteIds,p_upserts:plan.upserts.map(({id,values})=>({id,...calendarPayload(values,people)}))}))}
 const instance=materialize([recurring],[today],{milestones:false})[0];await edit(instance,'one','Tilpasset bonus');let rows=await must(owner.from('calendar_items').select('*').eq('household_id',hid));const override=materialize(rows,[today],{milestones:false}).find(t=>t.title==='Tilpasset bonus');state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));const awards=state.ledger.filter(l=>l.source_type==='task_award').length;await must(call(child,hid,'complete',{...payload(override),item_id:override.id}));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Only-this override retains identity and never re-awards',state.ledger.filter(l=>l.source_type==='task_award').length===awards)
 await edit(override,'future','Fremtidig bonus');rows=await must(owner.from('calendar_items').select('*').eq('household_id',hid));const future=materialize(rows,[today],{milestones:false}).find(t=>t.title==='Fremtidig bonus');await must(call(child,hid,'complete',{...payload(future),item_id:future.isRepeatOccurrence?future.baseId:future.id}));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Future split retains reward origin and award idempotency',state.ledger.filter(l=>l.source_type==='task_award').length===awards)
 const originalDate=bonus.date;const tomorrow=new Date(today+'T12:00:00');tomorrow.setDate(tomorrow.getDate()+1);const tomorrowISO=new Intl.DateTimeFormat('en-CA').format(tomorrow)
 await must(owner.from('calendar_items').update({date:tomorrowISO}).eq('id',bonus.id));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));const moved=await must(owner.from('calendar_items').select('*').eq('id',bonus.id).single());check('Moving a one-off keeps original occurrence and completed state',moved.data.originalDate===originalDate&&state.occurrences.find(s=>s.task_id===bonus.id).status==='completed'&&state.occurrences.find(s=>s.task_id===bonus.id).due_date===tomorrowISO)
 const started=await make('stars',{requiresApproval:true,starValue:7});await must(call(child,hid,'complete',payload(started)));await must(owner.from('calendar_items').update({data:{...started.data,rewardMode:'none',starValue:0,requiresApproval:false}}).eq('id',started.id));await must(call(owner,hid,'approve',payload(started)));state=await must(owner.rpc('get_reward_state',{p_household_id:hid}));check('Rule changes cannot rewrite already started occurrence',state.occurrences.find(s=>s.task_id===started.id).awarded_delta===7)
 const exported=await must(owner.rpc('export_family_data',{p_household_id:hid}));check('Export includes full reward ledger and config',exported.rewards_v2.ledger.length>5&&exported.rewards_v2.configs.length===2)
 const milestoneHousehold=await must(owner.rpc('create_household',{p_name:'Milestone race isolated'}));households.push(milestoneHousehold);report();const milestonePerson=await must(owner.from('household_people').insert({household_id:milestoneHousehold,name:'Milestone child',role:'child'}).select().single());await must(call(owner,milestoneHousehold,'config',config(milestonePerson)))
 await must(call(owner,milestoneHousehold,'allowance_save',{person_id:milestonePerson.id,cadence:'week',amount_minor:10000,start_today:true,duties:[{title:'One fixed task',schedule:'weekly',approval:false}]}));
 const milestoneTask={id:(await must(owner.rpc('get_reward_state',{p_household_id:milestoneHousehold}))).occurrences[0].task_id};
 await must(call(owner,milestoneHousehold,'complete',payload(milestoneTask,milestonePerson)))
 const monthArgs={p_household_id:milestoneHousehold,p_person_id:milestonePerson.id,p_month_start:today};
 const milestoneClaims=await Promise.all([1,2].map(()=>must(owner.rpc('claim_reward_milestone',monthArgs))));check('Concurrent devices display monthly milestone once',milestoneClaims.filter(Boolean).length===1)
 check('Milestone retry never displays twice',!(await must(owner.rpc('claim_reward_milestone',monthArgs))))
 check('Other household cannot claim milestone',Boolean((await other.rpc('claim_reward_milestone',monthArgs)).error))
 check('Tasks never write deprecated weekly celebration rows',(await must(owner.from('reward_celebrations').select('id').eq('household_id',hid))).length===0)
 console.log('REWARDS V2 API PASS '+checks.length+'/'+checks.length)
}finally{const errors=[];for(const id of [...households].reverse()){try{await must(admin.from('households').delete().eq('id',id))}catch{errors.push(id)}}for(const id of users){try{await must(admin.auth.admin.deleteUser(id))}catch{errors.push(id)}}report(!errors.length);if(errors.length)throw Error('Fixture cleanup failed for IDs: '+errors.join(', '))}
