import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {RewardTransitions,fullMonth} from '../src/lib/reward-transitions.js'
import {emptyRewards,monthProgress,optimisticReward} from '../src/lib/rewards-model.js'
const month=(done=0)=>({person_id:'p',year:2026,month:9,eligible_total:2,completed_total:done,completion_percent:done*50,earned_minor:done*5000,allowance_minor:10000})
const state=()=>({...emptyRewards(),monthly:[month()],balances:[{person_id:'p',balance:0}],goals:[{person_id:'p',reward_id:'g'}],catalog:[{id:'g',active:true,title:'Biograftur',star_cost:20}]})
const award=(s,id,delta)=>{s.ledger.push({id,person_id:'p',delta,source_type:delta>0?'task_award':'task_reversal',source_id:'o',created_at:'2026-09-30T10:00:00Z'});s.balances[0].balance+=delta;return s}
const setup=()=>{const s=state(),t=new RewardTransitions();t.hydrate(s);return {s,t}}
test('Initial and repeated historical hydration never produces reward events',()=>{const s=award(state(),'old',20);s.monthly=[month(2)];const t=new RewardTransitions();assert.deepEqual(t.observe(s),[]);t.hydrate(s);assert.deepEqual(t.observe(s),[])})
test('Allowance emits exact before/after percentage and integer money',()=>{const {s,t}=setup();s.monthly=[month(1)];const e=t.observe(s).find(e=>e.kind==='allowance');assert.equal(e.from.completion_percent,0);assert.equal(e.to.completion_percent,50);assert.equal(e.to.earned_minor,5000);assert.equal(e.milestone,false)})
test('Approval pending never advances confirmed monthly totals',()=>{const {s,t}=setup();s.occurrences=[{id:'o',task_id:'task',person_id:'p',revision:1,status:'pending'}];assert.deepEqual(t.observe(s).map(e=>e.kind),['task']);s.occurrences[0].status='approved';s.occurrences[0].revision=2;s.monthly=[month(1)];assert.ok(t.observe(s).some(e=>e.kind==='allowance'))})
test('100 percent requests a milestone only on a real crossing',()=>{const {s,t}=setup();s.monthly=[month(2)];assert.equal(t.observe(s).find(e=>e.kind==='allowance').milestone,true);assert.deepEqual(t.observe(s),[])})
test('Rounded percent alone and zero tasks never equal a completed month',()=>{assert.equal(fullMonth({...month(),completion_percent:100,eligible_total:100000,completed_total:99999}),false);assert.equal(fullMonth({...month(),eligible_total:0}),false)})
test('Month rollover establishes a quiet new monthly baseline',()=>{const {s,t}=setup();s.monthly=[{...month(2),month:10}];assert.deepEqual(t.observe(s),[])})
test('Ledger award is observed once across duplicate realtime and replay',()=>{const {s,t}=setup();award(s,'award',10);assert.equal(t.observe(s).filter(e=>e.kind==='stars').length,1);assert.deepEqual(t.observe(structuredClone(s)),[])})
test('Pending bonus completion cannot produce stars or a goal transition',()=>{const {s,t}=setup();s.occurrences=[{id:'o',person_id:'p',revision:1,status:'pending',star_value:20}];assert.ok(t.observe(s).every(e=>!['stars','goal','balance'].includes(e.kind)))})
test('Approved ledger award updates balance and goal together',()=>{const {s,t}=setup();award(s,'award',10);const events=t.observe(s);assert.equal(events.find(e=>e.kind==='balance').to,10);assert.equal(events.find(e=>e.kind==='goal').unlocked,false)})
test('Goal unlock is a single meaningful crossing',()=>{const {s,t}=setup();award(s,'award',20);assert.equal(t.observe(s).find(e=>e.kind==='goal').unlocked,true);assert.deepEqual(t.observe(s),[])})
test('Selecting an already affordable goal never pretends stars were earned',()=>{const {s,t}=setup();s.catalog[0].star_cost=0;assert.deepEqual(t.observe(s),[])})
test('Reversal is negative, updates balance and does not unlock',()=>{const {s,t}=setup();award(s,'award',20);t.observe(s);award(s,'reverse',-10);const e=t.observe(s);assert.equal(e.find(e=>e.kind==='stars').delta,-10);assert.equal(e.find(e=>e.kind==='balance').from,20);assert.equal(e.find(e=>e.kind==='goal').unlocked,false);assert.deepEqual(t.observe(s),[])})
test('Redemption pending has no debit, approval debits once',()=>{const {s,t}=setup();s.redemptions=[{id:'r',person_id:'p',status:'pending'}];assert.deepEqual(t.observe(s).map(e=>e.kind),['redemption']);award(s,'redeem',-20);s.ledger[0].source_type='redemption';s.ledger[0].source_id='r';s.redemptions[0].status='approved';const e=t.observe(s);assert.equal(e.find(e=>e.kind==='stars').redemptionId,'r');assert.equal(e.find(e=>e.kind==='redemption').status,'approved');assert.deepEqual(t.observe(s),[])})
test('Multiple independent ledger events are not lost in one snapshot',()=>{const {s,t}=setup();award(s,'a',10);award(s,'b',10);assert.equal(t.observe(s).filter(e=>e.kind==='stars').length,2)})
test('Offline optimistic allowance keeps the last confirmed kroner',()=>{const s=state(),entry={payload:{reward_action:{action:'complete',payload:{person_id:'p',item_id:'task',occurrence_date:'2026-09-30'},optimistic:{origin_id:'task',reward_mode:'allowance',requires_approval:false}}}};const view=optimisticReward(s,entry);assert.equal(view.occurrences[0].status,'completed');assert.equal(monthProgress([],[],view,'p','2026-09-30').earned_minor,0)})
test('Offline overlay then confirmed replay produces only one monetary transition',()=>{const {s,t}=setup();s.monthly=[month(1)];assert.equal(t.observe(s).filter(e=>e.kind==='allowance').length,1);assert.deepEqual(t.observe(s),[])})
test('Reset and new household hydration do not replay another household events',()=>{const {s,t}=setup();award(s,'a',20);t.observe(s);t.reset();t.hydrate(s);assert.deepEqual(t.observe(s),[])})
test('Active frontend has no weekly tiers, confetti or celebration queries',()=>{for(const file of ['src/main.js','src/lib/task-rewards.js','src/lib/rewards-ui.js','src/lib/offline-sync.js'])assert.doesNotMatch(readFileSync(new URL('../'+file,import.meta.url),'utf8'),/🪙|🟨|💎|👑|Superstjerne|Hverdagshelt|Legende|reward_celebrations|weekly_celebration_enabled|confetti/)})
