import test from 'node:test'
import assert from 'node:assert/strict'
import {emptyRewards,monthProgress,parseCurrency,currency,rewardRule,actionPayload,optimisticReward,starBalance,taskComplete} from '../src/lib/rewards-model.js'
import {monthDates} from '../src/lib/calendar-dates.js'
import {materialize,planEdit} from '../src/lib/calendar-semantics.js'
import {weeklyProgress} from '../src/lib/task-rewards.js'
import {OfflineSync} from '../src/lib/offline-sync.js'
const people=[{id:'p',name:'Carl',role:'child',reward_enabled:true},{id:'q',name:'Ida',role:'child',reward_enabled:true}]
const state=()=>({...emptyRewards(),configs:people.map(p=>({person_id:p.id,monthly_allowance_minor:10000,history:[{from:'2028-01-01',enabled:true,allowance:true,amount:10000}]}))})
const task=(id,date='2028-01-15',data={})=>({id,date,type:'Opgave',title:id,person:'Alle',person_ids:[],done:false,data:{rewardOriginId:id,rewardRules:[{from:date,mode:'allowance',stars:0,approval:false,pool:false}],...data}})
const completed=(t,pid='p',status='completed')=>({origin_id:t.data.rewardOriginId,task_id:t.id,occurrence_date:t.date,due_date:t.date,person_id:pid,reward_mode:'allowance',status})
test('Money parser keeps integer ore and rejects malformed or overflowing amounts',()=>{assert.equal(parseCurrency('100'),10000);assert.equal(parseCurrency('125,50'),12550);assert.equal(parseCurrency('0.01'),1);for(const s of ['-1','1e4','1.234','abc','1000001'])assert.throws(()=>parseCurrency(s));assert.match(currency(12550),/125,50/);assert.match(currency(10000),/100/);})
test('Confirmed kroner never change when mutable tasks are added or removed',()=>{const s=state();s.monthly=[{person_id:'p',year:2028,month:1,eligible_total:20,completed_total:10,earned_minor:5000}];assert.equal(monthProgress([],people,s,'p','2028-01-15').earned_minor,5000);assert.equal(monthProgress(Array.from({length:100},(_,n)=>task('t'+n)),people,s,'p','2028-01-15').earned_minor,5000)})
test('No confirmed period is neutral rather than a guessed allowance',()=>{const s=state(),rows=[task('a')];s.occurrences=[completed(rows[0])];const m=monthProgress(rows,people,s,'p','2028-01-15');assert.equal(m.earned_minor,0);assert.equal(m.completion_percent,0);assert.equal(m.neutral,'not_started')})
test('Multi-person and Alle states never complete another person',()=>{const s=state(),t=task('a');s.occurrences=[completed(t)];assert.equal(monthProgress([t],people,s,'q','2028-01-15').completed_total,0);assert.equal(taskComplete(t,people,s),false);assert.equal(taskComplete(t,people,s,'p'),true)})
for(const [day,count] of [['2028-02-01',5],['2029-02-01',4],['2028-12-01',5],['2029-01-01',5]])test('Weekly plan over civil month '+day,()=>{const s=state(),t=task('weekly',day,{repeatWeekly:true});assert.equal(materialize([t],monthDates(day),{milestones:false}).length,count)})
test('Start, end, exceptions and moved override count only actual occurrences',()=>{const s=state(),t=task('base','2028-01-15',{repeatWeekly:true,repeatUntil:'2028-01-29',exceptions:['2028-01-22']});const o=task('override','2028-01-23',{rewardOriginId:'base',overrideOf:'base',overrideBaseId:'base',originalDate:'2028-01-22'});assert.equal(materialize([t,o],monthDates('2028-01-01'),{milestones:false}).length,3);assert.equal(actionPayload(materialize([t,o],['2028-01-23'])[0],'p').item_id,'override')})
test('Closed snapshot wins over current source edits',()=>{const s=state();s.snapshots=[{person_id:'p',year:2028,month:1,earned_minor:8700}];assert.equal(monthProgress([],people,s,'p','2028-01-15').earned_minor,8700)})
test('Participation edits do not rewrite the confirmed current contract',()=>{const s=state();s.monthly=[{person_id:'p',year:2028,month:1,eligible_total:30,earned_minor:1000}];s.configs[0].history.push({from:'2028-01-20',enabled:false,allowance:true});assert.equal(monthProgress([],people,s,'p','2028-01-15').eligible_total,30)})
test('Server rule history prevents retroactive rewards',()=>{const t=task('old','2028-01-01',{rewardRules:[{from:'2028-01-20',mode:'stars',stars:100,approval:true,pool:false}]});assert.equal(rewardRule(t).mode,'none');assert.equal(rewardRule({...t,date:'2028-01-21'}).mode,'stars')})
test('Approval state is shared by week and allowance without duplicate counting',()=>{const s=state(),t=task('a');s.occurrences=[completed(t,'p','pending')];assert.equal(weeklyProgress([t],people,'2028-01-15','2028-01-15',s)[0].count,0);s.occurrences[0].status='approved';assert.equal(weeklyProgress([t],people,'2028-01-15','2028-01-15',s)[0].count,1)})
class Memory{constructor(){this.map=new Map()}async get(k){return structuredClone(this.map.get(k))}async update(k,fn){const s=fn(await this.get(k));this.map.set(k,structuredClone(s));return s}}
test('Offline completion durable replay after response loss uses same receipt; no optimistic stars',async t=>{
 let online=false,first=true;const receipts=new Map(),server=state(),store=new Memory(),calls=[];const client={rpc:async(name,p)=>{calls.push(p.p_request_id);assert.equal(name,'reward_action');if(!receipts.has(p.p_request_id)){server.balances=[{person_id:'p',balance:10}];server.occurrences=[{...completed(task('a')),reward_mode:'stars'}];receipts.set(p.p_request_id,true)}if(first){first=false;return {error:{message:'network failed'}}}return {data:{rewards:structuredClone(server),celebrations:[]}}}}
 const e=await new OfflineSync({store,client,userId:'u',householdId:'h',online:()=>online}).init();t.after(()=>e.stop());await e.snapshot({rewards:state()});const p={p_expected:[],p_upserts:[],p_delete_ids:[],reward_action:{action:'complete',payload:{person_id:'p',item_id:'a',occurrence_date:'2028-01-15',due_date:'2028-01-15'},optimistic:{origin_id:'a',requires_approval:true,reward_mode:'stars',star_value:10}}};await e.enqueue(p,{action:'reward_complete',entityId:'a|p'});assert.equal(e.view.rewards.occurrences[0].status,'pending');assert.equal(starBalance(e.view.rewards,'p'),0);await e.reload();assert.equal(e.state.queue.length,1);online=true;await e.replay();assert.equal(e.state.queue.length,1);await e.replay();assert.equal(e.state.queue.length,0);assert.equal(starBalance(e.view.rewards,'p'),10);assert.equal(receipts.size,1);assert.equal(calls[0],calls[1])
})
test('Rejected offline reward action rolls back optimistic state',async t=>{const e=await new OfflineSync({store:new Memory(),client:{rpc:async()=>({error:{code:'42501',message:'Denied'}}),from:()=>({select:()=>({eq:()=>({order:()=>({range:async()=>({data:[],error:null})})})})})},userId:'u',householdId:'h',online:()=>true}).init();t.after(()=>e.stop());await e.enqueue({p_expected:[],p_upserts:[],p_delete_ids:[],reward_action:{action:'complete',payload:{person_id:'p',occurrence_date:'2028-01-15'},optimistic:{origin_id:'a'}}},{action:'reward_complete'});assert.equal(e.view.rewards.occurrences.length,0);assert.equal(e.state.queue[0].status,'error')})